-------------------------------------------------------------------------------
-- SPDX-FileCopyrightText: 2025 CERN (home.cern)
--
-- SPDX-License-Identifier: CERN-OHL-W-2.0+
-------------------------------------------------------------------------------
-- Do not edit.  Generated by cheby 1.7.dev0 using these options:
--  -i auxclk_regs.cheby --gen-hdl auxclk_regs.vhd
-- Generated on Wed Jan 21 16:11:11 2026 by tgingold


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;

package auxclk_gen_regs_pkg is
  type t_auxclk_regs_master_out is record
    PR_hp_width      : std_logic_vector(15 downto 0);
    PR_wr            : std_logic;
    DCR_low_width    : std_logic_vector(15 downto 0);
    DCR_wr           : std_logic;
  end record t_auxclk_regs_master_out;
  subtype t_auxclk_regs_slave_in is t_auxclk_regs_master_out;

  type t_auxclk_regs_slave_out is record
    PR_hp_width      : std_logic_vector(15 downto 0);
    DCR_low_width    : std_logic_vector(15 downto 0);
  end record t_auxclk_regs_slave_out;
  subtype t_auxclk_regs_master_in is t_auxclk_regs_slave_out;

end auxclk_gen_regs_pkg;

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;
use work.auxclk_gen_regs_pkg.all;

entity auxclk_gen_regs is
  port (
    rst_n_i              : in    std_logic;
    clk_i                : in    std_logic;
    wb_i                 : in    t_wishbone_slave_in;
    wb_o                 : out   t_wishbone_slave_out;
    -- Wires and registers
    auxclk_regs_i        : in    t_auxclk_regs_master_in;
    auxclk_regs_o        : out   t_auxclk_regs_master_out
  );
end auxclk_gen_regs;

architecture syn of auxclk_gen_regs is
  signal adr_int                        : std_logic_vector(2 downto 2);
  signal rd_req_int                     : std_logic;
  signal wr_req_int                     : std_logic;
  signal rd_ack_int                     : std_logic;
  signal wr_ack_int                     : std_logic;
  signal wb_en                          : std_logic;
  signal ack_int                        : std_logic;
  signal wb_rip                         : std_logic;
  signal wb_wip                         : std_logic;
  signal PR_wreq                        : std_logic;
  signal DCR_wreq                       : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(2 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
begin

  -- WB decode signals
  adr_int <= wb_i.adr(2 downto 2);
  wb_en <= wb_i.cyc and wb_i.stb;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_rip <= '0';
      else
        wb_rip <= (wb_rip or (wb_en and not wb_i.we)) and not rd_ack_int;
      end if;
    end if;
  end process;
  rd_req_int <= (wb_en and not wb_i.we) and not wb_rip;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_wip <= '0';
      else
        wb_wip <= (wb_wip or (wb_en and wb_i.we)) and not wr_ack_int;
      end if;
    end if;
  end process;
  wr_req_int <= (wb_en and wb_i.we) and not wb_wip;

  ack_int <= rd_ack_int or wr_ack_int;
  wb_o.ack <= ack_int;
  wb_o.stall <= not ack_int and wb_en;
  wb_o.rty <= '0';
  wb_o.err <= '0';

  -- pipelining for wr-in+rd-out
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        rd_ack_int <= '0';
        wb_o.dat <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_adr_d0 <= "0";
        wr_dat_d0 <= "00000000000000000000000000000000";
      else
        rd_ack_int <= rd_ack_d0;
        wb_o.dat <= rd_dat_d0;
        wr_req_d0 <= wr_req_int;
        wr_adr_d0 <= adr_int;
        wr_dat_d0 <= wb_i.dat;
      end if;
    end if;
  end process;

  -- Register PR
  auxclk_regs_o.PR_hp_width <= wr_dat_d0(15 downto 0);
  auxclk_regs_o.PR_wr <= PR_wreq;

  -- Register DCR
  auxclk_regs_o.DCR_low_width <= wr_dat_d0(15 downto 0);
  auxclk_regs_o.DCR_wr <= DCR_wreq;

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0) begin
    PR_wreq <= '0';
    DCR_wreq <= '0';
    case wr_adr_d0(2 downto 2) is
    when "0" =>
      -- Reg PR
      PR_wreq <= wr_req_d0;
      wr_ack_int <= wr_req_d0;
    when "1" =>
      -- Reg DCR
      DCR_wreq <= wr_req_d0;
      wr_ack_int <= wr_req_d0;
    when others =>
      wr_ack_int <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (adr_int, rd_req_int, auxclk_regs_i.PR_hp_width,
           auxclk_regs_i.DCR_low_width) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    case adr_int(2 downto 2) is
    when "0" =>
      -- Reg PR
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(15 downto 0) <= auxclk_regs_i.PR_hp_width;
      rd_dat_d0(31 downto 16) <= (others => '0');
    when "1" =>
      -- Reg DCR
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(15 downto 0) <= auxclk_regs_i.DCR_low_width;
      rd_dat_d0(31 downto 16) <= (others => '0');
    when others =>
      rd_ack_d0 <= rd_req_int;
    end case;
  end process;
end syn;
