files = [
    'gtwizard_ultrascale_qpll_example_bit_sync.v',
    'gtwizard_ultrascale_qpll_example_checking_8b10b.v',
    'gtwizard_ultrascale_qpll_example_gtwiz_reset.v',
    'gtwizard_ultrascale_qpll_example_gtwiz_userclk_rx.v',
    'gtwizard_ultrascale_qpll_example_gtwiz_userclk_tx.v',
    'gtwizard_ultrascale_qpll_example_init.v',
    'gtwizard_ultrascale_qpll_example_reset_inv_sync.v',
    'gtwizard_ultrascale_qpll_example_reset_sync.v',
    'gtwizard_ultrascale_qpll_example_stimulus_8b10b.v',
    'gtwizard_ultrascale_qpll_example_top_sim.v',
    'gtwizard_ultrascale_qpll_example_top.v',
    'gtwizard_ultrascale_qpll_example_top.xdc',
    'gtwizard_ultrascale_qpll_example_wrapper_functions.v',
    'gtwizard_ultrascale_qpll_example_wrapper.v',
    'gtwizard_ultrascale_qpll_gthe4_common_wrapper.v',
    'gtwizard_ultrascale_qpll_prbs_any.v',
    'gtwizard_ultrascale_v1_7_gthe4_common.v',

    'gtwizard_ultrascale_qpll.v',
    'gtwizard_ultrascale_qpll_gtwizard_top.v',
    'gtwizard_ultrascale_qpll_gtwizard_gthe4.v',
    'gtwizard_ultrascale_qpll_gthe4_channel_wrapper.v',
]
