-- Do not edit.  Generated by cheby 1.7.dev0 using these options:
--  -i drp_map.cheby --gen-hdl
-- Generated on Fri Jun 06 14:39:07 2025 by tgingold


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;

entity drp_map is
  port (
    rst_n_i              : in    std_logic;
    clk_i                : in    std_logic;
    wb_i                 : in    t_wishbone_slave_in;
    wb_o                 : out   t_wishbone_slave_out;

    -- Address
    addr_o               : out   std_logic_vector(15 downto 0);

    -- Data and control
    -- Data (read or write)
    control_data_i       : in    std_logic_vector(15 downto 0);
    control_data_o       : out   std_logic_vector(15 downto 0);
    -- Set when a new transaction is possible
    control_rdy_i        : in    std_logic;
    control_rdy_o        : out   std_logic;
    -- 1 for write, 0 for read
    control_we_i         : in    std_logic;
    control_we_o         : out   std_logic;
    -- Set to start a transaction, always read as 0.
    control_en_i         : in    std_logic;
    control_en_o         : out   std_logic;
    -- Set for reset, always read as 0.
    control_rst_i        : in    std_logic;
    control_rst_o        : out   std_logic;
    control_wr_o         : out   std_logic
  );
end drp_map;

architecture syn of drp_map is
  signal adr_int                        : std_logic_vector(2 downto 2);
  signal rd_req_int                     : std_logic;
  signal wr_req_int                     : std_logic;
  signal rd_ack_int                     : std_logic;
  signal wr_ack_int                     : std_logic;
  signal wb_en                          : std_logic;
  signal ack_int                        : std_logic;
  signal wb_rip                         : std_logic;
  signal wb_wip                         : std_logic;
  signal addr_reg                       : std_logic_vector(15 downto 0);
  signal addr_wreq                      : std_logic;
  signal addr_wack                      : std_logic;
  signal control_wreq                   : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(2 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
begin

  -- WB decode signals
  adr_int <= wb_i.adr(2 downto 2);
  wb_en <= wb_i.cyc and wb_i.stb;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_rip <= '0';
      else
        wb_rip <= (wb_rip or (wb_en and not wb_i.we)) and not rd_ack_int;
      end if;
    end if;
  end process;
  rd_req_int <= (wb_en and not wb_i.we) and not wb_rip;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_wip <= '0';
      else
        wb_wip <= (wb_wip or (wb_en and wb_i.we)) and not wr_ack_int;
      end if;
    end if;
  end process;
  wr_req_int <= (wb_en and wb_i.we) and not wb_wip;

  ack_int <= rd_ack_int or wr_ack_int;
  wb_o.ack <= ack_int;
  wb_o.stall <= not ack_int and wb_en;
  wb_o.rty <= '0';
  wb_o.err <= '0';

  -- pipelining for wr-in+rd-out
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        rd_ack_int <= '0';
        wb_o.dat <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_adr_d0 <= "0";
        wr_dat_d0 <= "00000000000000000000000000000000";
      else
        rd_ack_int <= rd_ack_d0;
        wb_o.dat <= rd_dat_d0;
        wr_req_d0 <= wr_req_int;
        wr_adr_d0 <= adr_int;
        wr_dat_d0 <= wb_i.dat;
      end if;
    end if;
  end process;

  -- Register addr
  addr_o <= addr_reg;
  addr_wack <= addr_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        addr_reg <= "0000000000000000";
      else
        if addr_wreq = '1' then
          addr_reg <= wr_dat_d0(15 downto 0);
        end if;
      end if;
    end if;
  end process;

  -- Register control
  control_data_o <= wr_dat_d0(15 downto 0);
  control_rdy_o <= wr_dat_d0(16);
  control_we_o <= wr_dat_d0(17);
  control_en_o <= wr_dat_d0(18);
  control_rst_o <= wr_dat_d0(19);
  control_wr_o <= control_wreq;

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0, addr_wack) begin
    addr_wreq <= '0';
    control_wreq <= '0';
    case wr_adr_d0(2 downto 2) is
    when "0" =>
      -- Reg addr
      addr_wreq <= wr_req_d0;
      wr_ack_int <= addr_wack;
    when "1" =>
      -- Reg control
      control_wreq <= wr_req_d0;
      wr_ack_int <= wr_req_d0;
    when others =>
      wr_ack_int <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (adr_int, rd_req_int, addr_reg, control_data_i, control_rdy_i,
           control_we_i, control_en_i, control_rst_i) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    case adr_int(2 downto 2) is
    when "0" =>
      -- Reg addr
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(15 downto 0) <= addr_reg;
      rd_dat_d0(31 downto 16) <= (others => '0');
    when "1" =>
      -- Reg control
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(15 downto 0) <= control_data_i;
      rd_dat_d0(16) <= control_rdy_i;
      rd_dat_d0(17) <= control_we_i;
      rd_dat_d0(18) <= control_en_i;
      rd_dat_d0(19) <= control_rst_i;
      rd_dat_d0(31 downto 20) <= (others => '0');
    when others =>
      rd_ack_d0 <= rd_req_int;
    end case;
  end process;
end syn;
