-- Do not edit.  Generated by cheby 1.7.dev0 using these options:
--  --gen-hdl mpsoc_map.vhd --gen-c mpsoc_map.h -i mpsoc_map.cheby
-- Generated on Mon Jan 12 09:18:45 2026 by tgingold


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;

entity mpsoc_map is
  port (
    aclk                 : in    std_logic;
    areset_n             : in    std_logic;
    awvalid              : in    std_logic;
    awready              : out   std_logic;
    awaddr               : in    std_logic_vector(14 downto 2);
    awprot               : in    std_logic_vector(2 downto 0);
    wvalid               : in    std_logic;
    wready               : out   std_logic;
    wdata                : in    std_logic_vector(31 downto 0);
    wstrb                : in    std_logic_vector(3 downto 0);
    bvalid               : out   std_logic;
    bready               : in    std_logic;
    bresp                : out   std_logic_vector(1 downto 0);
    arvalid              : in    std_logic;
    arready              : out   std_logic;
    araddr               : in    std_logic_vector(14 downto 2);
    arprot               : in    std_logic_vector(2 downto 0);
    rvalid               : out   std_logic;
    rready               : in    std_logic;
    rdata                : out   std_logic_vector(31 downto 0);
    rresp                : out   std_logic_vector(1 downto 0);

    -- WB bus wrpc_host
    wrpc_host_i          : in    t_wishbone_master_in;
    wrpc_host_o          : out   t_wishbone_master_out;

    -- control register
    ctrl_led1_o          : out   std_logic;
    ctrl_led2_o          : out   std_logic;
    ctrl_gth_rst_o       : out   std_logic;
    ctrl_gth_tx_rst_o    : out   std_logic;
    ctrl_gth_tx_pcs_rst_o : out   std_logic;
    ctrl_gth_tx_pma_rst_o : out   std_logic;
    ctrl_gth_rx_rst_o    : out   std_logic;
    ctrl_gth_rx_pcs_rst_o : out   std_logic;
    ctrl_gth_rx_pma_rst_o : out   std_logic;
    ctrl_gth_rx_buf_rst_o : out   std_logic;

    -- REG status
    status_i             : in    std_logic_vector(31 downto 0);

    -- REG qpll0_sdm
    qpll0_sdm_o          : out   std_logic_vector(31 downto 0);
    qpll0_sdm_wr_o       : out   std_logic;

    -- REG qpll1_sdm
    qpll1_sdm_o          : out   std_logic_vector(31 downto 0);
    qpll1_sdm_wr_o       : out   std_logic;

    -- number of rxpi samples to accumulate
    rxpi_nsamp_o         : out   std_logic_vector(31 downto 0);

    -- Number of tags
    rxpi_count_i         : in    std_logic_vector(31 downto 0);

    -- REG rxpi_tag
    rxpi_tag_i           : in    std_logic_vector(31 downto 0);

    -- rxpi (7b) samples
    rxpi_direct_i        : in    std_logic_vector(31 downto 0);

    -- control of bitslide
    bitslide_force_o     : out   std_logic;
    bitslide_slide_i     : in    std_logic;
    bitslide_slide_o     : out   std_logic;
    bitslide_value_i     : in    std_logic_vector(4 downto 0);
    bitslide_value_o     : out   std_logic_vector(4 downto 0);
    bitslide_wr_o        : out   std_logic;

    -- REG nbr_comma_det
    nbr_comma_det_i      : in    std_logic_vector(31 downto 0);

    -- REG nbr_byte_align
    nbr_byte_align_i     : in    std_logic_vector(31 downto 0);

    -- WB bus wrpc_device
    wrpc_device_i        : in    t_wishbone_master_in;
    wrpc_device_o        : out   t_wishbone_master_out;

    -- WB bus wrpc_aux
    wrpc_aux_i           : in    t_wishbone_master_in;
    wrpc_aux_o           : out   t_wishbone_master_out
  );
end mpsoc_map;

architecture syn of mpsoc_map is
  signal wr_req                         : std_logic;
  signal wr_ack                         : std_logic;
  signal wr_addr                        : std_logic_vector(14 downto 2);
  signal wr_data                        : std_logic_vector(31 downto 0);
  signal wr_sel                         : std_logic_vector(31 downto 0);
  signal axi_awset                      : std_logic;
  signal axi_wset                       : std_logic;
  signal axi_wdone                      : std_logic;
  signal rd_req                         : std_logic;
  signal rd_ack                         : std_logic;
  signal rd_addr                        : std_logic_vector(14 downto 2);
  signal rd_data                        : std_logic_vector(31 downto 0);
  signal axi_arset                      : std_logic;
  signal axi_rdone                      : std_logic;
  signal wrpc_host_re                   : std_logic;
  signal wrpc_host_we                   : std_logic;
  signal wrpc_host_wt                   : std_logic;
  signal wrpc_host_rt                   : std_logic;
  signal wrpc_host_tr                   : std_logic;
  signal wrpc_host_wack                 : std_logic;
  signal wrpc_host_rack                 : std_logic;
  signal wrpc_host_wr                   : std_logic;
  signal wrpc_host_rr                   : std_logic;
  signal ctrl_led1_reg                  : std_logic;
  signal ctrl_led2_reg                  : std_logic;
  signal ctrl_gth_rst_reg               : std_logic;
  signal ctrl_gth_tx_rst_reg            : std_logic;
  signal ctrl_gth_tx_pcs_rst_reg        : std_logic;
  signal ctrl_gth_tx_pma_rst_reg        : std_logic;
  signal ctrl_gth_rx_rst_reg            : std_logic;
  signal ctrl_gth_rx_pcs_rst_reg        : std_logic;
  signal ctrl_gth_rx_pma_rst_reg        : std_logic;
  signal ctrl_gth_rx_buf_rst_reg        : std_logic;
  signal ctrl_wreq                      : std_logic;
  signal ctrl_wack                      : std_logic;
  signal qpll0_sdm_reg                  : std_logic_vector(31 downto 0);
  signal qpll0_sdm_wreq                 : std_logic;
  signal qpll0_sdm_wack                 : std_logic;
  signal qpll0_sdm_wstrb                : std_logic;
  signal qpll1_sdm_reg                  : std_logic_vector(31 downto 0);
  signal qpll1_sdm_wreq                 : std_logic;
  signal qpll1_sdm_wack                 : std_logic;
  signal qpll1_sdm_wstrb                : std_logic;
  signal rxpi_nsamp_reg                 : std_logic_vector(31 downto 0);
  signal rxpi_nsamp_wreq                : std_logic;
  signal rxpi_nsamp_wack                : std_logic;
  signal bitslide_force_reg             : std_logic;
  signal bitslide_wreq                  : std_logic;
  signal bitslide_wack                  : std_logic;
  signal bitslide_wstrb                 : std_logic;
  signal wrpc_device_re                 : std_logic;
  signal wrpc_device_we                 : std_logic;
  signal wrpc_device_wt                 : std_logic;
  signal wrpc_device_rt                 : std_logic;
  signal wrpc_device_tr                 : std_logic;
  signal wrpc_device_wack               : std_logic;
  signal wrpc_device_rack               : std_logic;
  signal wrpc_device_wr                 : std_logic;
  signal wrpc_device_rr                 : std_logic;
  signal wrpc_aux_re                    : std_logic;
  signal wrpc_aux_we                    : std_logic;
  signal wrpc_aux_wt                    : std_logic;
  signal wrpc_aux_rt                    : std_logic;
  signal wrpc_aux_tr                    : std_logic;
  signal wrpc_aux_wack                  : std_logic;
  signal wrpc_aux_rack                  : std_logic;
  signal wrpc_aux_wr                    : std_logic;
  signal wrpc_aux_rr                    : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(14 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_sel_d0                      : std_logic_vector(31 downto 0);
begin

  -- AW, W and B channels
  awready <= not axi_awset;
  wready <= not axi_wset;
  bvalid <= axi_wdone;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        wr_req <= '0';
        axi_awset <= '0';
        axi_wset <= '0';
        axi_wdone <= '0';
      else
        wr_req <= '0';
        if awvalid = '1' and axi_awset = '0' then
          wr_addr <= awaddr;
          axi_awset <= '1';
          wr_req <= axi_wset;
        end if;
        if wvalid = '1' and axi_wset = '0' then
          wr_data <= wdata;
          wr_sel(7 downto 0) <= (others => wstrb(0));
          wr_sel(15 downto 8) <= (others => wstrb(1));
          wr_sel(23 downto 16) <= (others => wstrb(2));
          wr_sel(31 downto 24) <= (others => wstrb(3));
          axi_wset <= '1';
          wr_req <= axi_awset or awvalid;
        end if;
        if (axi_wdone and bready) = '1' then
          axi_wset <= '0';
          axi_awset <= '0';
          axi_wdone <= '0';
        end if;
        if wr_ack = '1' then
          axi_wdone <= '1';
        end if;
      end if;
    end if;
  end process;
  bresp <= "00";

  -- AR and R channels
  arready <= not axi_arset;
  rvalid <= axi_rdone;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        rd_req <= '0';
        axi_arset <= '0';
        axi_rdone <= '0';
        rdata <= (others => '0');
      else
        rd_req <= '0';
        if arvalid = '1' and axi_arset = '0' then
          rd_addr <= araddr;
          axi_arset <= '1';
          rd_req <= '1';
        end if;
        if (axi_rdone and rready) = '1' then
          axi_arset <= '0';
          axi_rdone <= '0';
        end if;
        if rd_ack = '1' then
          axi_rdone <= '1';
          rdata <= rd_data;
        end if;
      end if;
    end if;
  end process;
  rresp <= "00";

  -- pipelining for wr-in+rd-out
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        rd_ack <= '0';
        rd_data <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_adr_d0 <= "0000000000000";
        wr_dat_d0 <= "00000000000000000000000000000000";
        wr_sel_d0 <= "00000000000000000000000000000000";
      else
        rd_ack <= rd_ack_d0;
        rd_data <= rd_dat_d0;
        wr_req_d0 <= wr_req;
        wr_adr_d0 <= wr_addr;
        wr_dat_d0 <= wr_data;
        wr_sel_d0 <= wr_sel;
      end if;
    end if;
  end process;

  -- Interface wrpc_host
  wrpc_host_tr <= wrpc_host_wt or wrpc_host_rt;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        wrpc_host_rt <= '0';
        wrpc_host_wt <= '0';
        wrpc_host_wr <= '0';
        wrpc_host_rr <= '0';
      else
        wrpc_host_wr <= (wrpc_host_wr or wrpc_host_we) and not wrpc_host_wack;
        wrpc_host_wt <= (wrpc_host_wt or (wrpc_host_wr and not wrpc_host_tr)) and not wrpc_host_wack;
        wrpc_host_rr <= (wrpc_host_rr or wrpc_host_re) and not wrpc_host_rack;
        wrpc_host_rt <= (wrpc_host_rt or (wrpc_host_rr and not (wrpc_host_wr or wrpc_host_tr))) and not wrpc_host_rack;
      end if;
    end if;
  end process;
  wrpc_host_o.cyc <= wrpc_host_tr;
  wrpc_host_o.stb <= wrpc_host_tr;
  wrpc_host_wack <= wrpc_host_i.ack and wrpc_host_wt;
  wrpc_host_rack <= wrpc_host_i.ack and wrpc_host_rt;
  process (rd_addr, wr_adr_d0, wrpc_host_wt) begin
    if wrpc_host_wt = '1' then
      wrpc_host_o.adr <= ((19 downto 0 => '0') & wr_adr_d0(11 downto 2)) & (1 downto 0 => '0');
    else
      wrpc_host_o.adr <= ((19 downto 0 => '0') & rd_addr(11 downto 2)) & (1 downto 0 => '0');
    end if;
  end process;
  process (wr_sel_d0) begin
    wrpc_host_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      wrpc_host_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      wrpc_host_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      wrpc_host_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      wrpc_host_o.sel(3) <= '1';
    end if;
  end process;
  wrpc_host_o.we <= wrpc_host_wt;
  wrpc_host_o.dat <= wr_dat_d0;

  -- Register ctrl
  ctrl_led1_o <= ctrl_led1_reg;
  ctrl_led2_o <= ctrl_led2_reg;
  ctrl_gth_rst_o <= ctrl_gth_rst_reg;
  ctrl_gth_tx_rst_o <= ctrl_gth_tx_rst_reg;
  ctrl_gth_tx_pcs_rst_o <= ctrl_gth_tx_pcs_rst_reg;
  ctrl_gth_tx_pma_rst_o <= ctrl_gth_tx_pma_rst_reg;
  ctrl_gth_rx_rst_o <= ctrl_gth_rx_rst_reg;
  ctrl_gth_rx_pcs_rst_o <= ctrl_gth_rx_pcs_rst_reg;
  ctrl_gth_rx_pma_rst_o <= ctrl_gth_rx_pma_rst_reg;
  ctrl_gth_rx_buf_rst_o <= ctrl_gth_rx_buf_rst_reg;
  ctrl_wack <= ctrl_wreq;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        ctrl_led1_reg <= '0';
        ctrl_led2_reg <= '0';
        ctrl_gth_rst_reg <= '0';
        ctrl_gth_tx_rst_reg <= '0';
        ctrl_gth_tx_pcs_rst_reg <= '0';
        ctrl_gth_tx_pma_rst_reg <= '0';
        ctrl_gth_rx_rst_reg <= '0';
        ctrl_gth_rx_pcs_rst_reg <= '0';
        ctrl_gth_rx_pma_rst_reg <= '0';
        ctrl_gth_rx_buf_rst_reg <= '0';
      else
        if ctrl_wreq = '1' then
          ctrl_led1_reg <= wr_dat_d0(0);
          ctrl_led2_reg <= wr_dat_d0(1);
          ctrl_gth_rst_reg <= wr_dat_d0(2);
          ctrl_gth_tx_rst_reg <= wr_dat_d0(4);
          ctrl_gth_tx_pcs_rst_reg <= wr_dat_d0(5);
          ctrl_gth_tx_pma_rst_reg <= wr_dat_d0(6);
          ctrl_gth_rx_rst_reg <= wr_dat_d0(8);
          ctrl_gth_rx_pcs_rst_reg <= wr_dat_d0(9);
          ctrl_gth_rx_pma_rst_reg <= wr_dat_d0(10);
          ctrl_gth_rx_buf_rst_reg <= wr_dat_d0(11);
        end if;
      end if;
    end if;
  end process;

  -- Register status

  -- Register qpll0_sdm
  qpll0_sdm_o <= qpll0_sdm_reg;
  qpll0_sdm_wack <= qpll0_sdm_wreq;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        qpll0_sdm_reg <= "00000000000000000000000000000000";
        qpll0_sdm_wstrb <= '0';
      else
        if qpll0_sdm_wreq = '1' then
          qpll0_sdm_reg <= wr_dat_d0;
        end if;
        qpll0_sdm_wstrb <= qpll0_sdm_wreq;
      end if;
    end if;
  end process;
  qpll0_sdm_wr_o <= qpll0_sdm_wstrb;

  -- Register qpll1_sdm
  qpll1_sdm_o <= qpll1_sdm_reg;
  qpll1_sdm_wack <= qpll1_sdm_wreq;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        qpll1_sdm_reg <= "00000000000000000000000000000000";
        qpll1_sdm_wstrb <= '0';
      else
        if qpll1_sdm_wreq = '1' then
          qpll1_sdm_reg <= wr_dat_d0;
        end if;
        qpll1_sdm_wstrb <= qpll1_sdm_wreq;
      end if;
    end if;
  end process;
  qpll1_sdm_wr_o <= qpll1_sdm_wstrb;

  -- Register rxpi_nsamp
  rxpi_nsamp_o <= rxpi_nsamp_reg;
  rxpi_nsamp_wack <= rxpi_nsamp_wreq;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        rxpi_nsamp_reg <= "00000000000000000111111111111111";
      else
        if rxpi_nsamp_wreq = '1' then
          rxpi_nsamp_reg <= wr_dat_d0;
        end if;
      end if;
    end if;
  end process;

  -- Register rxpi_count

  -- Register rxpi_tag

  -- Register rxpi_direct

  -- Register bitslide
  bitslide_force_o <= bitslide_force_reg;
  bitslide_slide_o <= wr_dat_d0(1);
  bitslide_value_o <= wr_dat_d0(12 downto 8);
  bitslide_wack <= bitslide_wreq;
  bitslide_wstrb <= bitslide_wreq;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        bitslide_force_reg <= '0';
      else
        if bitslide_wreq = '1' then
          bitslide_force_reg <= wr_dat_d0(0);
        end if;
      end if;
    end if;
  end process;
  bitslide_wr_o <= bitslide_wstrb;

  -- Register nbr_comma_det

  -- Register nbr_byte_align

  -- Interface wrpc_device
  wrpc_device_tr <= wrpc_device_wt or wrpc_device_rt;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        wrpc_device_rt <= '0';
        wrpc_device_wt <= '0';
        wrpc_device_wr <= '0';
        wrpc_device_rr <= '0';
      else
        wrpc_device_wr <= (wrpc_device_wr or wrpc_device_we) and not wrpc_device_wack;
        wrpc_device_wt <= (wrpc_device_wt or (wrpc_device_wr and not wrpc_device_tr)) and not wrpc_device_wack;
        wrpc_device_rr <= (wrpc_device_rr or wrpc_device_re) and not wrpc_device_rack;
        wrpc_device_rt <= (wrpc_device_rt or (wrpc_device_rr and not (wrpc_device_wr or wrpc_device_tr))) and not wrpc_device_rack;
      end if;
    end if;
  end process;
  wrpc_device_o.cyc <= wrpc_device_tr;
  wrpc_device_o.stb <= wrpc_device_tr;
  wrpc_device_wack <= wrpc_device_i.ack and wrpc_device_wt;
  wrpc_device_rack <= wrpc_device_i.ack and wrpc_device_rt;
  process (rd_addr, wr_adr_d0, wrpc_device_wt) begin
    if wrpc_device_wt = '1' then
      wrpc_device_o.adr <= ((19 downto 0 => '0') & wr_adr_d0(11 downto 2)) & (1 downto 0 => '0');
    else
      wrpc_device_o.adr <= ((19 downto 0 => '0') & rd_addr(11 downto 2)) & (1 downto 0 => '0');
    end if;
  end process;
  process (wr_sel_d0) begin
    wrpc_device_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      wrpc_device_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      wrpc_device_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      wrpc_device_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      wrpc_device_o.sel(3) <= '1';
    end if;
  end process;
  wrpc_device_o.we <= wrpc_device_wt;
  wrpc_device_o.dat <= wr_dat_d0;

  -- Interface wrpc_aux
  wrpc_aux_tr <= wrpc_aux_wt or wrpc_aux_rt;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        wrpc_aux_rt <= '0';
        wrpc_aux_wt <= '0';
        wrpc_aux_wr <= '0';
        wrpc_aux_rr <= '0';
      else
        wrpc_aux_wr <= (wrpc_aux_wr or wrpc_aux_we) and not wrpc_aux_wack;
        wrpc_aux_wt <= (wrpc_aux_wt or (wrpc_aux_wr and not wrpc_aux_tr)) and not wrpc_aux_wack;
        wrpc_aux_rr <= (wrpc_aux_rr or wrpc_aux_re) and not wrpc_aux_rack;
        wrpc_aux_rt <= (wrpc_aux_rt or (wrpc_aux_rr and not (wrpc_aux_wr or wrpc_aux_tr))) and not wrpc_aux_rack;
      end if;
    end if;
  end process;
  wrpc_aux_o.cyc <= wrpc_aux_tr;
  wrpc_aux_o.stb <= wrpc_aux_tr;
  wrpc_aux_wack <= wrpc_aux_i.ack and wrpc_aux_wt;
  wrpc_aux_rack <= wrpc_aux_i.ack and wrpc_aux_rt;
  process (rd_addr, wr_adr_d0, wrpc_aux_wt) begin
    if wrpc_aux_wt = '1' then
      wrpc_aux_o.adr <= ((19 downto 0 => '0') & wr_adr_d0(11 downto 2)) & (1 downto 0 => '0');
    else
      wrpc_aux_o.adr <= ((19 downto 0 => '0') & rd_addr(11 downto 2)) & (1 downto 0 => '0');
    end if;
  end process;
  process (wr_sel_d0) begin
    wrpc_aux_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      wrpc_aux_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      wrpc_aux_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      wrpc_aux_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      wrpc_aux_o.sel(3) <= '1';
    end if;
  end process;
  wrpc_aux_o.we <= wrpc_aux_wt;
  wrpc_aux_o.dat <= wr_dat_d0;

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0, wrpc_host_wack, ctrl_wack, qpll0_sdm_wack,
           qpll1_sdm_wack, rxpi_nsamp_wack, bitslide_wack, wrpc_device_wack,
           wrpc_aux_wack) begin
    wrpc_host_we <= '0';
    ctrl_wreq <= '0';
    qpll0_sdm_wreq <= '0';
    qpll1_sdm_wreq <= '0';
    rxpi_nsamp_wreq <= '0';
    bitslide_wreq <= '0';
    wrpc_device_we <= '0';
    wrpc_aux_we <= '0';
    case wr_adr_d0(14 downto 12) is
    when "000" =>
      -- Submap wrpc_host
      wrpc_host_we <= wr_req_d0;
      wr_ack <= wrpc_host_wack;
    when "001" =>
      case wr_adr_d0(11 downto 2) is
      when "0000000000" =>
        -- Reg ctrl
        ctrl_wreq <= wr_req_d0;
        wr_ack <= ctrl_wack;
      when "0000000001" =>
        -- Reg status
        wr_ack <= wr_req_d0;
      when "0000000010" =>
        -- Reg qpll0_sdm
        qpll0_sdm_wreq <= wr_req_d0;
        wr_ack <= qpll0_sdm_wack;
      when "0000000011" =>
        -- Reg qpll1_sdm
        qpll1_sdm_wreq <= wr_req_d0;
        wr_ack <= qpll1_sdm_wack;
      when "0000000100" =>
        -- Reg rxpi_nsamp
        rxpi_nsamp_wreq <= wr_req_d0;
        wr_ack <= rxpi_nsamp_wack;
      when "0000000101" =>
        -- Reg rxpi_count
        wr_ack <= wr_req_d0;
      when "0000000110" =>
        -- Reg rxpi_tag
        wr_ack <= wr_req_d0;
      when "0000000111" =>
        -- Reg rxpi_direct
        wr_ack <= wr_req_d0;
      when "0000001000" =>
        -- Reg bitslide
        bitslide_wreq <= wr_req_d0;
        wr_ack <= bitslide_wack;
      when "0000001001" =>
        -- Reg nbr_comma_det
        wr_ack <= wr_req_d0;
      when "0000001010" =>
        -- Reg nbr_byte_align
        wr_ack <= wr_req_d0;
      when others =>
        wr_ack <= wr_req_d0;
      end case;
    when "011" =>
      -- Submap wrpc_device
      wrpc_device_we <= wr_req_d0;
      wr_ack <= wrpc_device_wack;
    when "100" =>
      -- Submap wrpc_aux
      wrpc_aux_we <= wr_req_d0;
      wr_ack <= wrpc_aux_wack;
    when others =>
      wr_ack <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (rd_addr, rd_req, wrpc_host_i.dat, wrpc_host_rack, ctrl_led1_reg,
           ctrl_led2_reg, ctrl_gth_rst_reg, ctrl_gth_tx_rst_reg,
           ctrl_gth_tx_pcs_rst_reg, ctrl_gth_tx_pma_rst_reg,
           ctrl_gth_rx_rst_reg, ctrl_gth_rx_pcs_rst_reg,
           ctrl_gth_rx_pma_rst_reg, ctrl_gth_rx_buf_rst_reg, status_i,
           qpll0_sdm_reg, qpll1_sdm_reg, rxpi_nsamp_reg, rxpi_count_i, rxpi_tag_i,
           rxpi_direct_i, bitslide_force_reg, bitslide_slide_i, bitslide_value_i,
           nbr_comma_det_i, nbr_byte_align_i, wrpc_device_i.dat,
           wrpc_device_rack, wrpc_aux_i.dat, wrpc_aux_rack) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    wrpc_host_re <= '0';
    wrpc_device_re <= '0';
    wrpc_aux_re <= '0';
    case rd_addr(14 downto 12) is
    when "000" =>
      -- Submap wrpc_host
      wrpc_host_re <= rd_req;
      rd_dat_d0 <= wrpc_host_i.dat;
      rd_ack_d0 <= wrpc_host_rack;
    when "001" =>
      case rd_addr(11 downto 2) is
      when "0000000000" =>
        -- Reg ctrl
        rd_ack_d0 <= rd_req;
        rd_dat_d0(0) <= ctrl_led1_reg;
        rd_dat_d0(1) <= ctrl_led2_reg;
        rd_dat_d0(2) <= ctrl_gth_rst_reg;
        rd_dat_d0(3) <= '0';
        rd_dat_d0(4) <= ctrl_gth_tx_rst_reg;
        rd_dat_d0(5) <= ctrl_gth_tx_pcs_rst_reg;
        rd_dat_d0(6) <= ctrl_gth_tx_pma_rst_reg;
        rd_dat_d0(7) <= '0';
        rd_dat_d0(8) <= ctrl_gth_rx_rst_reg;
        rd_dat_d0(9) <= ctrl_gth_rx_pcs_rst_reg;
        rd_dat_d0(10) <= ctrl_gth_rx_pma_rst_reg;
        rd_dat_d0(11) <= ctrl_gth_rx_buf_rst_reg;
        rd_dat_d0(31 downto 12) <= (others => '0');
      when "0000000001" =>
        -- Reg status
        rd_ack_d0 <= rd_req;
        rd_dat_d0 <= status_i;
      when "0000000010" =>
        -- Reg qpll0_sdm
        rd_ack_d0 <= rd_req;
        rd_dat_d0 <= qpll0_sdm_reg;
      when "0000000011" =>
        -- Reg qpll1_sdm
        rd_ack_d0 <= rd_req;
        rd_dat_d0 <= qpll1_sdm_reg;
      when "0000000100" =>
        -- Reg rxpi_nsamp
        rd_ack_d0 <= rd_req;
        rd_dat_d0 <= rxpi_nsamp_reg;
      when "0000000101" =>
        -- Reg rxpi_count
        rd_ack_d0 <= rd_req;
        rd_dat_d0 <= rxpi_count_i;
      when "0000000110" =>
        -- Reg rxpi_tag
        rd_ack_d0 <= rd_req;
        rd_dat_d0 <= rxpi_tag_i;
      when "0000000111" =>
        -- Reg rxpi_direct
        rd_ack_d0 <= rd_req;
        rd_dat_d0 <= rxpi_direct_i;
      when "0000001000" =>
        -- Reg bitslide
        rd_ack_d0 <= rd_req;
        rd_dat_d0(0) <= bitslide_force_reg;
        rd_dat_d0(1) <= bitslide_slide_i;
        rd_dat_d0(7 downto 2) <= (others => '0');
        rd_dat_d0(12 downto 8) <= bitslide_value_i;
        rd_dat_d0(31 downto 13) <= (others => '0');
      when "0000001001" =>
        -- Reg nbr_comma_det
        rd_ack_d0 <= rd_req;
        rd_dat_d0 <= nbr_comma_det_i;
      when "0000001010" =>
        -- Reg nbr_byte_align
        rd_ack_d0 <= rd_req;
        rd_dat_d0 <= nbr_byte_align_i;
      when others =>
        rd_ack_d0 <= rd_req;
      end case;
    when "011" =>
      -- Submap wrpc_device
      wrpc_device_re <= rd_req;
      rd_dat_d0 <= wrpc_device_i.dat;
      rd_ack_d0 <= wrpc_device_rack;
    when "100" =>
      -- Submap wrpc_aux
      wrpc_aux_re <= rd_req;
      rd_dat_d0 <= wrpc_aux_i.dat;
      rd_ack_d0 <= wrpc_aux_rack;
    when others =>
      rd_ack_d0 <= rd_req;
    end case;
  end process;
end syn;
