-- Do not edit.  Generated by cheby 1.6.0rc1 using these options:
--  --gen-hdl mpsoc_map.vhd --gen-c mpsoc_map.h -i mpsoc_map.cheby
-- Generated on Mon Jul 29 16:04:31 2024 by tgingold


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity mpsoc_map is
  port (
    aclk                 : in    std_logic;
    areset_n             : in    std_logic;
    awvalid              : in    std_logic;
    awready              : out   std_logic;
    awprot               : in    std_logic_vector(2 downto 0);
    wvalid               : in    std_logic;
    wready               : out   std_logic;
    wdata                : in    std_logic_vector(31 downto 0);
    wstrb                : in    std_logic_vector(3 downto 0);
    bvalid               : out   std_logic;
    bready               : in    std_logic;
    bresp                : out   std_logic_vector(1 downto 0);
    arvalid              : in    std_logic;
    arready              : out   std_logic;
    arprot               : in    std_logic_vector(2 downto 0);
    rvalid               : out   std_logic;
    rready               : in    std_logic;
    rdata                : out   std_logic_vector(31 downto 0);
    rresp                : out   std_logic_vector(1 downto 0);

    -- control register
    ctrl_led1_o          : out   std_logic;
    ctrl_led2_o          : out   std_logic;
    ctrl_gth_rst_o       : out   std_logic
  );
end mpsoc_map;

architecture syn of mpsoc_map is
  signal wr_req                         : std_logic;
  signal wr_ack                         : std_logic;
  signal wr_data                        : std_logic_vector(31 downto 0);
  signal axi_awset                      : std_logic;
  signal axi_wset                       : std_logic;
  signal axi_wdone                      : std_logic;
  signal rd_req                         : std_logic;
  signal rd_ack                         : std_logic;
  signal rd_data                        : std_logic_vector(31 downto 0);
  signal axi_arset                      : std_logic;
  signal axi_rdone                      : std_logic;
  signal ctrl_led1_reg                  : std_logic;
  signal ctrl_led2_reg                  : std_logic;
  signal ctrl_gth_rst_reg               : std_logic;
  signal ctrl_wreq                      : std_logic;
  signal ctrl_wack                      : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
begin

  -- AW, W and B channels
  awready <= not axi_awset;
  wready <= not axi_wset;
  bvalid <= axi_wdone;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        wr_req <= '0';
        axi_awset <= '0';
        axi_wset <= '0';
        axi_wdone <= '0';
      else
        wr_req <= '0';
        if awvalid = '1' and axi_awset = '0' then
          axi_awset <= '1';
          wr_req <= axi_wset;
        end if;
        if wvalid = '1' and axi_wset = '0' then
          wr_data <= wdata;
          axi_wset <= '1';
          wr_req <= axi_awset or awvalid;
        end if;
        if (axi_wdone and bready) = '1' then
          axi_wset <= '0';
          axi_awset <= '0';
          axi_wdone <= '0';
        end if;
        if wr_ack = '1' then
          axi_wdone <= '1';
        end if;
      end if;
    end if;
  end process;
  bresp <= "00";

  -- AR and R channels
  arready <= not axi_arset;
  rvalid <= axi_rdone;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        rd_req <= '0';
        axi_arset <= '0';
        axi_rdone <= '0';
        rdata <= (others => '0');
      else
        rd_req <= '0';
        if arvalid = '1' and axi_arset = '0' then
          axi_arset <= '1';
          rd_req <= '1';
        end if;
        if (axi_rdone and rready) = '1' then
          axi_arset <= '0';
          axi_rdone <= '0';
        end if;
        if rd_ack = '1' then
          axi_rdone <= '1';
          rdata <= rd_data;
        end if;
      end if;
    end if;
  end process;
  rresp <= "00";

  -- pipelining for wr-in+rd-out
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        rd_ack <= '0';
        rd_data <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_dat_d0 <= "00000000000000000000000000000000";
      else
        rd_ack <= rd_ack_d0;
        rd_data <= rd_dat_d0;
        wr_req_d0 <= wr_req;
        wr_dat_d0 <= wr_data;
      end if;
    end if;
  end process;

  -- Register ctrl
  ctrl_led1_o <= ctrl_led1_reg;
  ctrl_led2_o <= ctrl_led2_reg;
  ctrl_gth_rst_o <= ctrl_gth_rst_reg;
  ctrl_wack <= ctrl_wreq;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        ctrl_led1_reg <= '0';
        ctrl_led2_reg <= '0';
        ctrl_gth_rst_reg <= '0';
      else
        if ctrl_wreq = '1' then
          ctrl_led1_reg <= wr_dat_d0(0);
          ctrl_led2_reg <= wr_dat_d0(1);
          ctrl_gth_rst_reg <= wr_dat_d0(2);
        end if;
      end if;
    end if;
  end process;

  -- Process for write requests.
  process (wr_req_d0, ctrl_wack) begin
    ctrl_wreq <= '0';
    -- Reg ctrl
    ctrl_wreq <= wr_req_d0;
    wr_ack <= ctrl_wack;
  end process;

  -- Process for read requests.
  process (rd_req, ctrl_led1_reg, ctrl_led2_reg, ctrl_gth_rst_reg) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    -- Reg ctrl
    rd_ack_d0 <= rd_req;
    rd_dat_d0(0) <= ctrl_led1_reg;
    rd_dat_d0(1) <= ctrl_led2_reg;
    rd_dat_d0(2) <= ctrl_gth_rst_reg;
    rd_dat_d0(31 downto 3) <= (others => '0');
  end process;
end syn;
