-- Do not edit.  Generated by cheby 1.7.dev0 using these options:
--  --gen-hdl mpsoc_map.vhd --gen-c mpsoc_map.h -i mpsoc_map.cheby
-- Generated on Wed Jun 18 08:44:52 2025 by tgingold


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;

entity mpsoc_map is
  port (
    aclk                 : in    std_logic;
    areset_n             : in    std_logic;
    awvalid              : in    std_logic;
    awready              : out   std_logic;
    awaddr               : in    std_logic_vector(12 downto 2);
    awprot               : in    std_logic_vector(2 downto 0);
    wvalid               : in    std_logic;
    wready               : out   std_logic;
    wdata                : in    std_logic_vector(31 downto 0);
    wstrb                : in    std_logic_vector(3 downto 0);
    bvalid               : out   std_logic;
    bready               : in    std_logic;
    bresp                : out   std_logic_vector(1 downto 0);
    arvalid              : in    std_logic;
    arready              : out   std_logic;
    araddr               : in    std_logic_vector(12 downto 2);
    arprot               : in    std_logic_vector(2 downto 0);
    rvalid               : out   std_logic;
    rready               : in    std_logic;
    rdata                : out   std_logic_vector(31 downto 0);
    rresp                : out   std_logic_vector(1 downto 0);

    -- WB bus wrpc
    wrpc_i               : in    t_wishbone_master_in;
    wrpc_o               : out   t_wishbone_master_out;

    -- control register
    ctrl_led1_o          : out   std_logic;
    ctrl_led2_o          : out   std_logic;
    ctrl_gth_rst_o       : out   std_logic;

    -- REG status
    status_i             : in    std_logic_vector(31 downto 0);

    -- REG qpll0_sdm
    qpll0_sdm_o          : out   std_logic_vector(31 downto 0);
    qpll0_sdm_wr_o       : out   std_logic;

    -- REG qpll1_sdm
    qpll1_sdm_o          : out   std_logic_vector(31 downto 0);
    qpll1_sdm_wr_o       : out   std_logic;

    -- number of rxpi samples to accumulate
    rxpi_samp_o          : out   std_logic_vector(31 downto 0);

    -- REG fifo_ctrl
    fifo_ctrl_en_o       : out   std_logic;

    -- REG fifo_rdcount
    fifo_rdcount_i       : in    std_logic_vector(31 downto 0);

    -- number of samples discarded because fifo was full, write to clear
    fifo_nfull_i         : in    std_logic_vector(31 downto 0);
    fifo_nfull_o         : out   std_logic_vector(31 downto 0);
    fifo_nfull_wr_o      : out   std_logic;

    -- REG fifo_data
    fifo_data_i          : in    std_logic_vector(31 downto 0);
    fifo_data_rd_o       : out   std_logic
  );
end mpsoc_map;

architecture syn of mpsoc_map is
  signal wr_req                         : std_logic;
  signal wr_ack                         : std_logic;
  signal wr_addr                        : std_logic_vector(12 downto 2);
  signal wr_data                        : std_logic_vector(31 downto 0);
  signal wr_sel                         : std_logic_vector(31 downto 0);
  signal axi_awset                      : std_logic;
  signal axi_wset                       : std_logic;
  signal axi_wdone                      : std_logic;
  signal rd_req                         : std_logic;
  signal rd_ack                         : std_logic;
  signal rd_addr                        : std_logic_vector(12 downto 2);
  signal rd_data                        : std_logic_vector(31 downto 0);
  signal axi_arset                      : std_logic;
  signal axi_rdone                      : std_logic;
  signal wrpc_re                        : std_logic;
  signal wrpc_we                        : std_logic;
  signal wrpc_wt                        : std_logic;
  signal wrpc_rt                        : std_logic;
  signal wrpc_tr                        : std_logic;
  signal wrpc_wack                      : std_logic;
  signal wrpc_rack                      : std_logic;
  signal wrpc_wr                        : std_logic;
  signal wrpc_rr                        : std_logic;
  signal ctrl_led1_reg                  : std_logic;
  signal ctrl_led2_reg                  : std_logic;
  signal ctrl_gth_rst_reg               : std_logic;
  signal ctrl_wreq                      : std_logic;
  signal ctrl_wack                      : std_logic;
  signal qpll0_sdm_reg                  : std_logic_vector(31 downto 0);
  signal qpll0_sdm_wreq                 : std_logic;
  signal qpll0_sdm_wack                 : std_logic;
  signal qpll0_sdm_wstrb                : std_logic;
  signal qpll1_sdm_reg                  : std_logic_vector(31 downto 0);
  signal qpll1_sdm_wreq                 : std_logic;
  signal qpll1_sdm_wack                 : std_logic;
  signal qpll1_sdm_wstrb                : std_logic;
  signal rxpi_samp_reg                  : std_logic_vector(31 downto 0);
  signal rxpi_samp_wreq                 : std_logic;
  signal rxpi_samp_wack                 : std_logic;
  signal fifo_ctrl_en_reg               : std_logic;
  signal fifo_ctrl_wreq                 : std_logic;
  signal fifo_ctrl_wack                 : std_logic;
  signal fifo_nfull_wreq                : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(12 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_sel_d0                      : std_logic_vector(31 downto 0);
begin

  -- AW, W and B channels
  awready <= not axi_awset;
  wready <= not axi_wset;
  bvalid <= axi_wdone;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        wr_req <= '0';
        axi_awset <= '0';
        axi_wset <= '0';
        axi_wdone <= '0';
      else
        wr_req <= '0';
        if awvalid = '1' and axi_awset = '0' then
          wr_addr <= awaddr;
          axi_awset <= '1';
          wr_req <= axi_wset;
        end if;
        if wvalid = '1' and axi_wset = '0' then
          wr_data <= wdata;
          wr_sel(7 downto 0) <= (others => wstrb(0));
          wr_sel(15 downto 8) <= (others => wstrb(1));
          wr_sel(23 downto 16) <= (others => wstrb(2));
          wr_sel(31 downto 24) <= (others => wstrb(3));
          axi_wset <= '1';
          wr_req <= axi_awset or awvalid;
        end if;
        if (axi_wdone and bready) = '1' then
          axi_wset <= '0';
          axi_awset <= '0';
          axi_wdone <= '0';
        end if;
        if wr_ack = '1' then
          axi_wdone <= '1';
        end if;
      end if;
    end if;
  end process;
  bresp <= "00";

  -- AR and R channels
  arready <= not axi_arset;
  rvalid <= axi_rdone;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        rd_req <= '0';
        axi_arset <= '0';
        axi_rdone <= '0';
        rdata <= (others => '0');
      else
        rd_req <= '0';
        if arvalid = '1' and axi_arset = '0' then
          rd_addr <= araddr;
          axi_arset <= '1';
          rd_req <= '1';
        end if;
        if (axi_rdone and rready) = '1' then
          axi_arset <= '0';
          axi_rdone <= '0';
        end if;
        if rd_ack = '1' then
          axi_rdone <= '1';
          rdata <= rd_data;
        end if;
      end if;
    end if;
  end process;
  rresp <= "00";

  -- pipelining for wr-in+rd-out
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        rd_ack <= '0';
        rd_data <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_adr_d0 <= "00000000000";
        wr_dat_d0 <= "00000000000000000000000000000000";
        wr_sel_d0 <= "00000000000000000000000000000000";
      else
        rd_ack <= rd_ack_d0;
        rd_data <= rd_dat_d0;
        wr_req_d0 <= wr_req;
        wr_adr_d0 <= wr_addr;
        wr_dat_d0 <= wr_data;
        wr_sel_d0 <= wr_sel;
      end if;
    end if;
  end process;

  -- Interface wrpc
  wrpc_tr <= wrpc_wt or wrpc_rt;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        wrpc_rt <= '0';
        wrpc_wt <= '0';
        wrpc_wr <= '0';
        wrpc_rr <= '0';
      else
        wrpc_wr <= (wrpc_wr or wrpc_we) and not wrpc_wack;
        wrpc_wt <= (wrpc_wt or (wrpc_wr and not wrpc_tr)) and not wrpc_wack;
        wrpc_rr <= (wrpc_rr or wrpc_re) and not wrpc_rack;
        wrpc_rt <= (wrpc_rt or (wrpc_rr and not (wrpc_wr or wrpc_tr))) and not wrpc_rack;
      end if;
    end if;
  end process;
  wrpc_o.cyc <= wrpc_tr;
  wrpc_o.stb <= wrpc_tr;
  wrpc_wack <= wrpc_i.ack and wrpc_wt;
  wrpc_rack <= wrpc_i.ack and wrpc_rt;
  process (rd_addr, wr_adr_d0, wrpc_wt) begin
    if wrpc_wt = '1' then
      wrpc_o.adr <= ((19 downto 0 => '0') & wr_adr_d0(11 downto 2)) & (1 downto 0 => '0');
    else
      wrpc_o.adr <= ((19 downto 0 => '0') & rd_addr(11 downto 2)) & (1 downto 0 => '0');
    end if;
  end process;
  process (wr_sel_d0) begin
    wrpc_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      wrpc_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      wrpc_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      wrpc_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      wrpc_o.sel(3) <= '1';
    end if;
  end process;
  wrpc_o.we <= wrpc_wt;
  wrpc_o.dat <= wr_dat_d0;

  -- Register ctrl
  ctrl_led1_o <= ctrl_led1_reg;
  ctrl_led2_o <= ctrl_led2_reg;
  ctrl_gth_rst_o <= ctrl_gth_rst_reg;
  ctrl_wack <= ctrl_wreq;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        ctrl_led1_reg <= '0';
        ctrl_led2_reg <= '0';
        ctrl_gth_rst_reg <= '0';
      else
        if ctrl_wreq = '1' then
          ctrl_led1_reg <= wr_dat_d0(0);
          ctrl_led2_reg <= wr_dat_d0(1);
          ctrl_gth_rst_reg <= wr_dat_d0(2);
        end if;
      end if;
    end if;
  end process;

  -- Register status

  -- Register qpll0_sdm
  qpll0_sdm_o <= qpll0_sdm_reg;
  qpll0_sdm_wack <= qpll0_sdm_wreq;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        qpll0_sdm_reg <= "00000000000000000000000000000000";
        qpll0_sdm_wstrb <= '0';
      else
        if qpll0_sdm_wreq = '1' then
          qpll0_sdm_reg <= wr_dat_d0;
        end if;
        qpll0_sdm_wstrb <= qpll0_sdm_wreq;
      end if;
    end if;
  end process;
  qpll0_sdm_wr_o <= qpll0_sdm_wstrb;

  -- Register qpll1_sdm
  qpll1_sdm_o <= qpll1_sdm_reg;
  qpll1_sdm_wack <= qpll1_sdm_wreq;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        qpll1_sdm_reg <= "00000000000000000000000000000000";
        qpll1_sdm_wstrb <= '0';
      else
        if qpll1_sdm_wreq = '1' then
          qpll1_sdm_reg <= wr_dat_d0;
        end if;
        qpll1_sdm_wstrb <= qpll1_sdm_wreq;
      end if;
    end if;
  end process;
  qpll1_sdm_wr_o <= qpll1_sdm_wstrb;

  -- Register rxpi_samp
  rxpi_samp_o <= rxpi_samp_reg;
  rxpi_samp_wack <= rxpi_samp_wreq;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        rxpi_samp_reg <= "00000000000000000100000000000000";
      else
        if rxpi_samp_wreq = '1' then
          rxpi_samp_reg <= wr_dat_d0;
        end if;
      end if;
    end if;
  end process;

  -- Register fifo_ctrl
  fifo_ctrl_en_o <= fifo_ctrl_en_reg;
  fifo_ctrl_wack <= fifo_ctrl_wreq;
  process (aclk) begin
    if rising_edge(aclk) then
      if areset_n = '0' then
        fifo_ctrl_en_reg <= '0';
      else
        if fifo_ctrl_wreq = '1' then
          fifo_ctrl_en_reg <= wr_dat_d0(0);
        end if;
      end if;
    end if;
  end process;

  -- Register fifo_rdcount

  -- Register fifo_nfull
  fifo_nfull_o <= wr_dat_d0;
  fifo_nfull_wr_o <= fifo_nfull_wreq;

  -- Register fifo_data

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0, wrpc_wack, ctrl_wack, qpll0_sdm_wack,
           qpll1_sdm_wack, rxpi_samp_wack, fifo_ctrl_wack) begin
    wrpc_we <= '0';
    ctrl_wreq <= '0';
    qpll0_sdm_wreq <= '0';
    qpll1_sdm_wreq <= '0';
    rxpi_samp_wreq <= '0';
    fifo_ctrl_wreq <= '0';
    fifo_nfull_wreq <= '0';
    case wr_adr_d0(12 downto 12) is
    when "0" =>
      -- Submap wrpc
      wrpc_we <= wr_req_d0;
      wr_ack <= wrpc_wack;
    when "1" =>
      case wr_adr_d0(11 downto 2) is
      when "0000000000" =>
        -- Reg ctrl
        ctrl_wreq <= wr_req_d0;
        wr_ack <= ctrl_wack;
      when "0000000001" =>
        -- Reg status
        wr_ack <= wr_req_d0;
      when "0000000010" =>
        -- Reg qpll0_sdm
        qpll0_sdm_wreq <= wr_req_d0;
        wr_ack <= qpll0_sdm_wack;
      when "0000000011" =>
        -- Reg qpll1_sdm
        qpll1_sdm_wreq <= wr_req_d0;
        wr_ack <= qpll1_sdm_wack;
      when "0000000100" =>
        -- Reg rxpi_samp
        rxpi_samp_wreq <= wr_req_d0;
        wr_ack <= rxpi_samp_wack;
      when "0000000101" =>
        -- Reg fifo_ctrl
        fifo_ctrl_wreq <= wr_req_d0;
        wr_ack <= fifo_ctrl_wack;
      when "0000000110" =>
        -- Reg fifo_rdcount
        wr_ack <= wr_req_d0;
      when "0000000111" =>
        -- Reg fifo_nfull
        fifo_nfull_wreq <= wr_req_d0;
        wr_ack <= wr_req_d0;
      when "0000001000" =>
        -- Reg fifo_data
        wr_ack <= wr_req_d0;
      when others =>
        wr_ack <= wr_req_d0;
      end case;
    when others =>
      wr_ack <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (rd_addr, rd_req, wrpc_i.dat, wrpc_rack, ctrl_led1_reg, ctrl_led2_reg,
           ctrl_gth_rst_reg, status_i, qpll0_sdm_reg, qpll1_sdm_reg, rxpi_samp_reg,
           fifo_ctrl_en_reg, fifo_rdcount_i, fifo_nfull_i, fifo_data_i) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    wrpc_re <= '0';
    fifo_data_rd_o <= '0';
    case rd_addr(12 downto 12) is
    when "0" =>
      -- Submap wrpc
      wrpc_re <= rd_req;
      rd_dat_d0 <= wrpc_i.dat;
      rd_ack_d0 <= wrpc_rack;
    when "1" =>
      case rd_addr(11 downto 2) is
      when "0000000000" =>
        -- Reg ctrl
        rd_ack_d0 <= rd_req;
        rd_dat_d0(0) <= ctrl_led1_reg;
        rd_dat_d0(1) <= ctrl_led2_reg;
        rd_dat_d0(2) <= ctrl_gth_rst_reg;
        rd_dat_d0(31 downto 3) <= (others => '0');
      when "0000000001" =>
        -- Reg status
        rd_ack_d0 <= rd_req;
        rd_dat_d0 <= status_i;
      when "0000000010" =>
        -- Reg qpll0_sdm
        rd_ack_d0 <= rd_req;
        rd_dat_d0 <= qpll0_sdm_reg;
      when "0000000011" =>
        -- Reg qpll1_sdm
        rd_ack_d0 <= rd_req;
        rd_dat_d0 <= qpll1_sdm_reg;
      when "0000000100" =>
        -- Reg rxpi_samp
        rd_ack_d0 <= rd_req;
        rd_dat_d0 <= rxpi_samp_reg;
      when "0000000101" =>
        -- Reg fifo_ctrl
        rd_ack_d0 <= rd_req;
        rd_dat_d0(0) <= fifo_ctrl_en_reg;
        rd_dat_d0(31 downto 1) <= (others => '0');
      when "0000000110" =>
        -- Reg fifo_rdcount
        rd_ack_d0 <= rd_req;
        rd_dat_d0 <= fifo_rdcount_i;
      when "0000000111" =>
        -- Reg fifo_nfull
        rd_ack_d0 <= rd_req;
        rd_dat_d0 <= fifo_nfull_i;
      when "0000001000" =>
        -- Reg fifo_data
        fifo_data_rd_o <= rd_req;
        rd_ack_d0 <= rd_req;
        rd_dat_d0 <= fifo_data_i;
      when others =>
        rd_ack_d0 <= rd_req;
      end case;
    when others =>
      rd_ack_d0 <= rd_req;
    end case;
  end process;
end syn;
