-- Do not edit.  Generated by cheby 1.7.dev0 using these options:
--  --gen-hdl rxpi_gthe4_map.vhd --gen-c rxpi_gthe4_map.h -i rxpi_gthe4_map.cheby
-- Generated on Mon Jun 30 09:47:49 2025 by tgingold


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;

entity rxpi_gthe4_map is
  port (
    rst_n_i              : in    std_logic;
    clk_i                : in    std_logic;
    wb_i                 : in    t_wishbone_slave_in;
    wb_o                 : out   t_wishbone_slave_out;

    -- Reset register
    reset_gth_rst_o      : out   std_logic;
    reset_gth_tx_rst_o   : out   std_logic;
    reset_gth_tx_pcs_rst_o : out   std_logic;
    reset_gth_tx_pma_rst_o : out   std_logic;
    reset_gth_rx_rst_o   : out   std_logic;
    reset_gth_rx_pcs_rst_o : out   std_logic;
    reset_gth_rx_pma_rst_o : out   std_logic;
    reset_gth_rx_buf_rst_o : out   std_logic;

    -- REG status
    status_i             : in    std_logic_vector(31 downto 0);

    -- REG ctrl
    -- Transceiver is fully ready
    ctrl_rdy_o           : out   std_logic;

    -- Bitslide
    bitslide_i           : in    std_logic_vector(31 downto 0)
  );
end rxpi_gthe4_map;

architecture syn of rxpi_gthe4_map is
  signal adr_int                        : std_logic_vector(4 downto 2);
  signal rd_req_int                     : std_logic;
  signal wr_req_int                     : std_logic;
  signal rd_ack_int                     : std_logic;
  signal wr_ack_int                     : std_logic;
  signal wb_en                          : std_logic;
  signal ack_int                        : std_logic;
  signal wb_rip                         : std_logic;
  signal wb_wip                         : std_logic;
  signal reset_gth_rst_reg              : std_logic;
  signal reset_gth_tx_rst_reg           : std_logic;
  signal reset_gth_tx_pcs_rst_reg       : std_logic;
  signal reset_gth_tx_pma_rst_reg       : std_logic;
  signal reset_gth_rx_rst_reg           : std_logic;
  signal reset_gth_rx_pcs_rst_reg       : std_logic;
  signal reset_gth_rx_pma_rst_reg       : std_logic;
  signal reset_gth_rx_buf_rst_reg       : std_logic;
  signal reset_wreq                     : std_logic;
  signal reset_wack                     : std_logic;
  signal ctrl_rdy_reg                   : std_logic;
  signal ctrl_wreq                      : std_logic;
  signal ctrl_wack                      : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(4 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
begin

  -- WB decode signals
  adr_int <= wb_i.adr(4 downto 2);
  wb_en <= wb_i.cyc and wb_i.stb;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_rip <= '0';
      else
        wb_rip <= (wb_rip or (wb_en and not wb_i.we)) and not rd_ack_int;
      end if;
    end if;
  end process;
  rd_req_int <= (wb_en and not wb_i.we) and not wb_rip;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_wip <= '0';
      else
        wb_wip <= (wb_wip or (wb_en and wb_i.we)) and not wr_ack_int;
      end if;
    end if;
  end process;
  wr_req_int <= (wb_en and wb_i.we) and not wb_wip;

  ack_int <= rd_ack_int or wr_ack_int;
  wb_o.ack <= ack_int;
  wb_o.stall <= not ack_int and wb_en;
  wb_o.rty <= '0';
  wb_o.err <= '0';

  -- pipelining for wr-in+rd-out
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        rd_ack_int <= '0';
        wb_o.dat <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_adr_d0 <= "000";
        wr_dat_d0 <= "00000000000000000000000000000000";
      else
        rd_ack_int <= rd_ack_d0;
        wb_o.dat <= rd_dat_d0;
        wr_req_d0 <= wr_req_int;
        wr_adr_d0 <= adr_int;
        wr_dat_d0 <= wb_i.dat;
      end if;
    end if;
  end process;

  -- Register id

  -- Register reset
  reset_gth_rst_o <= reset_gth_rst_reg;
  reset_gth_tx_rst_o <= reset_gth_tx_rst_reg;
  reset_gth_tx_pcs_rst_o <= reset_gth_tx_pcs_rst_reg;
  reset_gth_tx_pma_rst_o <= reset_gth_tx_pma_rst_reg;
  reset_gth_rx_rst_o <= reset_gth_rx_rst_reg;
  reset_gth_rx_pcs_rst_o <= reset_gth_rx_pcs_rst_reg;
  reset_gth_rx_pma_rst_o <= reset_gth_rx_pma_rst_reg;
  reset_gth_rx_buf_rst_o <= reset_gth_rx_buf_rst_reg;
  reset_wack <= reset_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        reset_gth_rst_reg <= '0';
        reset_gth_tx_rst_reg <= '0';
        reset_gth_tx_pcs_rst_reg <= '0';
        reset_gth_tx_pma_rst_reg <= '0';
        reset_gth_rx_rst_reg <= '0';
        reset_gth_rx_pcs_rst_reg <= '0';
        reset_gth_rx_pma_rst_reg <= '0';
        reset_gth_rx_buf_rst_reg <= '0';
      else
        if reset_wreq = '1' then
          reset_gth_rst_reg <= wr_dat_d0(0);
          reset_gth_tx_rst_reg <= wr_dat_d0(4);
          reset_gth_tx_pcs_rst_reg <= wr_dat_d0(5);
          reset_gth_tx_pma_rst_reg <= wr_dat_d0(6);
          reset_gth_rx_rst_reg <= wr_dat_d0(8);
          reset_gth_rx_pcs_rst_reg <= wr_dat_d0(9);
          reset_gth_rx_pma_rst_reg <= wr_dat_d0(10);
          reset_gth_rx_buf_rst_reg <= wr_dat_d0(11);
        end if;
      end if;
    end if;
  end process;

  -- Register status

  -- Register ctrl
  ctrl_rdy_o <= ctrl_rdy_reg;
  ctrl_wack <= ctrl_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        ctrl_rdy_reg <= '0';
      else
        if ctrl_wreq = '1' then
          ctrl_rdy_reg <= wr_dat_d0(0);
        end if;
      end if;
    end if;
  end process;

  -- Register bitslide

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0, reset_wack, ctrl_wack) begin
    reset_wreq <= '0';
    ctrl_wreq <= '0';
    case wr_adr_d0(4 downto 2) is
    when "000" =>
      -- Reg id
      wr_ack_int <= wr_req_d0;
    when "001" =>
      -- Reg reset
      reset_wreq <= wr_req_d0;
      wr_ack_int <= reset_wack;
    when "010" =>
      -- Reg status
      wr_ack_int <= wr_req_d0;
    when "011" =>
      -- Reg ctrl
      ctrl_wreq <= wr_req_d0;
      wr_ack_int <= ctrl_wack;
    when "100" =>
      -- Reg bitslide
      wr_ack_int <= wr_req_d0;
    when others =>
      wr_ack_int <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (adr_int, rd_req_int, reset_gth_rst_reg, reset_gth_tx_rst_reg,
           reset_gth_tx_pcs_rst_reg, reset_gth_tx_pma_rst_reg,
           reset_gth_rx_rst_reg, reset_gth_rx_pcs_rst_reg,
           reset_gth_rx_pma_rst_reg, reset_gth_rx_buf_rst_reg, status_i,
           ctrl_rdy_reg, bitslide_i) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    case adr_int(4 downto 2) is
    when "000" =>
      -- Reg id
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= "00000000000001100001100011100100";
    when "001" =>
      -- Reg reset
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(0) <= reset_gth_rst_reg;
      rd_dat_d0(3 downto 1) <= (others => '0');
      rd_dat_d0(4) <= reset_gth_tx_rst_reg;
      rd_dat_d0(5) <= reset_gth_tx_pcs_rst_reg;
      rd_dat_d0(6) <= reset_gth_tx_pma_rst_reg;
      rd_dat_d0(7) <= '0';
      rd_dat_d0(8) <= reset_gth_rx_rst_reg;
      rd_dat_d0(9) <= reset_gth_rx_pcs_rst_reg;
      rd_dat_d0(10) <= reset_gth_rx_pma_rst_reg;
      rd_dat_d0(11) <= reset_gth_rx_buf_rst_reg;
      rd_dat_d0(31 downto 12) <= (others => '0');
    when "010" =>
      -- Reg status
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= status_i;
    when "011" =>
      -- Reg ctrl
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(0) <= ctrl_rdy_reg;
      rd_dat_d0(31 downto 1) <= (others => '0');
    when "100" =>
      -- Reg bitslide
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= bitslide_i;
    when others =>
      rd_ack_d0 <= rd_req_int;
    end case;
  end process;
end syn;
