-- Do not edit.  Generated by cheby 1.7.dev0 using these options:
--  --gen-hdl rxpi_gthe4_map.vhd --gen-c rxpi_gthe4_map.h -i rxpi_gthe4_map.cheby
-- Generated on Mon Aug 17 11:28:52 2026 by geniejhang


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;

entity rxpi_gthe4_map is
  port (
    rst_n_i              : in    std_logic;
    clk_i                : in    std_logic;
    wb_i                 : in    t_wishbone_slave_in;
    wb_o                 : out   t_wishbone_slave_out;

    -- Reset register
    -- reset RX PMA for a different position
    reset_gth_rx_pma_rst_o : out   std_logic;
    reset_gth_rst_o      : out   std_logic;
    reset_gth_tx_rst_o   : out   std_logic;
    reset_gth_tx_pcs_rst_o : out   std_logic;
    reset_gth_tx_pma_rst_o : out   std_logic;
    reset_gth_rx_rst_o   : out   std_logic;
    reset_gth_rx_pcs_rst_o : out   std_logic;
    reset_gth_rx_buf_rst_o : out   std_logic;
    reset_rxpi_rst_o     : out   std_logic;

    -- REG status
    -- serdes ready (reset and bypass done) and bitslide done
    status_phy_ready_i   : in    std_logic;
    status_extra_i       : in    std_logic_vector(15 downto 0);

    -- REG ctrl
    -- Transceiver is fully ready
    ctrl_rdy_o           : out   std_logic;

    -- Bitslide
    bitslide_i           : in    std_logic_vector(31 downto 0);

    -- REG rxpi_nsamp
    rxpi_nsamp_o         : out   std_logic_vector(31 downto 0);

    -- REG rxpi_shift
    rxpi_shift_o         : out   std_logic_vector(31 downto 0);

    -- Control for phase shift
    ps_ctrl_rst_o        : out   std_logic;
    ps_ctrl_pd_o         : out   std_logic;
    ps_ctrl_incdec_o     : out   std_logic;
    ps_ctrl_shift_i      : in    std_logic;
    ps_ctrl_shift_o      : out   std_logic;
    ps_ctrl_wr_o         : out   std_logic;

    -- Status for phase shift
    ps_stat_phase_i      : in    std_logic_vector(15 downto 0);
    ps_stat_fb_stopped_i : in    std_logic;
    ps_stat_in_stopped_i : in    std_logic;
    ps_stat_locked_i     : in    std_logic;
    ps_stat_ps_busy_i    : in    std_logic;

    -- Number of sampling for ps
    ps_count_val_o       : out   std_logic_vector(23 downto 0);

    -- Number of sampling for ps
    ps_res_val_i         : in    std_logic_vector(23 downto 0);
    ps_res_gen_i         : in    std_logic_vector(7 downto 0);

    -- TX phase interpolator (TXPIPPM) control
    -- TXPIPPMEN - enable TX PI PPM stepping
    txpi_ctrl_en_o       : out   std_logic;
    -- TXPIPPMOVRDEN - override enable
    txpi_ctrl_ovrden_o   : out   std_logic;
    -- TXPIPPMPD - power down
    txpi_ctrl_pd_o       : out   std_logic;
    -- TXPIPPMSEL - select
    txpi_ctrl_sel_o      : out   std_logic;
    -- TXPIPPMSTEPSIZE
    txpi_ctrl_stepsize_o : out   std_logic_vector(4 downto 0);

    -- Issue a counted TXPIPPMEN pulse of <nsteps> clk_62m5 cycles
    txpi_step_nsteps_o   : out   std_logic_vector(23 downto 0);
    txpi_step_wr_o       : out   std_logic;

    -- TXPI counted-pulse status
    -- counted pulse in progress
    txpi_stat_busy_i     : in    std_logic
  );
end rxpi_gthe4_map;

architecture syn of rxpi_gthe4_map is
  signal adr_int                        : std_logic_vector(5 downto 2);
  signal rd_req_int                     : std_logic;
  signal wr_req_int                     : std_logic;
  signal rd_ack_int                     : std_logic;
  signal wr_ack_int                     : std_logic;
  signal wb_en                          : std_logic;
  signal ack_int                        : std_logic;
  signal wb_rip                         : std_logic;
  signal wb_wip                         : std_logic;
  signal reset_gth_rx_pma_rst_reg       : std_logic;
  signal reset_gth_rst_reg              : std_logic;
  signal reset_gth_tx_rst_reg           : std_logic;
  signal reset_gth_tx_pcs_rst_reg       : std_logic;
  signal reset_gth_tx_pma_rst_reg       : std_logic;
  signal reset_gth_rx_rst_reg           : std_logic;
  signal reset_gth_rx_pcs_rst_reg       : std_logic;
  signal reset_gth_rx_buf_rst_reg       : std_logic;
  signal reset_rxpi_rst_reg             : std_logic;
  signal reset_wreq                     : std_logic;
  signal reset_wack                     : std_logic;
  signal ctrl_rdy_reg                   : std_logic;
  signal ctrl_wreq                      : std_logic;
  signal ctrl_wack                      : std_logic;
  signal rxpi_nsamp_reg                 : std_logic_vector(31 downto 0);
  signal rxpi_nsamp_wreq                : std_logic;
  signal rxpi_nsamp_wack                : std_logic;
  signal rxpi_shift_reg                 : std_logic_vector(31 downto 0);
  signal rxpi_shift_wreq                : std_logic;
  signal rxpi_shift_wack                : std_logic;
  signal ps_ctrl_rst_reg                : std_logic;
  signal ps_ctrl_pd_reg                 : std_logic;
  signal ps_ctrl_incdec_reg             : std_logic;
  signal ps_ctrl_wreq                   : std_logic;
  signal ps_ctrl_wack                   : std_logic;
  signal ps_ctrl_wstrb                  : std_logic;
  signal ps_count_val_reg               : std_logic_vector(23 downto 0);
  signal ps_count_wreq                  : std_logic;
  signal ps_count_wack                  : std_logic;
  signal txpi_ctrl_en_reg               : std_logic;
  signal txpi_ctrl_ovrden_reg           : std_logic;
  signal txpi_ctrl_pd_reg               : std_logic;
  signal txpi_ctrl_sel_reg              : std_logic;
  signal txpi_ctrl_stepsize_reg         : std_logic_vector(4 downto 0);
  signal txpi_ctrl_wreq                 : std_logic;
  signal txpi_ctrl_wack                 : std_logic;
  signal txpi_step_nsteps_reg           : std_logic_vector(23 downto 0);
  signal txpi_step_wreq                 : std_logic;
  signal txpi_step_wack                 : std_logic;
  signal txpi_step_wstrb                : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(5 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
begin

  -- WB decode signals
  adr_int <= wb_i.adr(5 downto 2);
  wb_en <= wb_i.cyc and wb_i.stb;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_rip <= '0';
      else
        wb_rip <= (wb_rip or (wb_en and not wb_i.we)) and not rd_ack_int;
      end if;
    end if;
  end process;
  rd_req_int <= (wb_en and not wb_i.we) and not wb_rip;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_wip <= '0';
      else
        wb_wip <= (wb_wip or (wb_en and wb_i.we)) and not wr_ack_int;
      end if;
    end if;
  end process;
  wr_req_int <= (wb_en and wb_i.we) and not wb_wip;

  ack_int <= rd_ack_int or wr_ack_int;
  wb_o.ack <= ack_int;
  wb_o.stall <= not ack_int and wb_en;
  wb_o.rty <= '0';
  wb_o.err <= '0';

  -- pipelining for wr-in+rd-out
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        rd_ack_int <= '0';
        wb_o.dat <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_adr_d0 <= "0000";
        wr_dat_d0 <= "00000000000000000000000000000000";
      else
        rd_ack_int <= rd_ack_d0;
        wb_o.dat <= rd_dat_d0;
        wr_req_d0 <= wr_req_int;
        wr_adr_d0 <= adr_int;
        wr_dat_d0 <= wb_i.dat;
      end if;
    end if;
  end process;

  -- Register id

  -- Register reset
  reset_gth_rx_pma_rst_o <= reset_gth_rx_pma_rst_reg;
  reset_gth_rst_o <= reset_gth_rst_reg;
  reset_gth_tx_rst_o <= reset_gth_tx_rst_reg;
  reset_gth_tx_pcs_rst_o <= reset_gth_tx_pcs_rst_reg;
  reset_gth_tx_pma_rst_o <= reset_gth_tx_pma_rst_reg;
  reset_gth_rx_rst_o <= reset_gth_rx_rst_reg;
  reset_gth_rx_pcs_rst_o <= reset_gth_rx_pcs_rst_reg;
  reset_gth_rx_buf_rst_o <= reset_gth_rx_buf_rst_reg;
  reset_rxpi_rst_o <= reset_rxpi_rst_reg;
  reset_wack <= reset_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        reset_gth_rx_pma_rst_reg <= '0';
        reset_gth_rst_reg <= '0';
        reset_gth_tx_rst_reg <= '0';
        reset_gth_tx_pcs_rst_reg <= '0';
        reset_gth_tx_pma_rst_reg <= '0';
        reset_gth_rx_rst_reg <= '0';
        reset_gth_rx_pcs_rst_reg <= '0';
        reset_gth_rx_buf_rst_reg <= '0';
        reset_rxpi_rst_reg <= '0';
      else
        if reset_wreq = '1' then
          reset_gth_rx_pma_rst_reg <= wr_dat_d0(0);
          reset_gth_rst_reg <= wr_dat_d0(1);
          reset_gth_tx_rst_reg <= wr_dat_d0(2);
          reset_gth_tx_pcs_rst_reg <= wr_dat_d0(3);
          reset_gth_tx_pma_rst_reg <= wr_dat_d0(4);
          reset_gth_rx_rst_reg <= wr_dat_d0(5);
          reset_gth_rx_pcs_rst_reg <= wr_dat_d0(6);
          reset_gth_rx_buf_rst_reg <= wr_dat_d0(7);
          reset_rxpi_rst_reg <= wr_dat_d0(16);
        end if;
      end if;
    end if;
  end process;

  -- Register status

  -- Register ctrl
  ctrl_rdy_o <= ctrl_rdy_reg;
  ctrl_wack <= ctrl_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        ctrl_rdy_reg <= '0';
      else
        if ctrl_wreq = '1' then
          ctrl_rdy_reg <= wr_dat_d0(0);
        end if;
      end if;
    end if;
  end process;

  -- Register bitslide

  -- Register rxpi_nsamp
  rxpi_nsamp_o <= rxpi_nsamp_reg;
  rxpi_nsamp_wack <= rxpi_nsamp_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        rxpi_nsamp_reg <= "00000000000000000111111111111111";
      else
        if rxpi_nsamp_wreq = '1' then
          rxpi_nsamp_reg <= wr_dat_d0;
        end if;
      end if;
    end if;
  end process;

  -- Register rxpi_shift
  rxpi_shift_o <= rxpi_shift_reg;
  rxpi_shift_wack <= rxpi_shift_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        rxpi_shift_reg <= "00000000000000000000000000000000";
      else
        if rxpi_shift_wreq = '1' then
          rxpi_shift_reg <= wr_dat_d0;
        end if;
      end if;
    end if;
  end process;

  -- Register ps_ctrl
  ps_ctrl_rst_o <= ps_ctrl_rst_reg;
  ps_ctrl_pd_o <= ps_ctrl_pd_reg;
  ps_ctrl_incdec_o <= ps_ctrl_incdec_reg;
  ps_ctrl_shift_o <= wr_dat_d0(9);
  ps_ctrl_wack <= ps_ctrl_wreq;
  ps_ctrl_wstrb <= ps_ctrl_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        ps_ctrl_rst_reg <= '0';
        ps_ctrl_pd_reg <= '0';
        ps_ctrl_incdec_reg <= '0';
      else
        if ps_ctrl_wreq = '1' then
          ps_ctrl_rst_reg <= wr_dat_d0(0);
          ps_ctrl_pd_reg <= wr_dat_d0(1);
          ps_ctrl_incdec_reg <= wr_dat_d0(8);
        end if;
      end if;
    end if;
  end process;
  ps_ctrl_wr_o <= ps_ctrl_wstrb;

  -- Register ps_stat

  -- Register ps_count
  ps_count_val_o <= ps_count_val_reg;
  ps_count_wack <= ps_count_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        ps_count_val_reg <= "000000000000000000000000";
      else
        if ps_count_wreq = '1' then
          ps_count_val_reg <= wr_dat_d0(23 downto 0);
        end if;
      end if;
    end if;
  end process;

  -- Register ps_res

  -- Register txpi_ctrl
  txpi_ctrl_en_o <= txpi_ctrl_en_reg;
  txpi_ctrl_ovrden_o <= txpi_ctrl_ovrden_reg;
  txpi_ctrl_pd_o <= txpi_ctrl_pd_reg;
  txpi_ctrl_sel_o <= txpi_ctrl_sel_reg;
  txpi_ctrl_stepsize_o <= txpi_ctrl_stepsize_reg;
  txpi_ctrl_wack <= txpi_ctrl_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        txpi_ctrl_en_reg <= '0';
        txpi_ctrl_ovrden_reg <= '0';
        txpi_ctrl_pd_reg <= '0';
        txpi_ctrl_sel_reg <= '1';
        txpi_ctrl_stepsize_reg <= "10001";
      else
        if txpi_ctrl_wreq = '1' then
          txpi_ctrl_en_reg <= wr_dat_d0(0);
          txpi_ctrl_ovrden_reg <= wr_dat_d0(1);
          txpi_ctrl_pd_reg <= wr_dat_d0(2);
          txpi_ctrl_sel_reg <= wr_dat_d0(3);
          txpi_ctrl_stepsize_reg <= wr_dat_d0(8 downto 4);
        end if;
      end if;
    end if;
  end process;

  -- Register txpi_step
  txpi_step_nsteps_o <= txpi_step_nsteps_reg;
  txpi_step_wack <= txpi_step_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        txpi_step_nsteps_reg <= "000000000000000000000000";
        txpi_step_wstrb <= '0';
      else
        if txpi_step_wreq = '1' then
          txpi_step_nsteps_reg <= wr_dat_d0(23 downto 0);
        end if;
        txpi_step_wstrb <= txpi_step_wreq;
      end if;
    end if;
  end process;
  txpi_step_wr_o <= txpi_step_wstrb;

  -- Register txpi_stat

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0, reset_wack, ctrl_wack, rxpi_nsamp_wack,
           rxpi_shift_wack, ps_ctrl_wack, ps_count_wack, txpi_ctrl_wack,
           txpi_step_wack) begin
    reset_wreq <= '0';
    ctrl_wreq <= '0';
    rxpi_nsamp_wreq <= '0';
    rxpi_shift_wreq <= '0';
    ps_ctrl_wreq <= '0';
    ps_count_wreq <= '0';
    txpi_ctrl_wreq <= '0';
    txpi_step_wreq <= '0';
    case wr_adr_d0(5 downto 2) is
    when "0000" =>
      -- Reg id
      wr_ack_int <= wr_req_d0;
    when "0001" =>
      -- Reg reset
      reset_wreq <= wr_req_d0;
      wr_ack_int <= reset_wack;
    when "0010" =>
      -- Reg status
      wr_ack_int <= wr_req_d0;
    when "0011" =>
      -- Reg ctrl
      ctrl_wreq <= wr_req_d0;
      wr_ack_int <= ctrl_wack;
    when "0100" =>
      -- Reg bitslide
      wr_ack_int <= wr_req_d0;
    when "0101" =>
      -- Reg rxpi_nsamp
      rxpi_nsamp_wreq <= wr_req_d0;
      wr_ack_int <= rxpi_nsamp_wack;
    when "0110" =>
      -- Reg rxpi_shift
      rxpi_shift_wreq <= wr_req_d0;
      wr_ack_int <= rxpi_shift_wack;
    when "0111" =>
      -- Reg ps_ctrl
      ps_ctrl_wreq <= wr_req_d0;
      wr_ack_int <= ps_ctrl_wack;
    when "1000" =>
      -- Reg ps_stat
      wr_ack_int <= wr_req_d0;
    when "1001" =>
      -- Reg ps_count
      ps_count_wreq <= wr_req_d0;
      wr_ack_int <= ps_count_wack;
    when "1010" =>
      -- Reg ps_res
      wr_ack_int <= wr_req_d0;
    when "1011" =>
      -- Reg txpi_ctrl
      txpi_ctrl_wreq <= wr_req_d0;
      wr_ack_int <= txpi_ctrl_wack;
    when "1100" =>
      -- Reg txpi_step
      txpi_step_wreq <= wr_req_d0;
      wr_ack_int <= txpi_step_wack;
    when "1101" =>
      -- Reg txpi_stat
      wr_ack_int <= wr_req_d0;
    when others =>
      wr_ack_int <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (adr_int, rd_req_int, reset_gth_rx_pma_rst_reg, reset_gth_rst_reg,
           reset_gth_tx_rst_reg, reset_gth_tx_pcs_rst_reg,
           reset_gth_tx_pma_rst_reg, reset_gth_rx_rst_reg,
           reset_gth_rx_pcs_rst_reg, reset_gth_rx_buf_rst_reg,
           reset_rxpi_rst_reg, status_phy_ready_i, status_extra_i, ctrl_rdy_reg,
           bitslide_i, rxpi_nsamp_reg, rxpi_shift_reg, ps_ctrl_rst_reg,
           ps_ctrl_pd_reg, ps_ctrl_incdec_reg, ps_ctrl_shift_i, ps_stat_phase_i,
           ps_stat_fb_stopped_i, ps_stat_in_stopped_i, ps_stat_locked_i,
           ps_stat_ps_busy_i, ps_res_val_i, ps_res_gen_i, txpi_ctrl_en_reg,
           txpi_ctrl_ovrden_reg, txpi_ctrl_pd_reg, txpi_ctrl_sel_reg,
           txpi_ctrl_stepsize_reg, txpi_step_nsteps_reg, txpi_stat_busy_i) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    case adr_int(5 downto 2) is
    when "0000" =>
      -- Reg id
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= "00000000000001100001100011100100";
    when "0001" =>
      -- Reg reset
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(0) <= reset_gth_rx_pma_rst_reg;
      rd_dat_d0(1) <= reset_gth_rst_reg;
      rd_dat_d0(2) <= reset_gth_tx_rst_reg;
      rd_dat_d0(3) <= reset_gth_tx_pcs_rst_reg;
      rd_dat_d0(4) <= reset_gth_tx_pma_rst_reg;
      rd_dat_d0(5) <= reset_gth_rx_rst_reg;
      rd_dat_d0(6) <= reset_gth_rx_pcs_rst_reg;
      rd_dat_d0(7) <= reset_gth_rx_buf_rst_reg;
      rd_dat_d0(15 downto 8) <= (others => '0');
      rd_dat_d0(16) <= reset_rxpi_rst_reg;
      rd_dat_d0(31 downto 17) <= (others => '0');
    when "0010" =>
      -- Reg status
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(0) <= status_phy_ready_i;
      rd_dat_d0(15 downto 1) <= (others => '0');
      rd_dat_d0(31 downto 16) <= status_extra_i;
    when "0011" =>
      -- Reg ctrl
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(0) <= ctrl_rdy_reg;
      rd_dat_d0(31 downto 1) <= (others => '0');
    when "0100" =>
      -- Reg bitslide
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= bitslide_i;
    when "0101" =>
      -- Reg rxpi_nsamp
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= rxpi_nsamp_reg;
    when "0110" =>
      -- Reg rxpi_shift
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= rxpi_shift_reg;
    when "0111" =>
      -- Reg ps_ctrl
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(0) <= ps_ctrl_rst_reg;
      rd_dat_d0(1) <= ps_ctrl_pd_reg;
      rd_dat_d0(7 downto 2) <= (others => '0');
      rd_dat_d0(8) <= ps_ctrl_incdec_reg;
      rd_dat_d0(9) <= ps_ctrl_shift_i;
      rd_dat_d0(31 downto 10) <= (others => '0');
    when "1000" =>
      -- Reg ps_stat
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(15 downto 0) <= ps_stat_phase_i;
      rd_dat_d0(16) <= ps_stat_fb_stopped_i;
      rd_dat_d0(17) <= ps_stat_in_stopped_i;
      rd_dat_d0(18) <= ps_stat_locked_i;
      rd_dat_d0(19) <= ps_stat_ps_busy_i;
      rd_dat_d0(31 downto 20) <= (others => '0');
    when "1001" =>
      -- Reg ps_count
      rd_ack_d0 <= rd_req_int;
    when "1010" =>
      -- Reg ps_res
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(23 downto 0) <= ps_res_val_i;
      rd_dat_d0(31 downto 24) <= ps_res_gen_i;
    when "1011" =>
      -- Reg txpi_ctrl
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(0) <= txpi_ctrl_en_reg;
      rd_dat_d0(1) <= txpi_ctrl_ovrden_reg;
      rd_dat_d0(2) <= txpi_ctrl_pd_reg;
      rd_dat_d0(3) <= txpi_ctrl_sel_reg;
      rd_dat_d0(8 downto 4) <= txpi_ctrl_stepsize_reg;
      rd_dat_d0(31 downto 9) <= (others => '0');
    when "1100" =>
      -- Reg txpi_step
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(23 downto 0) <= txpi_step_nsteps_reg;
      rd_dat_d0(31 downto 24) <= (others => '0');
    when "1101" =>
      -- Reg txpi_stat
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(0) <= txpi_stat_busy_i;
      rd_dat_d0(31 downto 1) <= (others => '0');
    when others =>
      rd_ack_d0 <= rd_req_int;
    end case;
  end process;
end syn;
