-------------------------------------------------------------------------------
-- SPDX-FileCopyrightText: 2025 CERN (home.cern)
--
-- SPDX-License-Identifier: CERN-OHL-W-2.0+
-------------------------------------------------------------------------------
-- Do not edit.  Generated by cheby 1.6.dev0 using these options:
--  -i nmea_master_regs.cheby --gen-hdl nmea_master_regs.vhd
-- Generated on Fri Dec 20 09:13:59 2024 by harvey


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package nmea_master_regs_pkg is
  type t_nmea_regs_master_out is record
    CR_baud_div      : std_logic_vector(16 downto 0);
    CR_invert        : std_logic;
  end record t_nmea_regs_master_out;
  subtype t_nmea_regs_slave_in is t_nmea_regs_master_out;

  type t_nmea_regs_slave_out is record
    SR_tip           : std_logic;
    SR_valid         : std_logic;
    SR_clk_freq      : std_logic_vector(29 downto 0);
    TOD_second       : std_logic_vector(7 downto 0);
    TOD_minute       : std_logic_vector(7 downto 0);
    TOD_hour         : std_logic_vector(7 downto 0);
    DATE_day         : std_logic_vector(7 downto 0);
    DATE_month       : std_logic_vector(7 downto 0);
    DATE_year        : std_logic_vector(15 downto 0);
  end record t_nmea_regs_slave_out;
  subtype t_nmea_regs_master_in is t_nmea_regs_slave_out;

end nmea_master_regs_pkg;

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.nmea_master_regs_pkg.all;

entity nmea_master_regs is
  port (
    rst_n_i              : in    std_logic;
    clk_i                : in    std_logic;
    wb_cyc_i             : in    std_logic;
    wb_stb_i             : in    std_logic;
    wb_adr_i             : in    std_logic_vector(3 downto 2);
    wb_sel_i             : in    std_logic_vector(3 downto 0);
    wb_we_i              : in    std_logic;
    wb_dat_i             : in    std_logic_vector(31 downto 0);
    wb_ack_o             : out   std_logic;
    wb_err_o             : out   std_logic;
    wb_rty_o             : out   std_logic;
    wb_stall_o           : out   std_logic;
    wb_dat_o             : out   std_logic_vector(31 downto 0);
    -- Wires and registers
    nmea_regs_i          : in    t_nmea_regs_master_in;
    nmea_regs_o          : out   t_nmea_regs_master_out
  );
end nmea_master_regs;

architecture syn of nmea_master_regs is
  signal rd_req_int                     : std_logic;
  signal wr_req_int                     : std_logic;
  signal rd_ack_int                     : std_logic;
  signal wr_ack_int                     : std_logic;
  signal wb_en                          : std_logic;
  signal ack_int                        : std_logic;
  signal wb_rip                         : std_logic;
  signal wb_wip                         : std_logic;
  signal CR_baud_div_reg                : std_logic_vector(16 downto 0);
  signal CR_invert_reg                  : std_logic;
  signal CR_wreq                        : std_logic;
  signal CR_wack                        : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(3 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
begin

  -- WB decode signals
  wb_en <= wb_cyc_i and wb_stb_i;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_rip <= '0';
      else
        wb_rip <= (wb_rip or (wb_en and not wb_we_i)) and not rd_ack_int;
      end if;
    end if;
  end process;
  rd_req_int <= (wb_en and not wb_we_i) and not wb_rip;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_wip <= '0';
      else
        wb_wip <= (wb_wip or (wb_en and wb_we_i)) and not wr_ack_int;
      end if;
    end if;
  end process;
  wr_req_int <= (wb_en and wb_we_i) and not wb_wip;

  ack_int <= rd_ack_int or wr_ack_int;
  wb_ack_o <= ack_int;
  wb_stall_o <= not ack_int and wb_en;
  wb_rty_o <= '0';
  wb_err_o <= '0';

  -- pipelining for wr-in+rd-out
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        rd_ack_int <= '0';
        wb_dat_o <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_adr_d0 <= "00";
        wr_dat_d0 <= "00000000000000000000000000000000";
      else
        rd_ack_int <= rd_ack_d0;
        wb_dat_o <= rd_dat_d0;
        wr_req_d0 <= wr_req_int;
        wr_adr_d0 <= wb_adr_i;
        wr_dat_d0 <= wb_dat_i;
      end if;
    end if;
  end process;

  -- Register CR
  nmea_regs_o.CR_baud_div <= CR_baud_div_reg;
  nmea_regs_o.CR_invert <= CR_invert_reg;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        CR_baud_div_reg <= "00000001111000110";
        CR_invert_reg <= '0';
        CR_wack <= '0';
      else
        if CR_wreq = '1' then
          CR_baud_div_reg <= wr_dat_d0(16 downto 0);
          CR_invert_reg <= wr_dat_d0(17);
        end if;
        CR_wack <= CR_wreq;
      end if;
    end if;
  end process;

  -- Register SR

  -- Register TOD

  -- Register DATE

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0, CR_wack) begin
    CR_wreq <= '0';
    case wr_adr_d0(3 downto 2) is
    when "00" =>
      -- Reg CR
      CR_wreq <= wr_req_d0;
      wr_ack_int <= CR_wack;
    when "01" =>
      -- Reg SR
      wr_ack_int <= wr_req_d0;
    when "10" =>
      -- Reg TOD
      wr_ack_int <= wr_req_d0;
    when "11" =>
      -- Reg DATE
      wr_ack_int <= wr_req_d0;
    when others =>
      wr_ack_int <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (wb_adr_i, rd_req_int, CR_baud_div_reg, CR_invert_reg,
           nmea_regs_i.SR_tip, nmea_regs_i.SR_valid, nmea_regs_i.SR_clk_freq,
           nmea_regs_i.TOD_second, nmea_regs_i.TOD_minute,
           nmea_regs_i.TOD_hour, nmea_regs_i.DATE_day, nmea_regs_i.DATE_month,
           nmea_regs_i.DATE_year) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    case wb_adr_i(3 downto 2) is
    when "00" =>
      -- Reg CR
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(16 downto 0) <= CR_baud_div_reg;
      rd_dat_d0(17) <= CR_invert_reg;
      rd_dat_d0(31 downto 18) <= (others => '0');
    when "01" =>
      -- Reg SR
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(0) <= nmea_regs_i.SR_tip;
      rd_dat_d0(1) <= nmea_regs_i.SR_valid;
      rd_dat_d0(31 downto 2) <= nmea_regs_i.SR_clk_freq;
    when "10" =>
      -- Reg TOD
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(7 downto 0) <= nmea_regs_i.TOD_second;
      rd_dat_d0(15 downto 8) <= nmea_regs_i.TOD_minute;
      rd_dat_d0(23 downto 16) <= nmea_regs_i.TOD_hour;
      rd_dat_d0(31 downto 24) <= (others => '0');
    when "11" =>
      -- Reg DATE
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(7 downto 0) <= nmea_regs_i.DATE_day;
      rd_dat_d0(15 downto 8) <= nmea_regs_i.DATE_month;
      rd_dat_d0(31 downto 16) <= nmea_regs_i.DATE_year;
    when others =>
      rd_ack_d0 <= rd_req_int;
    end case;
  end process;
end syn;
