-- Do not edit.  Generated by cheby 1.7.dev0 using these options:
--  -i board_zcu10x_bus_wb.cheby --hdl vhdl --gen-hdl board_zcu10x_bus_wb.vhd
-- Generated on Wed Nov 19 18:34:59 2025 by oskar


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;

entity board_zcu10x_bus_wb is
  port (
    rst_n_i              : in    std_logic;
    clk_i                : in    std_logic;
    wb_i                 : in    t_wishbone_slave_in;
    wb_o                 : out   t_wishbone_slave_out;

    -- WB bus fmc_enable
    fmc_enable_i         : in    t_wishbone_master_in;
    fmc_enable_o         : out   t_wishbone_master_out;

    -- WB bus gnss_uart
    gnss_uart_i          : in    t_wishbone_master_in;
    gnss_uart_o          : out   t_wishbone_master_out;

    -- WB bus si5xx
    si5xx_i              : in    t_wishbone_master_in;
    si5xx_o              : out   t_wishbone_master_out
  );
end board_zcu10x_bus_wb;

architecture syn of board_zcu10x_bus_wb is
  signal wr_sel                         : std_logic_vector(31 downto 0);
  signal adr_int                        : std_logic_vector(8 downto 2);
  signal rd_req_int                     : std_logic;
  signal wr_req_int                     : std_logic;
  signal rd_ack_int                     : std_logic;
  signal wr_ack_int                     : std_logic;
  signal wb_en                          : std_logic;
  signal ack_int                        : std_logic;
  signal wb_rip                         : std_logic;
  signal wb_wip                         : std_logic;
  signal fmc_enable_re                  : std_logic;
  signal fmc_enable_we                  : std_logic;
  signal fmc_enable_wt                  : std_logic;
  signal fmc_enable_rt                  : std_logic;
  signal fmc_enable_tr                  : std_logic;
  signal fmc_enable_wack                : std_logic;
  signal fmc_enable_rack                : std_logic;
  signal gnss_uart_re                   : std_logic;
  signal gnss_uart_we                   : std_logic;
  signal gnss_uart_wt                   : std_logic;
  signal gnss_uart_rt                   : std_logic;
  signal gnss_uart_tr                   : std_logic;
  signal gnss_uart_wack                 : std_logic;
  signal gnss_uart_rack                 : std_logic;
  signal si5xx_re                       : std_logic;
  signal si5xx_we                       : std_logic;
  signal si5xx_wt                       : std_logic;
  signal si5xx_rt                       : std_logic;
  signal si5xx_tr                       : std_logic;
  signal si5xx_wack                     : std_logic;
  signal si5xx_rack                     : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(8 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_sel_d0                      : std_logic_vector(31 downto 0);
begin

  -- WB decode signals
  process (wb_i.sel) begin
    wr_sel(7 downto 0) <= (others => wb_i.sel(0));
    wr_sel(15 downto 8) <= (others => wb_i.sel(1));
    wr_sel(23 downto 16) <= (others => wb_i.sel(2));
    wr_sel(31 downto 24) <= (others => wb_i.sel(3));
  end process;
  adr_int <= wb_i.adr(8 downto 2);
  wb_en <= wb_i.cyc and wb_i.stb;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_rip <= '0';
      else
        wb_rip <= (wb_rip or (wb_en and not wb_i.we)) and not rd_ack_int;
      end if;
    end if;
  end process;
  rd_req_int <= (wb_en and not wb_i.we) and not wb_rip;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_wip <= '0';
      else
        wb_wip <= (wb_wip or (wb_en and wb_i.we)) and not wr_ack_int;
      end if;
    end if;
  end process;
  wr_req_int <= (wb_en and wb_i.we) and not wb_wip;

  ack_int <= rd_ack_int or wr_ack_int;
  wb_o.ack <= ack_int;
  wb_o.stall <= not ack_int and wb_en;
  wb_o.rty <= '0';
  wb_o.err <= '0';

  -- pipelining for wr-in+rd-out
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        rd_ack_int <= '0';
        wb_o.dat <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_adr_d0 <= "0000000";
        wr_dat_d0 <= "00000000000000000000000000000000";
        wr_sel_d0 <= "00000000000000000000000000000000";
      else
        rd_ack_int <= rd_ack_d0;
        wb_o.dat <= rd_dat_d0;
        wr_req_d0 <= wr_req_int;
        wr_adr_d0 <= adr_int;
        wr_dat_d0 <= wb_i.dat;
        wr_sel_d0 <= wr_sel;
      end if;
    end if;
  end process;

  -- Interface fmc_enable
  fmc_enable_tr <= fmc_enable_wt or fmc_enable_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        fmc_enable_rt <= '0';
        fmc_enable_wt <= '0';
      else
        fmc_enable_rt <= (fmc_enable_rt or fmc_enable_re) and not fmc_enable_rack;
        fmc_enable_wt <= (fmc_enable_wt or fmc_enable_we) and not fmc_enable_wack;
      end if;
    end if;
  end process;
  fmc_enable_o.cyc <= fmc_enable_tr;
  fmc_enable_o.stb <= fmc_enable_tr;
  fmc_enable_wack <= fmc_enable_i.ack and fmc_enable_wt;
  fmc_enable_rack <= fmc_enable_i.ack and fmc_enable_rt;
  fmc_enable_o.adr <= ((23 downto 0 => '0') & adr_int(7 downto 2)) & (1 downto 0 => '0');
  process (wr_sel_d0) begin
    fmc_enable_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      fmc_enable_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      fmc_enable_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      fmc_enable_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      fmc_enable_o.sel(3) <= '1';
    end if;
  end process;
  fmc_enable_o.we <= fmc_enable_wt;
  fmc_enable_o.dat <= wr_dat_d0;

  -- Interface gnss_uart
  gnss_uart_tr <= gnss_uart_wt or gnss_uart_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        gnss_uart_rt <= '0';
        gnss_uart_wt <= '0';
      else
        gnss_uart_rt <= (gnss_uart_rt or gnss_uart_re) and not gnss_uart_rack;
        gnss_uart_wt <= (gnss_uart_wt or gnss_uart_we) and not gnss_uart_wack;
      end if;
    end if;
  end process;
  gnss_uart_o.cyc <= gnss_uart_tr;
  gnss_uart_o.stb <= gnss_uart_tr;
  gnss_uart_wack <= gnss_uart_i.ack and gnss_uart_wt;
  gnss_uart_rack <= gnss_uart_i.ack and gnss_uart_rt;
  gnss_uart_o.adr <= ((26 downto 0 => '0') & adr_int(4 downto 2)) & (1 downto 0 => '0');
  process (wr_sel_d0) begin
    gnss_uart_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      gnss_uart_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      gnss_uart_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      gnss_uart_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      gnss_uart_o.sel(3) <= '1';
    end if;
  end process;
  gnss_uart_o.we <= gnss_uart_wt;
  gnss_uart_o.dat <= wr_dat_d0;

  -- Interface si5xx
  si5xx_tr <= si5xx_wt or si5xx_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        si5xx_rt <= '0';
        si5xx_wt <= '0';
      else
        si5xx_rt <= (si5xx_rt or si5xx_re) and not si5xx_rack;
        si5xx_wt <= (si5xx_wt or si5xx_we) and not si5xx_wack;
      end if;
    end if;
  end process;
  si5xx_o.cyc <= si5xx_tr;
  si5xx_o.stb <= si5xx_tr;
  si5xx_wack <= si5xx_i.ack and si5xx_wt;
  si5xx_rack <= si5xx_i.ack and si5xx_rt;
  si5xx_o.adr <= ((26 downto 0 => '0') & adr_int(4 downto 2)) & (1 downto 0 => '0');
  process (wr_sel_d0) begin
    si5xx_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      si5xx_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      si5xx_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      si5xx_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      si5xx_o.sel(3) <= '1';
    end if;
  end process;
  si5xx_o.we <= si5xx_wt;
  si5xx_o.dat <= wr_dat_d0;

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0, fmc_enable_wack, gnss_uart_wack, si5xx_wack) begin
    fmc_enable_we <= '0';
    gnss_uart_we <= '0';
    si5xx_we <= '0';
    case wr_adr_d0(8 downto 8) is
    when "0" =>
      -- Submap fmc_enable
      fmc_enable_we <= wr_req_d0;
      wr_ack_int <= fmc_enable_wack;
    when "1" =>
      case wr_adr_d0(7 downto 5) is
      when "000" =>
        -- Submap gnss_uart
        gnss_uart_we <= wr_req_d0;
        wr_ack_int <= gnss_uart_wack;
      when "001" =>
        -- Submap si5xx
        si5xx_we <= wr_req_d0;
        wr_ack_int <= si5xx_wack;
      when others =>
        wr_ack_int <= wr_req_d0;
      end case;
    when others =>
      wr_ack_int <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (adr_int, rd_req_int, fmc_enable_i.dat, fmc_enable_rack, gnss_uart_i.dat,
           gnss_uart_rack, si5xx_i.dat, si5xx_rack) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    fmc_enable_re <= '0';
    gnss_uart_re <= '0';
    si5xx_re <= '0';
    case adr_int(8 downto 8) is
    when "0" =>
      -- Submap fmc_enable
      fmc_enable_re <= rd_req_int;
      rd_dat_d0 <= fmc_enable_i.dat;
      rd_ack_d0 <= fmc_enable_rack;
    when "1" =>
      case adr_int(7 downto 5) is
      when "000" =>
        -- Submap gnss_uart
        gnss_uart_re <= rd_req_int;
        rd_dat_d0 <= gnss_uart_i.dat;
        rd_ack_d0 <= gnss_uart_rack;
      when "001" =>
        -- Submap si5xx
        si5xx_re <= rd_req_int;
        rd_dat_d0 <= si5xx_i.dat;
        rd_ack_d0 <= si5xx_rack;
      when others =>
        rd_ack_d0 <= rd_req_int;
      end case;
    when others =>
      rd_ack_d0 <= rd_req_int;
    end case;
  end process;
end syn;
