-- Do not edit.  Generated by cheby 1.7.dev0 using these options:
--  -i wrc_host_map.cheby --header=commit --gen-hdl wrc_host_map.vhd --gen-c wrc_host_map.h


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;

entity wrc_host_map is
  port (
    rst_n_i              : in    std_logic;
    clk_i                : in    std_logic;
    wb_i                 : in    t_wishbone_slave_in;
    wb_o                 : out   t_wishbone_slave_out;

    -- MAC Address bits [47:32]
    endpoint_mach_i      : in    std_logic_vector(31 downto 0);

    -- MAC Address bits [31:0]
    endpoint_macl_i      : in    std_logic_vector(31 downto 0);

    -- WB bus spll
    spll_i               : in    t_wishbone_master_in;
    spll_o               : out   t_wishbone_master_out;

    -- HW feature register
    -- Memory size (in 64KB units)
    syscon_hwfr_memory_i : in    std_logic_vector(3 downto 0);
    syscon_hwfr_STORAGE_SEC_i : in    std_logic_vector(15 downto 0);

    -- HW identification (name of the board)
    syscon_hwir_i        : in    std_logic_vector(31 downto 0);

    -- WB bus vuart
    vuart_i              : in    t_wishbone_master_in;
    vuart_o              : out   t_wishbone_master_out;

    -- WB bus wdiags
    wdiags_i             : in    t_wishbone_master_in;
    wdiags_o             : out   t_wishbone_master_out;

    -- WB bus cpu
    cpu_i                : in    t_wishbone_master_in;
    cpu_o                : out   t_wishbone_master_out
  );
end wrc_host_map;

architecture syn of wrc_host_map is
  signal wr_sel                         : std_logic_vector(31 downto 0);
  signal adr_int                        : std_logic_vector(11 downto 2);
  signal rd_req_int                     : std_logic;
  signal wr_req_int                     : std_logic;
  signal rd_ack_int                     : std_logic;
  signal wr_ack_int                     : std_logic;
  signal wb_en                          : std_logic;
  signal ack_int                        : std_logic;
  signal wb_rip                         : std_logic;
  signal wb_wip                         : std_logic;
  signal spll_re                        : std_logic;
  signal spll_we                        : std_logic;
  signal spll_wt                        : std_logic;
  signal spll_rt                        : std_logic;
  signal spll_tr                        : std_logic;
  signal spll_wack                      : std_logic;
  signal spll_rack                      : std_logic;
  signal vuart_re                       : std_logic;
  signal vuart_we                       : std_logic;
  signal vuart_wt                       : std_logic;
  signal vuart_rt                       : std_logic;
  signal vuart_tr                       : std_logic;
  signal vuart_wack                     : std_logic;
  signal vuart_rack                     : std_logic;
  signal wdiags_re                      : std_logic;
  signal wdiags_we                      : std_logic;
  signal wdiags_wt                      : std_logic;
  signal wdiags_rt                      : std_logic;
  signal wdiags_tr                      : std_logic;
  signal wdiags_wack                    : std_logic;
  signal wdiags_rack                    : std_logic;
  signal cpu_re                         : std_logic;
  signal cpu_we                         : std_logic;
  signal cpu_wt                         : std_logic;
  signal cpu_rt                         : std_logic;
  signal cpu_tr                         : std_logic;
  signal cpu_wack                       : std_logic;
  signal cpu_rack                       : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(11 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_sel_d0                      : std_logic_vector(31 downto 0);
begin

  -- WB decode signals
  process (wb_i.sel) begin
    wr_sel(7 downto 0) <= (others => wb_i.sel(0));
    wr_sel(15 downto 8) <= (others => wb_i.sel(1));
    wr_sel(23 downto 16) <= (others => wb_i.sel(2));
    wr_sel(31 downto 24) <= (others => wb_i.sel(3));
  end process;
  adr_int <= wb_i.adr(11 downto 2);
  wb_en <= wb_i.cyc and wb_i.stb;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_rip <= '0';
      else
        wb_rip <= (wb_rip or (wb_en and not wb_i.we)) and not rd_ack_int;
      end if;
    end if;
  end process;
  rd_req_int <= (wb_en and not wb_i.we) and not wb_rip;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_wip <= '0';
      else
        wb_wip <= (wb_wip or (wb_en and wb_i.we)) and not wr_ack_int;
      end if;
    end if;
  end process;
  wr_req_int <= (wb_en and wb_i.we) and not wb_wip;

  ack_int <= rd_ack_int or wr_ack_int;
  wb_o.ack <= ack_int;
  wb_o.stall <= not ack_int and wb_en;
  wb_o.rty <= '0';
  wb_o.err <= '0';

  -- pipelining for wr-in+rd-out
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        rd_ack_int <= '0';
        wb_o.dat <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_adr_d0 <= "0000000000";
        wr_dat_d0 <= "00000000000000000000000000000000";
        wr_sel_d0 <= "00000000000000000000000000000000";
      else
        rd_ack_int <= rd_ack_d0;
        wb_o.dat <= rd_dat_d0;
        wr_req_d0 <= wr_req_int;
        wr_adr_d0 <= adr_int;
        wr_dat_d0 <= wb_i.dat;
        wr_sel_d0 <= wr_sel;
      end if;
    end if;
  end process;

  -- Register magic

  -- Register mapver

  -- Register endpoint_mach

  -- Register endpoint_macl

  -- Interface spll
  spll_tr <= spll_wt or spll_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        spll_rt <= '0';
        spll_wt <= '0';
      else
        spll_rt <= (spll_rt or spll_re) and not spll_rack;
        spll_wt <= (spll_wt or spll_we) and not spll_wack;
      end if;
    end if;
  end process;
  spll_o.cyc <= spll_tr;
  spll_o.stb <= spll_tr;
  spll_wack <= spll_i.ack and spll_wt;
  spll_rack <= spll_i.ack and spll_rt;
  spll_o.adr <= ((27 downto 0 => '0') & adr_int(3 downto 2)) & (1 downto 0 => '0');
  process (wr_sel_d0) begin
    spll_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      spll_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      spll_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      spll_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      spll_o.sel(3) <= '1';
    end if;
  end process;
  spll_o.we <= spll_wt;
  spll_o.dat <= wr_dat_d0;

  -- Register syscon_hwfr

  -- Register syscon_hwir

  -- Interface vuart
  vuart_tr <= vuart_wt or vuart_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        vuart_rt <= '0';
        vuart_wt <= '0';
      else
        vuart_rt <= (vuart_rt or vuart_re) and not vuart_rack;
        vuart_wt <= (vuart_wt or vuart_we) and not vuart_wack;
      end if;
    end if;
  end process;
  vuart_o.cyc <= vuart_tr;
  vuart_o.stb <= vuart_tr;
  vuart_wack <= vuart_i.ack and vuart_wt;
  vuart_rack <= vuart_i.ack and vuart_rt;
  vuart_o.adr <= ((28 downto 0 => '0') & adr_int(2 downto 2)) & (1 downto 0 => '0');
  process (wr_sel_d0) begin
    vuart_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      vuart_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      vuart_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      vuart_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      vuart_o.sel(3) <= '1';
    end if;
  end process;
  vuart_o.we <= vuart_wt;
  vuart_o.dat <= wr_dat_d0;

  -- Interface wdiags
  wdiags_tr <= wdiags_wt or wdiags_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wdiags_rt <= '0';
        wdiags_wt <= '0';
      else
        wdiags_rt <= (wdiags_rt or wdiags_re) and not wdiags_rack;
        wdiags_wt <= (wdiags_wt or wdiags_we) and not wdiags_wack;
      end if;
    end if;
  end process;
  wdiags_o.cyc <= wdiags_tr;
  wdiags_o.stb <= wdiags_tr;
  wdiags_wack <= wdiags_i.ack and wdiags_wt;
  wdiags_rack <= wdiags_i.ack and wdiags_rt;
  wdiags_o.adr <= ((23 downto 0 => '0') & adr_int(7 downto 2)) & (1 downto 0 => '0');
  process (wr_sel_d0) begin
    wdiags_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      wdiags_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      wdiags_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      wdiags_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      wdiags_o.sel(3) <= '1';
    end if;
  end process;
  wdiags_o.we <= wdiags_wt;
  wdiags_o.dat <= wr_dat_d0;

  -- Interface cpu
  cpu_tr <= cpu_wt or cpu_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        cpu_rt <= '0';
        cpu_wt <= '0';
      else
        cpu_rt <= (cpu_rt or cpu_re) and not cpu_rack;
        cpu_wt <= (cpu_wt or cpu_we) and not cpu_wack;
      end if;
    end if;
  end process;
  cpu_o.cyc <= cpu_tr;
  cpu_o.stb <= cpu_tr;
  cpu_wack <= cpu_i.ack and cpu_wt;
  cpu_rack <= cpu_i.ack and cpu_rt;
  cpu_o.adr <= ((23 downto 0 => '0') & adr_int(7 downto 2)) & (1 downto 0 => '0');
  process (wr_sel_d0) begin
    cpu_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      cpu_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      cpu_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      cpu_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      cpu_o.sel(3) <= '1';
    end if;
  end process;
  cpu_o.we <= cpu_wt;
  cpu_o.dat <= wr_dat_d0;

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0, spll_wack, vuart_wack, wdiags_wack, cpu_wack) begin
    spll_we <= '0';
    vuart_we <= '0';
    wdiags_we <= '0';
    cpu_we <= '0';
    case wr_adr_d0(11 downto 8) is
    when "0000" =>
      case wr_adr_d0(7 downto 2) is
      when "000000" =>
        -- Reg magic
        wr_ack_int <= wr_req_d0;
      when "000001" =>
        -- Reg mapver
        wr_ack_int <= wr_req_d0;
      when others =>
        wr_ack_int <= wr_req_d0;
      end case;
    when "0001" =>
      case wr_adr_d0(7 downto 2) is
      when "001001" =>
        -- Reg endpoint_mach
        wr_ack_int <= wr_req_d0;
      when "001010" =>
        -- Reg endpoint_macl
        wr_ack_int <= wr_req_d0;
      when others =>
        wr_ack_int <= wr_req_d0;
      end case;
    when "0010" =>
      -- Submap spll
      spll_we <= wr_req_d0;
      wr_ack_int <= spll_wack;
    when "0100" =>
      case wr_adr_d0(7 downto 2) is
      when "000011" =>
        -- Reg syscon_hwfr
        wr_ack_int <= wr_req_d0;
      when "000100" =>
        -- Reg syscon_hwir
        wr_ack_int <= wr_req_d0;
      when others =>
        wr_ack_int <= wr_req_d0;
      end case;
    when "0101" =>
      -- Submap vuart
      vuart_we <= wr_req_d0;
      wr_ack_int <= vuart_wack;
    when "1001" =>
      -- Submap wdiags
      wdiags_we <= wr_req_d0;
      wr_ack_int <= wdiags_wack;
    when "1011" =>
      -- Submap cpu
      cpu_we <= wr_req_d0;
      wr_ack_int <= cpu_wack;
    when others =>
      wr_ack_int <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (adr_int, rd_req_int, endpoint_mach_i, endpoint_macl_i, spll_i.dat,
           spll_rack, syscon_hwfr_memory_i, syscon_hwfr_STORAGE_SEC_i,
           syscon_hwir_i, vuart_i.dat, vuart_rack, wdiags_i.dat, wdiags_rack,
           cpu_i.dat, cpu_rack) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    spll_re <= '0';
    vuart_re <= '0';
    wdiags_re <= '0';
    cpu_re <= '0';
    case adr_int(11 downto 8) is
    when "0000" =>
      case adr_int(7 downto 2) is
      when "000000" =>
        -- Reg magic
        rd_ack_d0 <= rd_req_int;
        rd_dat_d0 <= "01010111010100100101000001000011";
      when "000001" =>
        -- Reg mapver
        rd_ack_d0 <= rd_req_int;
        rd_dat_d0 <= "00000000000000000000000000000001";
      when others =>
        rd_ack_d0 <= rd_req_int;
      end case;
    when "0001" =>
      case adr_int(7 downto 2) is
      when "001001" =>
        -- Reg endpoint_mach
        rd_ack_d0 <= rd_req_int;
        rd_dat_d0 <= endpoint_mach_i;
      when "001010" =>
        -- Reg endpoint_macl
        rd_ack_d0 <= rd_req_int;
        rd_dat_d0 <= endpoint_macl_i;
      when others =>
        rd_ack_d0 <= rd_req_int;
      end case;
    when "0010" =>
      -- Submap spll
      spll_re <= rd_req_int;
      rd_dat_d0 <= spll_i.dat;
      rd_ack_d0 <= spll_rack;
    when "0100" =>
      case adr_int(7 downto 2) is
      when "000011" =>
        -- Reg syscon_hwfr
        rd_ack_d0 <= rd_req_int;
        rd_dat_d0(3 downto 0) <= syscon_hwfr_memory_i;
        rd_dat_d0(15 downto 4) <= (others => '0');
        rd_dat_d0(31 downto 16) <= syscon_hwfr_STORAGE_SEC_i;
      when "000100" =>
        -- Reg syscon_hwir
        rd_ack_d0 <= rd_req_int;
        rd_dat_d0 <= syscon_hwir_i;
      when others =>
        rd_ack_d0 <= rd_req_int;
      end case;
    when "0101" =>
      -- Submap vuart
      vuart_re <= rd_req_int;
      rd_dat_d0 <= vuart_i.dat;
      rd_ack_d0 <= vuart_rack;
    when "1001" =>
      -- Submap wdiags
      wdiags_re <= rd_req_int;
      rd_dat_d0 <= wdiags_i.dat;
      rd_ack_d0 <= wdiags_rack;
    when "1011" =>
      -- Submap cpu
      cpu_re <= rd_req_int;
      rd_dat_d0 <= cpu_i.dat;
      rd_ack_d0 <= cpu_rack;
    when others =>
      rd_ack_d0 <= rd_req_int;
    end case;
  end process;
end syn;
