-- Do not edit.  Generated by cheby 1.7.dev0 using these options:
--  -i wrc_cpu_csr.cheby --header=commit --gen-hdl


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;

package wrc_cpu_csr_pkg is
  type t_wrc_cpu_csr_regs_master_out is record
    RESET            : std_logic_vector(7 downto 0);
    UADDR            : std_logic_vector(31 downto 0);
    UDATA            : std_logic_vector(31 downto 0);
    UDATA_wr         : std_logic;
    DBG_FORCE        : std_logic_vector(7 downto 0);
    DBG_CORE0_INSN   : std_logic_vector(31 downto 0);
    DBG_CORE0_INSN_wr : std_logic;
    DBG_CORE0_MBX    : std_logic_vector(31 downto 0);
    DBG_CORE0_MBX_wr : std_logic;
  end record t_wrc_cpu_csr_regs_master_out;
  subtype t_wrc_cpu_csr_regs_slave_in is t_wrc_cpu_csr_regs_master_out;

  type t_wrc_cpu_csr_regs_slave_out is record
    UDATA            : std_logic_vector(31 downto 0);
    DBG_STATUS       : std_logic_vector(7 downto 0);
    DBG_INSN_READY   : std_logic_vector(7 downto 0);
    DBG_CORE0_MBX    : std_logic_vector(31 downto 0);
  end record t_wrc_cpu_csr_regs_slave_out;
  subtype t_wrc_cpu_csr_regs_master_in is t_wrc_cpu_csr_regs_slave_out;

end wrc_cpu_csr_pkg;

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;
use work.wrc_cpu_csr_pkg.all;

entity wrc_cpu_csr is
  port (
    rst_n_i              : in    std_logic;
    clk_i                : in    std_logic;
    wb_i                 : in    t_wishbone_slave_in;
    wb_o                 : out   t_wishbone_slave_out;
    -- Wires and registers
    wrc_cpu_csr_regs_i   : in    t_wrc_cpu_csr_regs_master_in;
    wrc_cpu_csr_regs_o   : out   t_wrc_cpu_csr_regs_master_out
  );
end wrc_cpu_csr;

architecture syn of wrc_cpu_csr is
  signal adr_int                        : std_logic_vector(7 downto 2);
  signal rd_req_int                     : std_logic;
  signal wr_req_int                     : std_logic;
  signal rd_ack_int                     : std_logic;
  signal wr_ack_int                     : std_logic;
  signal wb_en                          : std_logic;
  signal ack_int                        : std_logic;
  signal wb_rip                         : std_logic;
  signal wb_wip                         : std_logic;
  signal RESET_reg                      : std_logic_vector(7 downto 0);
  signal RESET_wreq                     : std_logic;
  signal RESET_wack                     : std_logic;
  signal UADDR_reg                      : std_logic_vector(31 downto 0);
  signal UADDR_wreq                     : std_logic;
  signal UADDR_wack                     : std_logic;
  signal UDATA_wreq                     : std_logic;
  signal DBG_FORCE_reg                  : std_logic_vector(7 downto 0);
  signal DBG_FORCE_wreq                 : std_logic;
  signal DBG_FORCE_wack                 : std_logic;
  signal DBG_CORE0_INSN_reg             : std_logic_vector(31 downto 0);
  signal DBG_CORE0_INSN_wreq            : std_logic;
  signal DBG_CORE0_INSN_wack            : std_logic;
  signal DBG_CORE0_INSN_wstrb           : std_logic;
  signal DBG_CORE0_MBX_wreq             : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(7 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
begin

  -- WB decode signals
  adr_int <= wb_i.adr(7 downto 2);
  wb_en <= wb_i.cyc and wb_i.stb;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_rip <= '0';
      else
        wb_rip <= (wb_rip or (wb_en and not wb_i.we)) and not rd_ack_int;
      end if;
    end if;
  end process;
  rd_req_int <= (wb_en and not wb_i.we) and not wb_rip;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_wip <= '0';
      else
        wb_wip <= (wb_wip or (wb_en and wb_i.we)) and not wr_ack_int;
      end if;
    end if;
  end process;
  wr_req_int <= (wb_en and wb_i.we) and not wb_wip;

  ack_int <= rd_ack_int or wr_ack_int;
  wb_o.ack <= ack_int;
  wb_o.stall <= not ack_int and wb_en;
  wb_o.rty <= '0';
  wb_o.err <= '0';

  -- pipelining for wr-in+rd-out
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        rd_ack_int <= '0';
        wb_o.dat <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_adr_d0 <= "000000";
        wr_dat_d0 <= "00000000000000000000000000000000";
      else
        rd_ack_int <= rd_ack_d0;
        wb_o.dat <= rd_dat_d0;
        wr_req_d0 <= wr_req_int;
        wr_adr_d0 <= adr_int;
        wr_dat_d0 <= wb_i.dat;
      end if;
    end if;
  end process;

  -- Register RESET
  wrc_cpu_csr_regs_o.RESET <= RESET_reg;
  RESET_wack <= RESET_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        RESET_reg <= "00000000";
      else
        if RESET_wreq = '1' then
          RESET_reg <= wr_dat_d0(7 downto 0);
        end if;
      end if;
    end if;
  end process;

  -- Register UADDR
  wrc_cpu_csr_regs_o.UADDR <= UADDR_reg;
  UADDR_wack <= UADDR_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        UADDR_reg <= "00000000000000000000000000000000";
      else
        if UADDR_wreq = '1' then
          UADDR_reg <= wr_dat_d0;
        end if;
      end if;
    end if;
  end process;

  -- Register UDATA
  wrc_cpu_csr_regs_o.UDATA <= wr_dat_d0;
  wrc_cpu_csr_regs_o.UDATA_wr <= UDATA_wreq;

  -- Register DBG_STATUS

  -- Register DBG_FORCE
  wrc_cpu_csr_regs_o.DBG_FORCE <= DBG_FORCE_reg;
  DBG_FORCE_wack <= DBG_FORCE_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        DBG_FORCE_reg <= "00000000";
      else
        if DBG_FORCE_wreq = '1' then
          DBG_FORCE_reg <= wr_dat_d0(7 downto 0);
        end if;
      end if;
    end if;
  end process;

  -- Register DBG_INSN_READY

  -- Register DBG_CORE0_INSN
  wrc_cpu_csr_regs_o.DBG_CORE0_INSN <= DBG_CORE0_INSN_reg;
  DBG_CORE0_INSN_wack <= DBG_CORE0_INSN_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        DBG_CORE0_INSN_reg <= "00000000000000000000000000000000";
        DBG_CORE0_INSN_wstrb <= '0';
      else
        if DBG_CORE0_INSN_wreq = '1' then
          DBG_CORE0_INSN_reg <= wr_dat_d0;
        end if;
        DBG_CORE0_INSN_wstrb <= DBG_CORE0_INSN_wreq;
      end if;
    end if;
  end process;
  wrc_cpu_csr_regs_o.DBG_CORE0_INSN_wr <= DBG_CORE0_INSN_wstrb;

  -- Register DBG_CORE0_MBX
  wrc_cpu_csr_regs_o.DBG_CORE0_MBX <= wr_dat_d0;
  wrc_cpu_csr_regs_o.DBG_CORE0_MBX_wr <= DBG_CORE0_MBX_wreq;

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0, RESET_wack, UADDR_wack, DBG_FORCE_wack,
           DBG_CORE0_INSN_wack) begin
    RESET_wreq <= '0';
    UADDR_wreq <= '0';
    UDATA_wreq <= '0';
    DBG_FORCE_wreq <= '0';
    DBG_CORE0_INSN_wreq <= '0';
    DBG_CORE0_MBX_wreq <= '0';
    case wr_adr_d0(7 downto 2) is
    when "000000" =>
      -- Reg RESET
      RESET_wreq <= wr_req_d0;
      wr_ack_int <= RESET_wack;
    when "000001" =>
      -- Reg UADDR
      UADDR_wreq <= wr_req_d0;
      wr_ack_int <= UADDR_wack;
    when "000010" =>
      -- Reg UDATA
      UDATA_wreq <= wr_req_d0;
      wr_ack_int <= wr_req_d0;
    when "100000" =>
      -- Reg DBG_STATUS
      wr_ack_int <= wr_req_d0;
    when "100001" =>
      -- Reg DBG_FORCE
      DBG_FORCE_wreq <= wr_req_d0;
      wr_ack_int <= DBG_FORCE_wack;
    when "100010" =>
      -- Reg DBG_INSN_READY
      wr_ack_int <= wr_req_d0;
    when "100011" =>
      -- Reg DBG_CORE0_INSN
      DBG_CORE0_INSN_wreq <= wr_req_d0;
      wr_ack_int <= DBG_CORE0_INSN_wack;
    when "100100" =>
      -- Reg DBG_CORE0_MBX
      DBG_CORE0_MBX_wreq <= wr_req_d0;
      wr_ack_int <= wr_req_d0;
    when others =>
      wr_ack_int <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (adr_int, rd_req_int, RESET_reg, UADDR_reg, wrc_cpu_csr_regs_i.UDATA,
           wrc_cpu_csr_regs_i.DBG_STATUS, DBG_FORCE_reg,
           wrc_cpu_csr_regs_i.DBG_INSN_READY, DBG_CORE0_INSN_reg,
           wrc_cpu_csr_regs_i.DBG_CORE0_MBX) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    case adr_int(7 downto 2) is
    when "000000" =>
      -- Reg RESET
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(7 downto 0) <= RESET_reg;
      rd_dat_d0(31 downto 8) <= (others => '0');
    when "000001" =>
      -- Reg UADDR
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= UADDR_reg;
    when "000010" =>
      -- Reg UDATA
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= wrc_cpu_csr_regs_i.UDATA;
    when "100000" =>
      -- Reg DBG_STATUS
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(7 downto 0) <= wrc_cpu_csr_regs_i.DBG_STATUS;
      rd_dat_d0(31 downto 8) <= (others => '0');
    when "100001" =>
      -- Reg DBG_FORCE
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(7 downto 0) <= DBG_FORCE_reg;
      rd_dat_d0(31 downto 8) <= (others => '0');
    when "100010" =>
      -- Reg DBG_INSN_READY
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(7 downto 0) <= wrc_cpu_csr_regs_i.DBG_INSN_READY;
      rd_dat_d0(31 downto 8) <= (others => '0');
    when "100011" =>
      -- Reg DBG_CORE0_INSN
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= DBG_CORE0_INSN_reg;
    when "100100" =>
      -- Reg DBG_CORE0_MBX
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= wrc_cpu_csr_regs_i.DBG_CORE0_MBX;
    when others =>
      rd_ack_d0 <= rd_req_int;
    end case;
  end process;
end syn;
