-- Do not edit.  Generated by cheby 1.7.dev0 using these options:
--  -i wrc_devices_map.cheby --header=commit --gen-hdl wrc_devices_map.vhd


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;

entity wrc_devices_map is
  port (
    rst_n_i              : in    std_logic;
    clk_i                : in    std_logic;
    wb_i                 : in    t_wishbone_slave_in;
    wb_o                 : out   t_wishbone_slave_out;

    -- WB bus minic
    minic_i              : in    t_wishbone_master_in;
    minic_o              : out   t_wishbone_master_out;

    -- WB bus endpoint
    endpoint_i           : in    t_wishbone_master_in;
    endpoint_o           : out   t_wishbone_master_out;

    -- WB bus softpll
    softpll_i            : in    t_wishbone_master_in;
    softpll_o            : out   t_wishbone_master_out;

    -- WB bus ppsgen
    ppsgen_i             : in    t_wishbone_master_in;
    ppsgen_o             : out   t_wishbone_master_out;

    -- WB bus syscon
    syscon_i             : in    t_wishbone_master_in;
    syscon_o             : out   t_wishbone_master_out;

    -- WB bus uart
    uart_i               : in    t_wishbone_master_in;
    uart_o               : out   t_wishbone_master_out;

    -- WB bus vuart
    vuart_i              : in    t_wishbone_master_in;
    vuart_o              : out   t_wishbone_master_out;

    -- WB bus onewire
    onewire_i            : in    t_wishbone_master_in;
    onewire_o            : out   t_wishbone_master_out;

    -- WB bus timing
    timing_i             : in    t_wishbone_master_in;
    timing_o             : out   t_wishbone_master_out;

    -- WB bus wdiag
    wdiag_i              : in    t_wishbone_master_in;
    wdiag_o              : out   t_wishbone_master_out;

    -- WB bus freqmon
    freqmon_i            : in    t_wishbone_master_in;
    freqmon_o            : out   t_wishbone_master_out;

    -- WB bus aux
    aux_i                : in    t_wishbone_master_in;
    aux_o                : out   t_wishbone_master_out
  );
end wrc_devices_map;

architecture syn of wrc_devices_map is
  signal wr_sel                         : std_logic_vector(31 downto 0);
  signal adr_int                        : std_logic_vector(15 downto 2);
  signal rd_req_int                     : std_logic;
  signal wr_req_int                     : std_logic;
  signal rd_ack_int                     : std_logic;
  signal wr_ack_int                     : std_logic;
  signal wb_en                          : std_logic;
  signal ack_int                        : std_logic;
  signal wb_rip                         : std_logic;
  signal wb_wip                         : std_logic;
  signal minic_re                       : std_logic;
  signal minic_we                       : std_logic;
  signal minic_wt                       : std_logic;
  signal minic_rt                       : std_logic;
  signal minic_tr                       : std_logic;
  signal minic_wack                     : std_logic;
  signal minic_rack                     : std_logic;
  signal endpoint_re                    : std_logic;
  signal endpoint_we                    : std_logic;
  signal endpoint_wt                    : std_logic;
  signal endpoint_rt                    : std_logic;
  signal endpoint_tr                    : std_logic;
  signal endpoint_wack                  : std_logic;
  signal endpoint_rack                  : std_logic;
  signal softpll_re                     : std_logic;
  signal softpll_we                     : std_logic;
  signal softpll_wt                     : std_logic;
  signal softpll_rt                     : std_logic;
  signal softpll_tr                     : std_logic;
  signal softpll_wack                   : std_logic;
  signal softpll_rack                   : std_logic;
  signal ppsgen_re                      : std_logic;
  signal ppsgen_we                      : std_logic;
  signal ppsgen_wt                      : std_logic;
  signal ppsgen_rt                      : std_logic;
  signal ppsgen_tr                      : std_logic;
  signal ppsgen_wack                    : std_logic;
  signal ppsgen_rack                    : std_logic;
  signal syscon_re                      : std_logic;
  signal syscon_we                      : std_logic;
  signal syscon_wt                      : std_logic;
  signal syscon_rt                      : std_logic;
  signal syscon_tr                      : std_logic;
  signal syscon_wack                    : std_logic;
  signal syscon_rack                    : std_logic;
  signal uart_re                        : std_logic;
  signal uart_we                        : std_logic;
  signal uart_wt                        : std_logic;
  signal uart_rt                        : std_logic;
  signal uart_tr                        : std_logic;
  signal uart_wack                      : std_logic;
  signal uart_rack                      : std_logic;
  signal vuart_re                       : std_logic;
  signal vuart_we                       : std_logic;
  signal vuart_wt                       : std_logic;
  signal vuart_rt                       : std_logic;
  signal vuart_tr                       : std_logic;
  signal vuart_wack                     : std_logic;
  signal vuart_rack                     : std_logic;
  signal onewire_re                     : std_logic;
  signal onewire_we                     : std_logic;
  signal onewire_wt                     : std_logic;
  signal onewire_rt                     : std_logic;
  signal onewire_tr                     : std_logic;
  signal onewire_wack                   : std_logic;
  signal onewire_rack                   : std_logic;
  signal timing_re                      : std_logic;
  signal timing_we                      : std_logic;
  signal timing_wt                      : std_logic;
  signal timing_rt                      : std_logic;
  signal timing_tr                      : std_logic;
  signal timing_wack                    : std_logic;
  signal timing_rack                    : std_logic;
  signal wdiag_re                       : std_logic;
  signal wdiag_we                       : std_logic;
  signal wdiag_wt                       : std_logic;
  signal wdiag_rt                       : std_logic;
  signal wdiag_tr                       : std_logic;
  signal wdiag_wack                     : std_logic;
  signal wdiag_rack                     : std_logic;
  signal freqmon_re                     : std_logic;
  signal freqmon_we                     : std_logic;
  signal freqmon_wt                     : std_logic;
  signal freqmon_rt                     : std_logic;
  signal freqmon_tr                     : std_logic;
  signal freqmon_wack                   : std_logic;
  signal freqmon_rack                   : std_logic;
  signal aux_re                         : std_logic;
  signal aux_we                         : std_logic;
  signal aux_wt                         : std_logic;
  signal aux_rt                         : std_logic;
  signal aux_tr                         : std_logic;
  signal aux_wack                       : std_logic;
  signal aux_rack                       : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(15 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_sel_d0                      : std_logic_vector(31 downto 0);
begin

  -- WB decode signals
  process (wb_i.sel) begin
    wr_sel(7 downto 0) <= (others => wb_i.sel(0));
    wr_sel(15 downto 8) <= (others => wb_i.sel(1));
    wr_sel(23 downto 16) <= (others => wb_i.sel(2));
    wr_sel(31 downto 24) <= (others => wb_i.sel(3));
  end process;
  adr_int <= wb_i.adr(15 downto 2);
  wb_en <= wb_i.cyc and wb_i.stb;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_rip <= '0';
      else
        wb_rip <= (wb_rip or (wb_en and not wb_i.we)) and not rd_ack_int;
      end if;
    end if;
  end process;
  rd_req_int <= (wb_en and not wb_i.we) and not wb_rip;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_wip <= '0';
      else
        wb_wip <= (wb_wip or (wb_en and wb_i.we)) and not wr_ack_int;
      end if;
    end if;
  end process;
  wr_req_int <= (wb_en and wb_i.we) and not wb_wip;

  ack_int <= rd_ack_int or wr_ack_int;
  wb_o.ack <= ack_int;
  wb_o.stall <= not ack_int and wb_en;
  wb_o.rty <= '0';
  wb_o.err <= '0';

  -- pipelining for wr-in+rd-out
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        rd_ack_int <= '0';
        wb_o.dat <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_adr_d0 <= "00000000000000";
        wr_dat_d0 <= "00000000000000000000000000000000";
        wr_sel_d0 <= "00000000000000000000000000000000";
      else
        rd_ack_int <= rd_ack_d0;
        wb_o.dat <= rd_dat_d0;
        wr_req_d0 <= wr_req_int;
        wr_adr_d0 <= adr_int;
        wr_dat_d0 <= wb_i.dat;
        wr_sel_d0 <= wr_sel;
      end if;
    end if;
  end process;

  -- Interface minic
  minic_tr <= minic_wt or minic_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        minic_rt <= '0';
        minic_wt <= '0';
      else
        minic_rt <= (minic_rt or minic_re) and not minic_rack;
        minic_wt <= (minic_wt or minic_we) and not minic_wack;
      end if;
    end if;
  end process;
  minic_o.cyc <= minic_tr;
  minic_o.stb <= minic_tr;
  minic_wack <= minic_i.ack and minic_wt;
  minic_rack <= minic_i.ack and minic_rt;
  minic_o.adr <= ((23 downto 0 => '0') & adr_int(7 downto 2)) & (1 downto 0 => '0');
  process (wr_sel_d0) begin
    minic_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      minic_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      minic_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      minic_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      minic_o.sel(3) <= '1';
    end if;
  end process;
  minic_o.we <= minic_wt;
  minic_o.dat <= wr_dat_d0;

  -- Interface endpoint
  endpoint_tr <= endpoint_wt or endpoint_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        endpoint_rt <= '0';
        endpoint_wt <= '0';
      else
        endpoint_rt <= (endpoint_rt or endpoint_re) and not endpoint_rack;
        endpoint_wt <= (endpoint_wt or endpoint_we) and not endpoint_wack;
      end if;
    end if;
  end process;
  endpoint_o.cyc <= endpoint_tr;
  endpoint_o.stb <= endpoint_tr;
  endpoint_wack <= endpoint_i.ack and endpoint_wt;
  endpoint_rack <= endpoint_i.ack and endpoint_rt;
  endpoint_o.adr <= ((23 downto 0 => '0') & adr_int(7 downto 2)) & (1 downto 0 => '0');
  process (wr_sel_d0) begin
    endpoint_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      endpoint_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      endpoint_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      endpoint_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      endpoint_o.sel(3) <= '1';
    end if;
  end process;
  endpoint_o.we <= endpoint_wt;
  endpoint_o.dat <= wr_dat_d0;

  -- Interface softpll
  softpll_tr <= softpll_wt or softpll_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        softpll_rt <= '0';
        softpll_wt <= '0';
      else
        softpll_rt <= (softpll_rt or softpll_re) and not softpll_rack;
        softpll_wt <= (softpll_wt or softpll_we) and not softpll_wack;
      end if;
    end if;
  end process;
  softpll_o.cyc <= softpll_tr;
  softpll_o.stb <= softpll_tr;
  softpll_wack <= softpll_i.ack and softpll_wt;
  softpll_rack <= softpll_i.ack and softpll_rt;
  softpll_o.adr <= ((23 downto 0 => '0') & adr_int(7 downto 2)) & (1 downto 0 => '0');
  process (wr_sel_d0) begin
    softpll_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      softpll_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      softpll_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      softpll_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      softpll_o.sel(3) <= '1';
    end if;
  end process;
  softpll_o.we <= softpll_wt;
  softpll_o.dat <= wr_dat_d0;

  -- Interface ppsgen
  ppsgen_tr <= ppsgen_wt or ppsgen_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        ppsgen_rt <= '0';
        ppsgen_wt <= '0';
      else
        ppsgen_rt <= (ppsgen_rt or ppsgen_re) and not ppsgen_rack;
        ppsgen_wt <= (ppsgen_wt or ppsgen_we) and not ppsgen_wack;
      end if;
    end if;
  end process;
  ppsgen_o.cyc <= ppsgen_tr;
  ppsgen_o.stb <= ppsgen_tr;
  ppsgen_wack <= ppsgen_i.ack and ppsgen_wt;
  ppsgen_rack <= ppsgen_i.ack and ppsgen_rt;
  ppsgen_o.adr <= ((23 downto 0 => '0') & adr_int(7 downto 2)) & (1 downto 0 => '0');
  process (wr_sel_d0) begin
    ppsgen_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      ppsgen_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      ppsgen_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      ppsgen_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      ppsgen_o.sel(3) <= '1';
    end if;
  end process;
  ppsgen_o.we <= ppsgen_wt;
  ppsgen_o.dat <= wr_dat_d0;

  -- Interface syscon
  syscon_tr <= syscon_wt or syscon_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        syscon_rt <= '0';
        syscon_wt <= '0';
      else
        syscon_rt <= (syscon_rt or syscon_re) and not syscon_rack;
        syscon_wt <= (syscon_wt or syscon_we) and not syscon_wack;
      end if;
    end if;
  end process;
  syscon_o.cyc <= syscon_tr;
  syscon_o.stb <= syscon_tr;
  syscon_wack <= syscon_i.ack and syscon_wt;
  syscon_rack <= syscon_i.ack and syscon_rt;
  syscon_o.adr <= ((23 downto 0 => '0') & adr_int(7 downto 2)) & (1 downto 0 => '0');
  process (wr_sel_d0) begin
    syscon_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      syscon_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      syscon_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      syscon_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      syscon_o.sel(3) <= '1';
    end if;
  end process;
  syscon_o.we <= syscon_wt;
  syscon_o.dat <= wr_dat_d0;

  -- Interface uart
  uart_tr <= uart_wt or uart_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        uart_rt <= '0';
        uart_wt <= '0';
      else
        uart_rt <= (uart_rt or uart_re) and not uart_rack;
        uart_wt <= (uart_wt or uart_we) and not uart_wack;
      end if;
    end if;
  end process;
  uart_o.cyc <= uart_tr;
  uart_o.stb <= uart_tr;
  uart_wack <= uart_i.ack and uart_wt;
  uart_rack <= uart_i.ack and uart_rt;
  uart_o.adr <= ((24 downto 0 => '0') & adr_int(6 downto 2)) & (1 downto 0 => '0');
  process (wr_sel_d0) begin
    uart_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      uart_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      uart_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      uart_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      uart_o.sel(3) <= '1';
    end if;
  end process;
  uart_o.we <= uart_wt;
  uart_o.dat <= wr_dat_d0;

  -- Interface vuart
  vuart_tr <= vuart_wt or vuart_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        vuart_rt <= '0';
        vuart_wt <= '0';
      else
        vuart_rt <= (vuart_rt or vuart_re) and not vuart_rack;
        vuart_wt <= (vuart_wt or vuart_we) and not vuart_wack;
      end if;
    end if;
  end process;
  vuart_o.cyc <= vuart_tr;
  vuart_o.stb <= vuart_tr;
  vuart_wack <= vuart_i.ack and vuart_wt;
  vuart_rack <= vuart_i.ack and vuart_rt;
  vuart_o.adr <= ((24 downto 0 => '0') & adr_int(6 downto 2)) & (1 downto 0 => '0');
  process (wr_sel_d0) begin
    vuart_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      vuart_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      vuart_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      vuart_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      vuart_o.sel(3) <= '1';
    end if;
  end process;
  vuart_o.we <= vuart_wt;
  vuart_o.dat <= wr_dat_d0;

  -- Interface onewire
  onewire_tr <= onewire_wt or onewire_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        onewire_rt <= '0';
        onewire_wt <= '0';
      else
        onewire_rt <= (onewire_rt or onewire_re) and not onewire_rack;
        onewire_wt <= (onewire_wt or onewire_we) and not onewire_wack;
      end if;
    end if;
  end process;
  onewire_o.cyc <= onewire_tr;
  onewire_o.stb <= onewire_tr;
  onewire_wack <= onewire_i.ack and onewire_wt;
  onewire_rack <= onewire_i.ack and onewire_rt;
  onewire_o.adr <= ((23 downto 0 => '0') & adr_int(7 downto 2)) & (1 downto 0 => '0');
  process (wr_sel_d0) begin
    onewire_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      onewire_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      onewire_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      onewire_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      onewire_o.sel(3) <= '1';
    end if;
  end process;
  onewire_o.we <= onewire_wt;
  onewire_o.dat <= wr_dat_d0;

  -- Interface timing
  timing_tr <= timing_wt or timing_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        timing_rt <= '0';
        timing_wt <= '0';
      else
        timing_rt <= (timing_rt or timing_re) and not timing_rack;
        timing_wt <= (timing_wt or timing_we) and not timing_wack;
      end if;
    end if;
  end process;
  timing_o.cyc <= timing_tr;
  timing_o.stb <= timing_tr;
  timing_wack <= timing_i.ack and timing_wt;
  timing_rack <= timing_i.ack and timing_rt;
  timing_o.adr <= ((23 downto 0 => '0') & adr_int(7 downto 2)) & (1 downto 0 => '0');
  process (wr_sel_d0) begin
    timing_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      timing_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      timing_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      timing_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      timing_o.sel(3) <= '1';
    end if;
  end process;
  timing_o.we <= timing_wt;
  timing_o.dat <= wr_dat_d0;

  -- Interface wdiag
  wdiag_tr <= wdiag_wt or wdiag_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wdiag_rt <= '0';
        wdiag_wt <= '0';
      else
        wdiag_rt <= (wdiag_rt or wdiag_re) and not wdiag_rack;
        wdiag_wt <= (wdiag_wt or wdiag_we) and not wdiag_wack;
      end if;
    end if;
  end process;
  wdiag_o.cyc <= wdiag_tr;
  wdiag_o.stb <= wdiag_tr;
  wdiag_wack <= wdiag_i.ack and wdiag_wt;
  wdiag_rack <= wdiag_i.ack and wdiag_rt;
  wdiag_o.adr <= ((23 downto 0 => '0') & adr_int(7 downto 2)) & (1 downto 0 => '0');
  process (wr_sel_d0) begin
    wdiag_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      wdiag_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      wdiag_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      wdiag_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      wdiag_o.sel(3) <= '1';
    end if;
  end process;
  wdiag_o.we <= wdiag_wt;
  wdiag_o.dat <= wr_dat_d0;

  -- Interface freqmon
  freqmon_tr <= freqmon_wt or freqmon_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        freqmon_rt <= '0';
        freqmon_wt <= '0';
      else
        freqmon_rt <= (freqmon_rt or freqmon_re) and not freqmon_rack;
        freqmon_wt <= (freqmon_wt or freqmon_we) and not freqmon_wack;
      end if;
    end if;
  end process;
  freqmon_o.cyc <= freqmon_tr;
  freqmon_o.stb <= freqmon_tr;
  freqmon_wack <= freqmon_i.ack and freqmon_wt;
  freqmon_rack <= freqmon_i.ack and freqmon_rt;
  freqmon_o.adr <= ((23 downto 0 => '0') & adr_int(7 downto 2)) & (1 downto 0 => '0');
  process (wr_sel_d0) begin
    freqmon_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      freqmon_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      freqmon_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      freqmon_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      freqmon_o.sel(3) <= '1';
    end if;
  end process;
  freqmon_o.we <= freqmon_wt;
  freqmon_o.dat <= wr_dat_d0;

  -- Interface aux
  aux_tr <= aux_wt or aux_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        aux_rt <= '0';
        aux_wt <= '0';
      else
        aux_rt <= (aux_rt or aux_re) and not aux_rack;
        aux_wt <= (aux_wt or aux_we) and not aux_wack;
      end if;
    end if;
  end process;
  aux_o.cyc <= aux_tr;
  aux_o.stb <= aux_tr;
  aux_wack <= aux_i.ack and aux_wt;
  aux_rack <= aux_i.ack and aux_rt;
  aux_o.adr <= ((16 downto 0 => '0') & adr_int(14 downto 2)) & (1 downto 0 => '0');
  process (wr_sel_d0) begin
    aux_o.sel <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      aux_o.sel(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      aux_o.sel(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      aux_o.sel(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      aux_o.sel(3) <= '1';
    end if;
  end process;
  aux_o.we <= aux_wt;
  aux_o.dat <= wr_dat_d0;

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0, minic_wack, endpoint_wack, softpll_wack,
           ppsgen_wack, syscon_wack, uart_wack, vuart_wack, onewire_wack,
           timing_wack, wdiag_wack, freqmon_wack, aux_wack) begin
    minic_we <= '0';
    endpoint_we <= '0';
    softpll_we <= '0';
    ppsgen_we <= '0';
    syscon_we <= '0';
    uart_we <= '0';
    vuart_we <= '0';
    onewire_we <= '0';
    timing_we <= '0';
    wdiag_we <= '0';
    freqmon_we <= '0';
    aux_we <= '0';
    case wr_adr_d0(15 downto 15) is
    when "0" =>
      case wr_adr_d0(14 downto 8) is
      when "0000000" =>
        -- Submap minic
        minic_we <= wr_req_d0;
        wr_ack_int <= minic_wack;
      when "0000001" =>
        -- Submap endpoint
        endpoint_we <= wr_req_d0;
        wr_ack_int <= endpoint_wack;
      when "0000010" =>
        -- Submap softpll
        softpll_we <= wr_req_d0;
        wr_ack_int <= softpll_wack;
      when "0000011" =>
        -- Submap ppsgen
        ppsgen_we <= wr_req_d0;
        wr_ack_int <= ppsgen_wack;
      when "0000100" =>
        -- Submap syscon
        syscon_we <= wr_req_d0;
        wr_ack_int <= syscon_wack;
      when "0000101" =>
        case wr_adr_d0(7 downto 7) is
        when "0" =>
          -- Submap uart
          uart_we <= wr_req_d0;
          wr_ack_int <= uart_wack;
        when "1" =>
          -- Submap vuart
          vuart_we <= wr_req_d0;
          wr_ack_int <= vuart_wack;
        when others =>
          wr_ack_int <= wr_req_d0;
        end case;
      when "0000110" =>
        -- Submap onewire
        onewire_we <= wr_req_d0;
        wr_ack_int <= onewire_wack;
      when "0000111" =>
        -- Submap timing
        timing_we <= wr_req_d0;
        wr_ack_int <= timing_wack;
      when "0001000" =>
        -- Submap wdiag
        wdiag_we <= wr_req_d0;
        wr_ack_int <= wdiag_wack;
      when "0001010" =>
        -- Submap freqmon
        freqmon_we <= wr_req_d0;
        wr_ack_int <= freqmon_wack;
      when others =>
        wr_ack_int <= wr_req_d0;
      end case;
    when "1" =>
      -- Submap aux
      aux_we <= wr_req_d0;
      wr_ack_int <= aux_wack;
    when others =>
      wr_ack_int <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (adr_int, rd_req_int, minic_i.dat, minic_rack, endpoint_i.dat,
           endpoint_rack, softpll_i.dat, softpll_rack, ppsgen_i.dat, ppsgen_rack,
           syscon_i.dat, syscon_rack, uart_i.dat, uart_rack, vuart_i.dat, vuart_rack,
           onewire_i.dat, onewire_rack, timing_i.dat, timing_rack, wdiag_i.dat,
           wdiag_rack, freqmon_i.dat, freqmon_rack, aux_i.dat, aux_rack) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    minic_re <= '0';
    endpoint_re <= '0';
    softpll_re <= '0';
    ppsgen_re <= '0';
    syscon_re <= '0';
    uart_re <= '0';
    vuart_re <= '0';
    onewire_re <= '0';
    timing_re <= '0';
    wdiag_re <= '0';
    freqmon_re <= '0';
    aux_re <= '0';
    case adr_int(15 downto 15) is
    when "0" =>
      case adr_int(14 downto 8) is
      when "0000000" =>
        -- Submap minic
        minic_re <= rd_req_int;
        rd_dat_d0 <= minic_i.dat;
        rd_ack_d0 <= minic_rack;
      when "0000001" =>
        -- Submap endpoint
        endpoint_re <= rd_req_int;
        rd_dat_d0 <= endpoint_i.dat;
        rd_ack_d0 <= endpoint_rack;
      when "0000010" =>
        -- Submap softpll
        softpll_re <= rd_req_int;
        rd_dat_d0 <= softpll_i.dat;
        rd_ack_d0 <= softpll_rack;
      when "0000011" =>
        -- Submap ppsgen
        ppsgen_re <= rd_req_int;
        rd_dat_d0 <= ppsgen_i.dat;
        rd_ack_d0 <= ppsgen_rack;
      when "0000100" =>
        -- Submap syscon
        syscon_re <= rd_req_int;
        rd_dat_d0 <= syscon_i.dat;
        rd_ack_d0 <= syscon_rack;
      when "0000101" =>
        case adr_int(7 downto 7) is
        when "0" =>
          -- Submap uart
          uart_re <= rd_req_int;
          rd_dat_d0 <= uart_i.dat;
          rd_ack_d0 <= uart_rack;
        when "1" =>
          -- Submap vuart
          vuart_re <= rd_req_int;
          rd_dat_d0 <= vuart_i.dat;
          rd_ack_d0 <= vuart_rack;
        when others =>
          rd_ack_d0 <= rd_req_int;
        end case;
      when "0000110" =>
        -- Submap onewire
        onewire_re <= rd_req_int;
        rd_dat_d0 <= onewire_i.dat;
        rd_ack_d0 <= onewire_rack;
      when "0000111" =>
        -- Submap timing
        timing_re <= rd_req_int;
        rd_dat_d0 <= timing_i.dat;
        rd_ack_d0 <= timing_rack;
      when "0001000" =>
        -- Submap wdiag
        wdiag_re <= rd_req_int;
        rd_dat_d0 <= wdiag_i.dat;
        rd_ack_d0 <= wdiag_rack;
      when "0001010" =>
        -- Submap freqmon
        freqmon_re <= rd_req_int;
        rd_dat_d0 <= freqmon_i.dat;
        rd_ack_d0 <= freqmon_rack;
      when others =>
        rd_ack_d0 <= rd_req_int;
      end case;
    when "1" =>
      -- Submap aux
      aux_re <= rd_req_int;
      rd_dat_d0 <= aux_i.dat;
      rd_ack_d0 <= aux_rack;
    when others =>
      rd_ack_d0 <= rd_req_int;
    end case;
  end process;
end syn;
