-------------------------------------------------------------------------------
-- SPDX-FileCopyrightText: 2026 CERN (home.cern)
--
-- SPDX-License-Identifier: CERN-OHL-W-2.0+
-------------------------------------------------------------------------------
-- Do not edit.  Generated by cheby 1.7.dev0 using these options:
--  -i wrc_syscon_map.cheby --header=commit --gen-hdl wrc_syscon_map.vhd --gen-c wrc_syscon_map.h


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;

package wrc_syscon_map_pkg is
  type t_sysc_regs_master_out is record
    RSTR_TRIG        : std_logic_vector(27 downto 0);
    RSTR_RST         : std_logic;
    RSTR_wr          : std_logic;
    GPSR_fmc_scl     : std_logic;
    GPSR_fmc_sda     : std_logic;
    GPSR_Net_RST     : std_logic;
    GPSR_Btn1        : std_logic;
    GPSR_Btn2        : std_logic;
    GPSR_sfp1_det    : std_logic;
    GPSR_sfp1_scl    : std_logic;
    GPSR_sfp1_sda    : std_logic;
    GPSR_spi_sclk    : std_logic;
    GPSR_spi_ncs     : std_logic;
    GPSR_spi_mosi    : std_logic;
    GPSR_spi_miso    : std_logic;
    GPSR_spi_cs2     : std_logic;
    GPSR_sfp2_det    : std_logic;
    GPSR_sfp2_scl    : std_logic;
    GPSR_sfp2_sda    : std_logic;
    GPSR_wr          : std_logic;
    GPCR_fmc_scl     : std_logic;
    GPCR_fmc_sda     : std_logic;
    GPCR_sfp1_scl    : std_logic;
    GPCR_sfp1_sda    : std_logic;
    GPCR_spi_sclk    : std_logic;
    GPCR_spi_cs      : std_logic;
    GPCR_spi_mosi    : std_logic;
    GPCR_spi_cs2     : std_logic;
    GPCR_sfp2_scl    : std_logic;
    GPCR_sfp2_sda    : std_logic;
    GPCR_wr          : std_logic;
    TCR_ENABLE       : std_logic;
    DIAG_CR_ADR      : std_logic_vector(15 downto 0);
    DIAG_CR_RW       : std_logic;
    DIAG_CR_wr       : std_logic;
    DIAG_DAT         : std_logic_vector(31 downto 0);
    DIAG_DAT_wr      : std_logic;
  end record t_sysc_regs_master_out;
  subtype t_sysc_regs_slave_in is t_sysc_regs_master_out;

  type t_sysc_regs_slave_out is record
    RSTR_TRIG        : std_logic_vector(27 downto 0);
    GPSR_fmc_scl     : std_logic;
    GPSR_fmc_sda     : std_logic;
    GPSR_Net_RST     : std_logic;
    GPSR_Btn1        : std_logic;
    GPSR_Btn2        : std_logic;
    GPSR_sfp1_det    : std_logic;
    GPSR_sfp1_scl    : std_logic;
    GPSR_sfp1_sda    : std_logic;
    GPSR_spi_sclk    : std_logic;
    GPSR_spi_ncs     : std_logic;
    GPSR_spi_mosi    : std_logic;
    GPSR_spi_miso    : std_logic;
    GPSR_spi_cs2     : std_logic;
    GPSR_sfp2_det    : std_logic;
    GPSR_sfp2_scl    : std_logic;
    GPSR_sfp2_sda    : std_logic;
    HWFR_MEMSIZE     : std_logic_vector(3 downto 0);
    HWFR_STORAGE_TYPE : std_logic_vector(1 downto 0);
    HWFR_mapver      : std_logic_vector(3 downto 0);
    HWFR_STORAGE_SEC : std_logic_vector(15 downto 0);
    HWIR_NAME        : std_logic_vector(31 downto 0);
    SDBFS_BADDR      : std_logic_vector(31 downto 0);
    TVR              : std_logic_vector(31 downto 0);
    DIAG_INFO_VER    : std_logic_vector(15 downto 0);
    DIAG_INFO_ID     : std_logic_vector(15 downto 0);
    DIAG_NW_RW       : std_logic_vector(15 downto 0);
    DIAG_NW_RO       : std_logic_vector(15 downto 0);
    DIAG_DAT         : std_logic_vector(31 downto 0);
    HWBLD            : std_logic_vector(31 downto 0);
  end record t_sysc_regs_slave_out;
  subtype t_sysc_regs_master_in is t_sysc_regs_slave_out;

end wrc_syscon_map_pkg;

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;
use work.wrc_syscon_map_pkg.all;

entity wrc_syscon_map is
  port (
    rst_n_i              : in    std_logic;
    clk_i                : in    std_logic;
    wb_i                 : in    t_wishbone_slave_in;
    wb_o                 : out   t_wishbone_slave_out;
    -- Wires and registers
    sysc_regs_i          : in    t_sysc_regs_master_in;
    sysc_regs_o          : out   t_sysc_regs_master_out
  );
end wrc_syscon_map;

architecture syn of wrc_syscon_map is
  signal adr_int                        : std_logic_vector(5 downto 2);
  signal rd_req_int                     : std_logic;
  signal wr_req_int                     : std_logic;
  signal rd_ack_int                     : std_logic;
  signal wr_ack_int                     : std_logic;
  signal wb_en                          : std_logic;
  signal ack_int                        : std_logic;
  signal wb_rip                         : std_logic;
  signal wb_wip                         : std_logic;
  signal RSTR_RST_reg                   : std_logic;
  signal RSTR_wreq                      : std_logic;
  signal RSTR_wack                      : std_logic;
  signal RSTR_wstrb                     : std_logic;
  signal GPSR_wreq                      : std_logic;
  signal GPCR_wreq                      : std_logic;
  signal TCR_ENABLE_reg                 : std_logic;
  signal TCR_wreq                       : std_logic;
  signal TCR_wack                       : std_logic;
  signal DIAG_CR_ADR_reg                : std_logic_vector(15 downto 0);
  signal DIAG_CR_RW_reg                 : std_logic;
  signal DIAG_CR_wreq                   : std_logic;
  signal DIAG_CR_wack                   : std_logic;
  signal DIAG_CR_wstrb                  : std_logic;
  signal DIAG_DAT_wreq                  : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(5 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
begin

  -- WB decode signals
  adr_int <= wb_i.adr(5 downto 2);
  wb_en <= wb_i.cyc and wb_i.stb;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_rip <= '0';
      else
        wb_rip <= (wb_rip or (wb_en and not wb_i.we)) and not rd_ack_int;
      end if;
    end if;
  end process;
  rd_req_int <= (wb_en and not wb_i.we) and not wb_rip;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_wip <= '0';
      else
        wb_wip <= (wb_wip or (wb_en and wb_i.we)) and not wr_ack_int;
      end if;
    end if;
  end process;
  wr_req_int <= (wb_en and wb_i.we) and not wb_wip;

  ack_int <= rd_ack_int or wr_ack_int;
  wb_o.ack <= ack_int;
  wb_o.stall <= not ack_int and wb_en;
  wb_o.rty <= '0';
  wb_o.err <= '0';

  -- pipelining for wr-in+rd-out
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        rd_ack_int <= '0';
        wb_o.dat <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_adr_d0 <= "0000";
        wr_dat_d0 <= "00000000000000000000000000000000";
      else
        rd_ack_int <= rd_ack_d0;
        wb_o.dat <= rd_dat_d0;
        wr_req_d0 <= wr_req_int;
        wr_adr_d0 <= adr_int;
        wr_dat_d0 <= wb_i.dat;
      end if;
    end if;
  end process;

  -- Register RSTR
  sysc_regs_o.RSTR_TRIG <= wr_dat_d0(27 downto 0);
  sysc_regs_o.RSTR_RST <= RSTR_RST_reg;
  RSTR_wack <= RSTR_wreq;
  RSTR_wstrb <= RSTR_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        RSTR_RST_reg <= '0';
      else
        if RSTR_wreq = '1' then
          RSTR_RST_reg <= wr_dat_d0(28);
        end if;
      end if;
    end if;
  end process;
  sysc_regs_o.RSTR_wr <= RSTR_wstrb;

  -- Register GPSR
  sysc_regs_o.GPSR_fmc_scl <= wr_dat_d0(2);
  sysc_regs_o.GPSR_fmc_sda <= wr_dat_d0(3);
  sysc_regs_o.GPSR_Net_RST <= wr_dat_d0(4);
  sysc_regs_o.GPSR_Btn1 <= wr_dat_d0(5);
  sysc_regs_o.GPSR_Btn2 <= wr_dat_d0(6);
  sysc_regs_o.GPSR_sfp1_det <= wr_dat_d0(7);
  sysc_regs_o.GPSR_sfp1_scl <= wr_dat_d0(8);
  sysc_regs_o.GPSR_sfp1_sda <= wr_dat_d0(9);
  sysc_regs_o.GPSR_spi_sclk <= wr_dat_d0(10);
  sysc_regs_o.GPSR_spi_ncs <= wr_dat_d0(11);
  sysc_regs_o.GPSR_spi_mosi <= wr_dat_d0(12);
  sysc_regs_o.GPSR_spi_miso <= wr_dat_d0(13);
  sysc_regs_o.GPSR_spi_cs2 <= wr_dat_d0(14);
  sysc_regs_o.GPSR_sfp2_det <= wr_dat_d0(16);
  sysc_regs_o.GPSR_sfp2_scl <= wr_dat_d0(17);
  sysc_regs_o.GPSR_sfp2_sda <= wr_dat_d0(18);
  sysc_regs_o.GPSR_wr <= GPSR_wreq;

  -- Register GPCR
  sysc_regs_o.GPCR_fmc_scl <= wr_dat_d0(2);
  sysc_regs_o.GPCR_fmc_sda <= wr_dat_d0(3);
  sysc_regs_o.GPCR_sfp1_scl <= wr_dat_d0(8);
  sysc_regs_o.GPCR_sfp1_sda <= wr_dat_d0(9);
  sysc_regs_o.GPCR_spi_sclk <= wr_dat_d0(10);
  sysc_regs_o.GPCR_spi_cs <= wr_dat_d0(11);
  sysc_regs_o.GPCR_spi_mosi <= wr_dat_d0(12);
  sysc_regs_o.GPCR_spi_cs2 <= wr_dat_d0(14);
  sysc_regs_o.GPCR_sfp2_scl <= wr_dat_d0(17);
  sysc_regs_o.GPCR_sfp2_sda <= wr_dat_d0(18);
  sysc_regs_o.GPCR_wr <= GPCR_wreq;

  -- Register HWFR

  -- Register HWIR

  -- Register SDBFS

  -- Register TCR
  sysc_regs_o.TCR_ENABLE <= TCR_ENABLE_reg;
  TCR_wack <= TCR_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        TCR_ENABLE_reg <= '0';
      else
        if TCR_wreq = '1' then
          TCR_ENABLE_reg <= wr_dat_d0(31);
        end if;
      end if;
    end if;
  end process;

  -- Register TVR

  -- Register DIAG_INFO

  -- Register DIAG_NW

  -- Register DIAG_CR
  sysc_regs_o.DIAG_CR_ADR <= DIAG_CR_ADR_reg;
  sysc_regs_o.DIAG_CR_RW <= DIAG_CR_RW_reg;
  DIAG_CR_wack <= DIAG_CR_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        DIAG_CR_ADR_reg <= "0000000000000000";
        DIAG_CR_RW_reg <= '0';
        DIAG_CR_wstrb <= '0';
      else
        if DIAG_CR_wreq = '1' then
          DIAG_CR_ADR_reg <= wr_dat_d0(15 downto 0);
          DIAG_CR_RW_reg <= wr_dat_d0(31);
        end if;
        DIAG_CR_wstrb <= DIAG_CR_wreq;
      end if;
    end if;
  end process;
  sysc_regs_o.DIAG_CR_wr <= DIAG_CR_wstrb;

  -- Register DIAG_DAT
  sysc_regs_o.DIAG_DAT <= wr_dat_d0;
  sysc_regs_o.DIAG_DAT_wr <= DIAG_DAT_wreq;

  -- Register HWBLD

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0, RSTR_wack, TCR_wack, DIAG_CR_wack) begin
    RSTR_wreq <= '0';
    GPSR_wreq <= '0';
    GPCR_wreq <= '0';
    TCR_wreq <= '0';
    DIAG_CR_wreq <= '0';
    DIAG_DAT_wreq <= '0';
    case wr_adr_d0(5 downto 2) is
    when "0000" =>
      -- Reg RSTR
      RSTR_wreq <= wr_req_d0;
      wr_ack_int <= RSTR_wack;
    when "0001" =>
      -- Reg GPSR
      GPSR_wreq <= wr_req_d0;
      wr_ack_int <= wr_req_d0;
    when "0010" =>
      -- Reg GPCR
      GPCR_wreq <= wr_req_d0;
      wr_ack_int <= wr_req_d0;
    when "0011" =>
      -- Reg HWFR
      wr_ack_int <= wr_req_d0;
    when "0100" =>
      -- Reg HWIR
      wr_ack_int <= wr_req_d0;
    when "0101" =>
      -- Reg SDBFS
      wr_ack_int <= wr_req_d0;
    when "0110" =>
      -- Reg TCR
      TCR_wreq <= wr_req_d0;
      wr_ack_int <= TCR_wack;
    when "0111" =>
      -- Reg TVR
      wr_ack_int <= wr_req_d0;
    when "1000" =>
      -- Reg DIAG_INFO
      wr_ack_int <= wr_req_d0;
    when "1001" =>
      -- Reg DIAG_NW
      wr_ack_int <= wr_req_d0;
    when "1010" =>
      -- Reg DIAG_CR
      DIAG_CR_wreq <= wr_req_d0;
      wr_ack_int <= DIAG_CR_wack;
    when "1011" =>
      -- Reg DIAG_DAT
      DIAG_DAT_wreq <= wr_req_d0;
      wr_ack_int <= wr_req_d0;
    when "1100" =>
      -- Reg HWBLD
      wr_ack_int <= wr_req_d0;
    when others =>
      wr_ack_int <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (adr_int, rd_req_int, sysc_regs_i.RSTR_TRIG, RSTR_RST_reg,
           sysc_regs_i.GPSR_fmc_scl, sysc_regs_i.GPSR_fmc_sda,
           sysc_regs_i.GPSR_Net_RST, sysc_regs_i.GPSR_Btn1,
           sysc_regs_i.GPSR_Btn2, sysc_regs_i.GPSR_sfp1_det,
           sysc_regs_i.GPSR_sfp1_scl, sysc_regs_i.GPSR_sfp1_sda,
           sysc_regs_i.GPSR_spi_sclk, sysc_regs_i.GPSR_spi_ncs,
           sysc_regs_i.GPSR_spi_mosi, sysc_regs_i.GPSR_spi_miso,
           sysc_regs_i.GPSR_spi_cs2, sysc_regs_i.GPSR_sfp2_det,
           sysc_regs_i.GPSR_sfp2_scl, sysc_regs_i.GPSR_sfp2_sda,
           sysc_regs_i.HWFR_MEMSIZE, sysc_regs_i.HWFR_STORAGE_TYPE,
           sysc_regs_i.HWFR_mapver, sysc_regs_i.HWFR_STORAGE_SEC,
           sysc_regs_i.HWIR_NAME, sysc_regs_i.SDBFS_BADDR, TCR_ENABLE_reg,
           sysc_regs_i.TVR, sysc_regs_i.DIAG_INFO_VER,
           sysc_regs_i.DIAG_INFO_ID, sysc_regs_i.DIAG_NW_RW,
           sysc_regs_i.DIAG_NW_RO, sysc_regs_i.DIAG_DAT, sysc_regs_i.HWBLD) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    case adr_int(5 downto 2) is
    when "0000" =>
      -- Reg RSTR
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(27 downto 0) <= sysc_regs_i.RSTR_TRIG;
      rd_dat_d0(28) <= RSTR_RST_reg;
      rd_dat_d0(31 downto 29) <= (others => '0');
    when "0001" =>
      -- Reg GPSR
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(1 downto 0) <= (others => '0');
      rd_dat_d0(2) <= sysc_regs_i.GPSR_fmc_scl;
      rd_dat_d0(3) <= sysc_regs_i.GPSR_fmc_sda;
      rd_dat_d0(4) <= sysc_regs_i.GPSR_Net_RST;
      rd_dat_d0(5) <= sysc_regs_i.GPSR_Btn1;
      rd_dat_d0(6) <= sysc_regs_i.GPSR_Btn2;
      rd_dat_d0(7) <= sysc_regs_i.GPSR_sfp1_det;
      rd_dat_d0(8) <= sysc_regs_i.GPSR_sfp1_scl;
      rd_dat_d0(9) <= sysc_regs_i.GPSR_sfp1_sda;
      rd_dat_d0(10) <= sysc_regs_i.GPSR_spi_sclk;
      rd_dat_d0(11) <= sysc_regs_i.GPSR_spi_ncs;
      rd_dat_d0(12) <= sysc_regs_i.GPSR_spi_mosi;
      rd_dat_d0(13) <= sysc_regs_i.GPSR_spi_miso;
      rd_dat_d0(14) <= sysc_regs_i.GPSR_spi_cs2;
      rd_dat_d0(15) <= '0';
      rd_dat_d0(16) <= sysc_regs_i.GPSR_sfp2_det;
      rd_dat_d0(17) <= sysc_regs_i.GPSR_sfp2_scl;
      rd_dat_d0(18) <= sysc_regs_i.GPSR_sfp2_sda;
      rd_dat_d0(31 downto 19) <= (others => '0');
    when "0010" =>
      -- Reg GPCR
      rd_ack_d0 <= rd_req_int;
    when "0011" =>
      -- Reg HWFR
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(3 downto 0) <= sysc_regs_i.HWFR_MEMSIZE;
      rd_dat_d0(7 downto 4) <= (others => '0');
      rd_dat_d0(9 downto 8) <= sysc_regs_i.HWFR_STORAGE_TYPE;
      rd_dat_d0(11 downto 10) <= (others => '0');
      rd_dat_d0(15 downto 12) <= sysc_regs_i.HWFR_mapver;
      rd_dat_d0(31 downto 16) <= sysc_regs_i.HWFR_STORAGE_SEC;
    when "0100" =>
      -- Reg HWIR
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= sysc_regs_i.HWIR_NAME;
    when "0101" =>
      -- Reg SDBFS
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= sysc_regs_i.SDBFS_BADDR;
    when "0110" =>
      -- Reg TCR
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(30 downto 0) <= (others => '0');
      rd_dat_d0(31) <= TCR_ENABLE_reg;
    when "0111" =>
      -- Reg TVR
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= sysc_regs_i.TVR;
    when "1000" =>
      -- Reg DIAG_INFO
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(15 downto 0) <= sysc_regs_i.DIAG_INFO_VER;
      rd_dat_d0(31 downto 16) <= sysc_regs_i.DIAG_INFO_ID;
    when "1001" =>
      -- Reg DIAG_NW
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(15 downto 0) <= sysc_regs_i.DIAG_NW_RW;
      rd_dat_d0(31 downto 16) <= sysc_regs_i.DIAG_NW_RO;
    when "1010" =>
      -- Reg DIAG_CR
      rd_ack_d0 <= rd_req_int;
    when "1011" =>
      -- Reg DIAG_DAT
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= sysc_regs_i.DIAG_DAT;
    when "1100" =>
      -- Reg HWBLD
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= sysc_regs_i.HWBLD;
    when others =>
      rd_ack_d0 <= rd_req_int;
    end case;
  end process;
end syn;
