-------------------------------------------------------------------------------
-- SPDX-FileCopyrightText: 2025 CERN (home.cern)
--
-- SPDX-License-Identifier: CERN-OHL-W-2.0+
-------------------------------------------------------------------------------
-- Do not edit.  Generated by cheby 1.6.dev0 using these options:
--  -i timecode_regs.cheby --gen-hdl timecode_regs.vhd
-- Generated on Thu Jan 09 09:04:01 2025 by harvey


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package timecode_regs_pkg is
  type t_timecode_regs_master_out is record
    CR_valid         : std_logic;
    CR_serdes_ip_sel : std_logic_vector(1 downto 0);
    NEXT_UTC_MDHMS_second : std_logic_vector(5 downto 0);
    NEXT_UTC_MDHMS_minute : std_logic_vector(5 downto 0);
    NEXT_UTC_MDHMS_utc_hr : std_logic_vector(5 downto 0);
    NEXT_UTC_MDHMS_utc_day : std_logic_vector(4 downto 0);
    NEXT_UTC_MDHMS_utc_mon : std_logic_vector(3 downto 0);
    NEXT_UTC_Y_utc_year : std_logic_vector(11 downto 0);
    NEXT_UTC_Y_utc_diy : std_logic_vector(8 downto 0);
    NEXT_UTC_SBS_utc_sbs : std_logic_vector(16 downto 0);
    NEXT_LEAP_SEC_ls_value : std_logic_vector(7 downto 0);
    NEXT_LEAP_SEC_ls_flag59 : std_logic;
    NEXT_LEAP_SEC_ls_flag61 : std_logic;
    NEXT_LEAP_SEC_ls_valid : std_logic;
  end record t_timecode_regs_master_out;
  subtype t_timecode_regs_slave_in is t_timecode_regs_master_out;

  type t_timecode_regs_slave_out is record
    SR_valid         : std_logic;
    SR_auxclk_enabled : std_logic;
    SR_irig_enabled  : std_logic;
    SR_nmea_enabled  : std_logic;
    CURR_UTC_MDHMS_second : std_logic_vector(5 downto 0);
    CURR_UTC_MDHMS_minute : std_logic_vector(5 downto 0);
    CURR_UTC_MDHMS_utc_hr : std_logic_vector(5 downto 0);
    CURR_UTC_MDHMS_utc_day : std_logic_vector(4 downto 0);
    CURR_UTC_MDHMS_utc_mon : std_logic_vector(3 downto 0);
    CURR_UTC_Y_utc_year : std_logic_vector(11 downto 0);
    CURR_UTC_Y_utc_diy : std_logic_vector(8 downto 0);
    CURR_UTC_SBS_utc_sbs : std_logic_vector(16 downto 0);
    CURR_LEAP_SEC_ls_value : std_logic_vector(7 downto 0);
    CURR_LEAP_SEC_ls_flag59 : std_logic;
    CURR_LEAP_SEC_ls_flag61 : std_logic;
    CURR_LEAP_SEC_ls_valid : std_logic;
  end record t_timecode_regs_slave_out;
  subtype t_timecode_regs_master_in is t_timecode_regs_slave_out;

end timecode_regs_pkg;

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.timecode_regs_pkg.all;

entity timecode_regs is
  port (
    rst_n_i              : in    std_logic;
    clk_i                : in    std_logic;
    wb_cyc_i             : in    std_logic;
    wb_stb_i             : in    std_logic;
    wb_adr_i             : in    std_logic_vector(6 downto 2);
    wb_sel_i             : in    std_logic_vector(3 downto 0);
    wb_we_i              : in    std_logic;
    wb_dat_i             : in    std_logic_vector(31 downto 0);
    wb_ack_o             : out   std_logic;
    wb_err_o             : out   std_logic;
    wb_rty_o             : out   std_logic;
    wb_stall_o           : out   std_logic;
    wb_dat_o             : out   std_logic_vector(31 downto 0);
    -- Wires and registers
    timecode_regs_i      : in    t_timecode_regs_master_in;
    timecode_regs_o      : out   t_timecode_regs_master_out;

    -- auxclk generator interface submap
    auxclk_cyc_o         : out   std_logic;
    auxclk_stb_o         : out   std_logic;
    auxclk_adr_o         : out   std_logic_vector(2 downto 2);
    auxclk_sel_o         : out   std_logic_vector(3 downto 0);
    auxclk_we_o          : out   std_logic;
    auxclk_dat_o         : out   std_logic_vector(31 downto 0);
    auxclk_ack_i         : in    std_logic;
    auxclk_err_i         : in    std_logic;
    auxclk_rty_i         : in    std_logic;
    auxclk_stall_i       : in    std_logic;
    auxclk_dat_i         : in    std_logic_vector(31 downto 0);

    -- nmea master interface submap
    nmea_cyc_o           : out   std_logic;
    nmea_stb_o           : out   std_logic;
    nmea_adr_o           : out   std_logic_vector(3 downto 2);
    nmea_sel_o           : out   std_logic_vector(3 downto 0);
    nmea_we_o            : out   std_logic;
    nmea_dat_o           : out   std_logic_vector(31 downto 0);
    nmea_ack_i           : in    std_logic;
    nmea_err_i           : in    std_logic;
    nmea_rty_i           : in    std_logic;
    nmea_stall_i         : in    std_logic;
    nmea_dat_i           : in    std_logic_vector(31 downto 0)
  );
end timecode_regs;

architecture syn of timecode_regs is
  signal wr_sel                         : std_logic_vector(31 downto 0);
  signal rd_req_int                     : std_logic;
  signal wr_req_int                     : std_logic;
  signal rd_ack_int                     : std_logic;
  signal wr_ack_int                     : std_logic;
  signal wb_en                          : std_logic;
  signal ack_int                        : std_logic;
  signal wb_rip                         : std_logic;
  signal wb_wip                         : std_logic;
  signal CR_valid_reg                   : std_logic;
  signal CR_serdes_ip_sel_reg           : std_logic_vector(1 downto 0);
  signal CR_wreq                        : std_logic;
  signal CR_wack                        : std_logic;
  signal NEXT_UTC_MDHMS_second_reg      : std_logic_vector(5 downto 0);
  signal NEXT_UTC_MDHMS_minute_reg      : std_logic_vector(5 downto 0);
  signal NEXT_UTC_MDHMS_utc_hr_reg      : std_logic_vector(5 downto 0);
  signal NEXT_UTC_MDHMS_utc_day_reg     : std_logic_vector(4 downto 0);
  signal NEXT_UTC_MDHMS_utc_mon_reg     : std_logic_vector(3 downto 0);
  signal NEXT_UTC_MDHMS_wreq            : std_logic;
  signal NEXT_UTC_MDHMS_wack            : std_logic;
  signal NEXT_UTC_Y_utc_year_reg        : std_logic_vector(11 downto 0);
  signal NEXT_UTC_Y_utc_diy_reg         : std_logic_vector(8 downto 0);
  signal NEXT_UTC_Y_wreq                : std_logic;
  signal NEXT_UTC_Y_wack                : std_logic;
  signal NEXT_UTC_SBS_utc_sbs_reg       : std_logic_vector(16 downto 0);
  signal NEXT_UTC_SBS_wreq              : std_logic;
  signal NEXT_UTC_SBS_wack              : std_logic;
  signal NEXT_LEAP_SEC_ls_value_reg     : std_logic_vector(7 downto 0);
  signal NEXT_LEAP_SEC_ls_flag59_reg    : std_logic;
  signal NEXT_LEAP_SEC_ls_flag61_reg    : std_logic;
  signal NEXT_LEAP_SEC_ls_valid_reg     : std_logic;
  signal NEXT_LEAP_SEC_wreq             : std_logic;
  signal NEXT_LEAP_SEC_wack             : std_logic;
  signal auxclk_re                      : std_logic;
  signal auxclk_we                      : std_logic;
  signal auxclk_wt                      : std_logic;
  signal auxclk_rt                      : std_logic;
  signal auxclk_tr                      : std_logic;
  signal auxclk_wack                    : std_logic;
  signal auxclk_rack                    : std_logic;
  signal nmea_re                        : std_logic;
  signal nmea_we                        : std_logic;
  signal nmea_wt                        : std_logic;
  signal nmea_rt                        : std_logic;
  signal nmea_tr                        : std_logic;
  signal nmea_wack                      : std_logic;
  signal nmea_rack                      : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(6 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_sel_d0                      : std_logic_vector(31 downto 0);
begin

  -- WB decode signals
  process (wb_sel_i) begin
    wr_sel(7 downto 0) <= (others => wb_sel_i(0));
    wr_sel(15 downto 8) <= (others => wb_sel_i(1));
    wr_sel(23 downto 16) <= (others => wb_sel_i(2));
    wr_sel(31 downto 24) <= (others => wb_sel_i(3));
  end process;
  wb_en <= wb_cyc_i and wb_stb_i;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_rip <= '0';
      else
        wb_rip <= (wb_rip or (wb_en and not wb_we_i)) and not rd_ack_int;
      end if;
    end if;
  end process;
  rd_req_int <= (wb_en and not wb_we_i) and not wb_rip;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_wip <= '0';
      else
        wb_wip <= (wb_wip or (wb_en and wb_we_i)) and not wr_ack_int;
      end if;
    end if;
  end process;
  wr_req_int <= (wb_en and wb_we_i) and not wb_wip;

  ack_int <= rd_ack_int or wr_ack_int;
  wb_ack_o <= ack_int;
  wb_stall_o <= not ack_int and wb_en;
  wb_rty_o <= '0';
  wb_err_o <= '0';

  -- pipelining for wr-in+rd-out
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        rd_ack_int <= '0';
        wb_dat_o <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_adr_d0 <= "00000";
        wr_dat_d0 <= "00000000000000000000000000000000";
        wr_sel_d0 <= "00000000000000000000000000000000";
      else
        rd_ack_int <= rd_ack_d0;
        wb_dat_o <= rd_dat_d0;
        wr_req_d0 <= wr_req_int;
        wr_adr_d0 <= wb_adr_i;
        wr_dat_d0 <= wb_dat_i;
        wr_sel_d0 <= wr_sel;
      end if;
    end if;
  end process;

  -- Register CR
  timecode_regs_o.CR_valid <= CR_valid_reg;
  timecode_regs_o.CR_serdes_ip_sel <= CR_serdes_ip_sel_reg;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        CR_valid_reg <= '0';
        CR_serdes_ip_sel_reg <= "00";
        CR_wack <= '0';
      else
        if CR_wreq = '1' then
          CR_valid_reg <= wr_dat_d0(0);
          CR_serdes_ip_sel_reg <= wr_dat_d0(2 downto 1);
        end if;
        CR_wack <= CR_wreq;
      end if;
    end if;
  end process;

  -- Register SR

  -- Register NEXT_UTC_MDHMS
  timecode_regs_o.NEXT_UTC_MDHMS_second <= NEXT_UTC_MDHMS_second_reg;
  timecode_regs_o.NEXT_UTC_MDHMS_minute <= NEXT_UTC_MDHMS_minute_reg;
  timecode_regs_o.NEXT_UTC_MDHMS_utc_hr <= NEXT_UTC_MDHMS_utc_hr_reg;
  timecode_regs_o.NEXT_UTC_MDHMS_utc_day <= NEXT_UTC_MDHMS_utc_day_reg;
  timecode_regs_o.NEXT_UTC_MDHMS_utc_mon <= NEXT_UTC_MDHMS_utc_mon_reg;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        NEXT_UTC_MDHMS_second_reg <= "000000";
        NEXT_UTC_MDHMS_minute_reg <= "000000";
        NEXT_UTC_MDHMS_utc_hr_reg <= "000000";
        NEXT_UTC_MDHMS_utc_day_reg <= "00000";
        NEXT_UTC_MDHMS_utc_mon_reg <= "0000";
        NEXT_UTC_MDHMS_wack <= '0';
      else
        if NEXT_UTC_MDHMS_wreq = '1' then
          NEXT_UTC_MDHMS_second_reg <= wr_dat_d0(5 downto 0);
          NEXT_UTC_MDHMS_minute_reg <= wr_dat_d0(11 downto 6);
          NEXT_UTC_MDHMS_utc_hr_reg <= wr_dat_d0(17 downto 12);
          NEXT_UTC_MDHMS_utc_day_reg <= wr_dat_d0(22 downto 18);
          NEXT_UTC_MDHMS_utc_mon_reg <= wr_dat_d0(26 downto 23);
        end if;
        NEXT_UTC_MDHMS_wack <= NEXT_UTC_MDHMS_wreq;
      end if;
    end if;
  end process;

  -- Register NEXT_UTC_Y
  timecode_regs_o.NEXT_UTC_Y_utc_year <= NEXT_UTC_Y_utc_year_reg;
  timecode_regs_o.NEXT_UTC_Y_utc_diy <= NEXT_UTC_Y_utc_diy_reg;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        NEXT_UTC_Y_utc_year_reg <= "000000000000";
        NEXT_UTC_Y_utc_diy_reg <= "000000000";
        NEXT_UTC_Y_wack <= '0';
      else
        if NEXT_UTC_Y_wreq = '1' then
          NEXT_UTC_Y_utc_year_reg <= wr_dat_d0(11 downto 0);
          NEXT_UTC_Y_utc_diy_reg <= wr_dat_d0(20 downto 12);
        end if;
        NEXT_UTC_Y_wack <= NEXT_UTC_Y_wreq;
      end if;
    end if;
  end process;

  -- Register NEXT_UTC_SBS
  timecode_regs_o.NEXT_UTC_SBS_utc_sbs <= NEXT_UTC_SBS_utc_sbs_reg;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        NEXT_UTC_SBS_utc_sbs_reg <= "00000000000000000";
        NEXT_UTC_SBS_wack <= '0';
      else
        if NEXT_UTC_SBS_wreq = '1' then
          NEXT_UTC_SBS_utc_sbs_reg <= wr_dat_d0(16 downto 0);
        end if;
        NEXT_UTC_SBS_wack <= NEXT_UTC_SBS_wreq;
      end if;
    end if;
  end process;

  -- Register NEXT_LEAP_SEC
  timecode_regs_o.NEXT_LEAP_SEC_ls_value <= NEXT_LEAP_SEC_ls_value_reg;
  timecode_regs_o.NEXT_LEAP_SEC_ls_flag59 <= NEXT_LEAP_SEC_ls_flag59_reg;
  timecode_regs_o.NEXT_LEAP_SEC_ls_flag61 <= NEXT_LEAP_SEC_ls_flag61_reg;
  timecode_regs_o.NEXT_LEAP_SEC_ls_valid <= NEXT_LEAP_SEC_ls_valid_reg;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        NEXT_LEAP_SEC_ls_value_reg <= "00000000";
        NEXT_LEAP_SEC_ls_flag59_reg <= '0';
        NEXT_LEAP_SEC_ls_flag61_reg <= '0';
        NEXT_LEAP_SEC_ls_valid_reg <= '0';
        NEXT_LEAP_SEC_wack <= '0';
      else
        if NEXT_LEAP_SEC_wreq = '1' then
          NEXT_LEAP_SEC_ls_value_reg <= wr_dat_d0(7 downto 0);
          NEXT_LEAP_SEC_ls_flag59_reg <= wr_dat_d0(8);
          NEXT_LEAP_SEC_ls_flag61_reg <= wr_dat_d0(9);
          NEXT_LEAP_SEC_ls_valid_reg <= wr_dat_d0(10);
        end if;
        NEXT_LEAP_SEC_wack <= NEXT_LEAP_SEC_wreq;
      end if;
    end if;
  end process;

  -- Register CURR_UTC_MDHMS

  -- Register CURR_UTC_Y

  -- Register CURR_UTC_SBS

  -- Register CURR_LEAP_SEC

  -- Interface auxclk
  auxclk_tr <= auxclk_wt or auxclk_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        auxclk_rt <= '0';
        auxclk_wt <= '0';
      else
        auxclk_rt <= (auxclk_rt or auxclk_re) and not auxclk_rack;
        auxclk_wt <= (auxclk_wt or auxclk_we) and not auxclk_wack;
      end if;
    end if;
  end process;
  auxclk_cyc_o <= auxclk_tr;
  auxclk_stb_o <= auxclk_tr;
  auxclk_wack <= auxclk_ack_i and auxclk_wt;
  auxclk_rack <= auxclk_ack_i and auxclk_rt;
  auxclk_adr_o <= wb_adr_i(2 downto 2);
  process (wr_sel_d0) begin
    auxclk_sel_o <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      auxclk_sel_o(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      auxclk_sel_o(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      auxclk_sel_o(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      auxclk_sel_o(3) <= '1';
    end if;
  end process;
  auxclk_we_o <= auxclk_wt;
  auxclk_dat_o <= wr_dat_d0;

  -- Interface nmea
  nmea_tr <= nmea_wt or nmea_rt;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        nmea_rt <= '0';
        nmea_wt <= '0';
      else
        nmea_rt <= (nmea_rt or nmea_re) and not nmea_rack;
        nmea_wt <= (nmea_wt or nmea_we) and not nmea_wack;
      end if;
    end if;
  end process;
  nmea_cyc_o <= nmea_tr;
  nmea_stb_o <= nmea_tr;
  nmea_wack <= nmea_ack_i and nmea_wt;
  nmea_rack <= nmea_ack_i and nmea_rt;
  nmea_adr_o <= wb_adr_i(3 downto 2);
  process (wr_sel_d0) begin
    nmea_sel_o <= (others => '0');
    if not (wr_sel_d0(7 downto 0) = (7 downto 0 => '0')) then
      nmea_sel_o(0) <= '1';
    end if;
    if not (wr_sel_d0(15 downto 8) = (7 downto 0 => '0')) then
      nmea_sel_o(1) <= '1';
    end if;
    if not (wr_sel_d0(23 downto 16) = (7 downto 0 => '0')) then
      nmea_sel_o(2) <= '1';
    end if;
    if not (wr_sel_d0(31 downto 24) = (7 downto 0 => '0')) then
      nmea_sel_o(3) <= '1';
    end if;
  end process;
  nmea_we_o <= nmea_wt;
  nmea_dat_o <= wr_dat_d0;

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0, CR_wack, NEXT_UTC_MDHMS_wack, NEXT_UTC_Y_wack,
           NEXT_UTC_SBS_wack, NEXT_LEAP_SEC_wack, auxclk_wack, nmea_wack) begin
    CR_wreq <= '0';
    NEXT_UTC_MDHMS_wreq <= '0';
    NEXT_UTC_Y_wreq <= '0';
    NEXT_UTC_SBS_wreq <= '0';
    NEXT_LEAP_SEC_wreq <= '0';
    auxclk_we <= '0';
    nmea_we <= '0';
    case wr_adr_d0(6 downto 4) is
    when "000" =>
      case wr_adr_d0(3 downto 2) is
      when "00" =>
        -- Reg CR
        CR_wreq <= wr_req_d0;
        wr_ack_int <= CR_wack;
      when "01" =>
        -- Reg SR
        wr_ack_int <= wr_req_d0;
      when others =>
        wr_ack_int <= wr_req_d0;
      end case;
    when "001" =>
      case wr_adr_d0(3 downto 2) is
      when "00" =>
        -- Reg NEXT_UTC_MDHMS
        NEXT_UTC_MDHMS_wreq <= wr_req_d0;
        wr_ack_int <= NEXT_UTC_MDHMS_wack;
      when "01" =>
        -- Reg NEXT_UTC_Y
        NEXT_UTC_Y_wreq <= wr_req_d0;
        wr_ack_int <= NEXT_UTC_Y_wack;
      when "10" =>
        -- Reg NEXT_UTC_SBS
        NEXT_UTC_SBS_wreq <= wr_req_d0;
        wr_ack_int <= NEXT_UTC_SBS_wack;
      when "11" =>
        -- Reg NEXT_LEAP_SEC
        NEXT_LEAP_SEC_wreq <= wr_req_d0;
        wr_ack_int <= NEXT_LEAP_SEC_wack;
      when others =>
        wr_ack_int <= wr_req_d0;
      end case;
    when "010" =>
      case wr_adr_d0(3 downto 2) is
      when "00" =>
        -- Reg CURR_UTC_MDHMS
        wr_ack_int <= wr_req_d0;
      when "01" =>
        -- Reg CURR_UTC_Y
        wr_ack_int <= wr_req_d0;
      when "10" =>
        -- Reg CURR_UTC_SBS
        wr_ack_int <= wr_req_d0;
      when "11" =>
        -- Reg CURR_LEAP_SEC
        wr_ack_int <= wr_req_d0;
      when others =>
        wr_ack_int <= wr_req_d0;
      end case;
    when "011" =>
      -- Submap auxclk
      auxclk_we <= wr_req_d0;
      wr_ack_int <= auxclk_wack;
    when "100" =>
      -- Submap nmea
      nmea_we <= wr_req_d0;
      wr_ack_int <= nmea_wack;
    when others =>
      wr_ack_int <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (wb_adr_i, rd_req_int, CR_valid_reg, CR_serdes_ip_sel_reg,
           timecode_regs_i.SR_valid, timecode_regs_i.SR_auxclk_enabled,
           timecode_regs_i.SR_irig_enabled, timecode_regs_i.SR_nmea_enabled,
           NEXT_UTC_MDHMS_second_reg, NEXT_UTC_MDHMS_minute_reg,
           NEXT_UTC_MDHMS_utc_hr_reg, NEXT_UTC_MDHMS_utc_day_reg,
           NEXT_UTC_MDHMS_utc_mon_reg, NEXT_UTC_Y_utc_year_reg,
           NEXT_UTC_Y_utc_diy_reg, NEXT_UTC_SBS_utc_sbs_reg,
           NEXT_LEAP_SEC_ls_value_reg, NEXT_LEAP_SEC_ls_flag59_reg,
           NEXT_LEAP_SEC_ls_flag61_reg, NEXT_LEAP_SEC_ls_valid_reg,
           timecode_regs_i.CURR_UTC_MDHMS_second,
           timecode_regs_i.CURR_UTC_MDHMS_minute,
           timecode_regs_i.CURR_UTC_MDHMS_utc_hr,
           timecode_regs_i.CURR_UTC_MDHMS_utc_day,
           timecode_regs_i.CURR_UTC_MDHMS_utc_mon,
           timecode_regs_i.CURR_UTC_Y_utc_year,
           timecode_regs_i.CURR_UTC_Y_utc_diy,
           timecode_regs_i.CURR_UTC_SBS_utc_sbs,
           timecode_regs_i.CURR_LEAP_SEC_ls_value,
           timecode_regs_i.CURR_LEAP_SEC_ls_flag59,
           timecode_regs_i.CURR_LEAP_SEC_ls_flag61,
           timecode_regs_i.CURR_LEAP_SEC_ls_valid, auxclk_dat_i, auxclk_rack,
           nmea_dat_i, nmea_rack) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    auxclk_re <= '0';
    nmea_re <= '0';
    case wb_adr_i(6 downto 4) is
    when "000" =>
      case wb_adr_i(3 downto 2) is
      when "00" =>
        -- Reg CR
        rd_ack_d0 <= rd_req_int;
        rd_dat_d0(0) <= CR_valid_reg;
        rd_dat_d0(2 downto 1) <= CR_serdes_ip_sel_reg;
        rd_dat_d0(31 downto 3) <= (others => '0');
      when "01" =>
        -- Reg SR
        rd_ack_d0 <= rd_req_int;
        rd_dat_d0(0) <= timecode_regs_i.SR_valid;
        rd_dat_d0(1) <= timecode_regs_i.SR_auxclk_enabled;
        rd_dat_d0(2) <= timecode_regs_i.SR_irig_enabled;
        rd_dat_d0(3) <= timecode_regs_i.SR_nmea_enabled;
        rd_dat_d0(31 downto 4) <= (others => '0');
      when others =>
        rd_ack_d0 <= rd_req_int;
      end case;
    when "001" =>
      case wb_adr_i(3 downto 2) is
      when "00" =>
        -- Reg NEXT_UTC_MDHMS
        rd_ack_d0 <= rd_req_int;
        rd_dat_d0(5 downto 0) <= NEXT_UTC_MDHMS_second_reg;
        rd_dat_d0(11 downto 6) <= NEXT_UTC_MDHMS_minute_reg;
        rd_dat_d0(17 downto 12) <= NEXT_UTC_MDHMS_utc_hr_reg;
        rd_dat_d0(22 downto 18) <= NEXT_UTC_MDHMS_utc_day_reg;
        rd_dat_d0(26 downto 23) <= NEXT_UTC_MDHMS_utc_mon_reg;
        rd_dat_d0(31 downto 27) <= (others => '0');
      when "01" =>
        -- Reg NEXT_UTC_Y
        rd_ack_d0 <= rd_req_int;
        rd_dat_d0(11 downto 0) <= NEXT_UTC_Y_utc_year_reg;
        rd_dat_d0(20 downto 12) <= NEXT_UTC_Y_utc_diy_reg;
        rd_dat_d0(31 downto 21) <= (others => '0');
      when "10" =>
        -- Reg NEXT_UTC_SBS
        rd_ack_d0 <= rd_req_int;
        rd_dat_d0(16 downto 0) <= NEXT_UTC_SBS_utc_sbs_reg;
        rd_dat_d0(31 downto 17) <= (others => '0');
      when "11" =>
        -- Reg NEXT_LEAP_SEC
        rd_ack_d0 <= rd_req_int;
        rd_dat_d0(7 downto 0) <= NEXT_LEAP_SEC_ls_value_reg;
        rd_dat_d0(8) <= NEXT_LEAP_SEC_ls_flag59_reg;
        rd_dat_d0(9) <= NEXT_LEAP_SEC_ls_flag61_reg;
        rd_dat_d0(10) <= NEXT_LEAP_SEC_ls_valid_reg;
        rd_dat_d0(31 downto 11) <= (others => '0');
      when others =>
        rd_ack_d0 <= rd_req_int;
      end case;
    when "010" =>
      case wb_adr_i(3 downto 2) is
      when "00" =>
        -- Reg CURR_UTC_MDHMS
        rd_ack_d0 <= rd_req_int;
        rd_dat_d0(5 downto 0) <= timecode_regs_i.CURR_UTC_MDHMS_second;
        rd_dat_d0(11 downto 6) <= timecode_regs_i.CURR_UTC_MDHMS_minute;
        rd_dat_d0(17 downto 12) <= timecode_regs_i.CURR_UTC_MDHMS_utc_hr;
        rd_dat_d0(22 downto 18) <= timecode_regs_i.CURR_UTC_MDHMS_utc_day;
        rd_dat_d0(26 downto 23) <= timecode_regs_i.CURR_UTC_MDHMS_utc_mon;
        rd_dat_d0(31 downto 27) <= (others => '0');
      when "01" =>
        -- Reg CURR_UTC_Y
        rd_ack_d0 <= rd_req_int;
        rd_dat_d0(11 downto 0) <= timecode_regs_i.CURR_UTC_Y_utc_year;
        rd_dat_d0(20 downto 12) <= timecode_regs_i.CURR_UTC_Y_utc_diy;
        rd_dat_d0(31 downto 21) <= (others => '0');
      when "10" =>
        -- Reg CURR_UTC_SBS
        rd_ack_d0 <= rd_req_int;
        rd_dat_d0(16 downto 0) <= timecode_regs_i.CURR_UTC_SBS_utc_sbs;
        rd_dat_d0(31 downto 17) <= (others => '0');
      when "11" =>
        -- Reg CURR_LEAP_SEC
        rd_ack_d0 <= rd_req_int;
        rd_dat_d0(7 downto 0) <= timecode_regs_i.CURR_LEAP_SEC_ls_value;
        rd_dat_d0(8) <= timecode_regs_i.CURR_LEAP_SEC_ls_flag59;
        rd_dat_d0(9) <= timecode_regs_i.CURR_LEAP_SEC_ls_flag61;
        rd_dat_d0(10) <= timecode_regs_i.CURR_LEAP_SEC_ls_valid;
        rd_dat_d0(31 downto 11) <= (others => '0');
      when others =>
        rd_ack_d0 <= rd_req_int;
      end case;
    when "011" =>
      -- Submap auxclk
      auxclk_re <= rd_req_int;
      rd_dat_d0 <= auxclk_dat_i;
      rd_ack_d0 <= auxclk_rack;
    when "100" =>
      -- Submap nmea
      nmea_re <= rd_req_int;
      rd_dat_d0 <= nmea_dat_i;
      rd_ack_d0 <= nmea_rack;
    when others =>
      rd_ack_d0 <= rd_req_int;
    end case;
  end process;
end syn;
