-- Do not edit.  Generated by cheby 1.7.dev0 using these options:
--  -i spll_host_map.cheby --header=commit --gen-hdl spll_host_map.vhd --gen-c spll_host_map.h


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;

entity spll_host_map is
  port (
    rst_n_i              : in    std_logic;
    clk_i                : in    std_logic;
    wb_i                 : in    t_wishbone_slave_in;
    wb_o                 : out   t_wishbone_slave_out;

    -- Fifo output (data)
    DFR_HOST_R0_i        : in    std_logic_vector(31 downto 0);
    DFR_HOST_R0_rd_o     : out   std_logic;

    -- Fifo status
    -- FIFO count
    DFR_HOST_CSR_USEDW_i : in    std_logic_vector(12 downto 0);
    -- Set when FIFO is empty
    DFR_HOST_CSR_EMPTY_i : in    std_logic
  );
end spll_host_map;

architecture syn of spll_host_map is
  signal adr_int                        : std_logic_vector(3 downto 2);
  signal rd_req_int                     : std_logic;
  signal wr_req_int                     : std_logic;
  signal rd_ack_int                     : std_logic;
  signal wr_ack_int                     : std_logic;
  signal wb_en                          : std_logic;
  signal ack_int                        : std_logic;
  signal wb_rip                         : std_logic;
  signal wb_wip                         : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(3 downto 2);
begin

  -- WB decode signals
  adr_int <= wb_i.adr(3 downto 2);
  wb_en <= wb_i.cyc and wb_i.stb;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_rip <= '0';
      else
        wb_rip <= (wb_rip or (wb_en and not wb_i.we)) and not rd_ack_int;
      end if;
    end if;
  end process;
  rd_req_int <= (wb_en and not wb_i.we) and not wb_rip;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_wip <= '0';
      else
        wb_wip <= (wb_wip or (wb_en and wb_i.we)) and not wr_ack_int;
      end if;
    end if;
  end process;
  wr_req_int <= (wb_en and wb_i.we) and not wb_wip;

  ack_int <= rd_ack_int or wr_ack_int;
  wb_o.ack <= ack_int;
  wb_o.stall <= not ack_int and wb_en;
  wb_o.rty <= '0';
  wb_o.err <= '0';

  -- pipelining for wr-in+rd-out
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        rd_ack_int <= '0';
        wb_o.dat <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_adr_d0 <= "00";
      else
        rd_ack_int <= rd_ack_d0;
        wb_o.dat <= rd_dat_d0;
        wr_req_d0 <= wr_req_int;
        wr_adr_d0 <= adr_int;
      end if;
    end if;
  end process;

  -- Register DFR_HOST_R0

  -- Register DFR_HOST_CSR

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0) begin
    case wr_adr_d0(3 downto 2) is
    when "00" =>
      -- Reg DFR_HOST_R0
      wr_ack_int <= wr_req_d0;
    when "10" =>
      -- Reg DFR_HOST_CSR
      wr_ack_int <= wr_req_d0;
    when others =>
      wr_ack_int <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (adr_int, rd_req_int, DFR_HOST_R0_i, DFR_HOST_CSR_USEDW_i,
           DFR_HOST_CSR_EMPTY_i) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    DFR_HOST_R0_rd_o <= '0';
    case adr_int(3 downto 2) is
    when "00" =>
      -- Reg DFR_HOST_R0
      DFR_HOST_R0_rd_o <= rd_req_int;
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= DFR_HOST_R0_i;
    when "10" =>
      -- Reg DFR_HOST_CSR
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(12 downto 0) <= DFR_HOST_CSR_USEDW_i;
      rd_dat_d0(16 downto 13) <= (others => '0');
      rd_dat_d0(17) <= DFR_HOST_CSR_EMPTY_i;
      rd_dat_d0(31 downto 18) <= (others => '0');
    when others =>
      rd_ack_d0 <= rd_req_int;
    end case;
  end process;
end syn;
