-------------------------------------------------------------------------------
-- SPDX-FileCopyrightText: 2010 CERN (home.cern)
--
-- SPDX-License-Identifier: CERN-OHL-W-2.0+
-------------------------------------------------------------------------------
-- Do not edit.  Generated by cheby 1.7.dev0 using these options:
--  -i wr_mini_nic_map.cheby --header=commit --gen-hdl


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;

package wr_mini_nic_map_pkg is
  type t_mini_nic_regs_master_out is record
    mcr_tx_start     : std_logic;
    mcr_tx_idle      : std_logic;
    mcr_tx_error     : std_logic;
    mcr_tx_empty     : std_logic;
    mcr_tx_full      : std_logic;
    mcr_rx_ready     : std_logic;
    mcr_rx_error     : std_logic;
    mcr_rx_en        : std_logic;
    mcr_tx_ts_ready  : std_logic;
    mcr_rx_empty     : std_logic;
    mcr_rx_full      : std_logic;
    mcr_VER          : std_logic_vector(3 downto 0);
    mcr_wr           : std_logic;
    tx_fifo_dat      : std_logic_vector(15 downto 0);
    tx_fifo_type     : std_logic_vector(1 downto 0);
    tx_fifo_wr       : std_logic;
    rx_fifo_rd       : std_logic;
    tsr1_rd          : std_logic;
  end record t_mini_nic_regs_master_out;
  subtype t_mini_nic_regs_slave_in is t_mini_nic_regs_master_out;

  type t_mini_nic_regs_slave_out is record
    mcr_tx_start     : std_logic;
    mcr_tx_idle      : std_logic;
    mcr_tx_error     : std_logic;
    mcr_tx_empty     : std_logic;
    mcr_tx_full      : std_logic;
    mcr_rx_ready     : std_logic;
    mcr_rx_error     : std_logic;
    mcr_rx_en        : std_logic;
    mcr_tx_ts_ready  : std_logic;
    mcr_rx_empty     : std_logic;
    mcr_rx_full      : std_logic;
    mcr_VER          : std_logic_vector(3 downto 0);
    rx_fifo_dat      : std_logic_vector(15 downto 0);
    rx_fifo_type     : std_logic_vector(1 downto 0);
    rx_fifo_empty    : std_logic;
    rx_fifo_full     : std_logic;
    tsr0_valid       : std_logic;
    tsr0_pid         : std_logic_vector(4 downto 0);
    tsr0_fid         : std_logic_vector(15 downto 0);
    tsr1_tsval       : std_logic_vector(31 downto 0);
  end record t_mini_nic_regs_slave_out;
  subtype t_mini_nic_regs_master_in is t_mini_nic_regs_slave_out;

end wr_mini_nic_map_pkg;

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;
use work.wr_mini_nic_map_pkg.all;

entity wr_mini_nic_map is
  port (
    rst_n_i              : in    std_logic;
    clk_i                : in    std_logic;
    wb_i                 : in    t_wishbone_slave_in;
    wb_o                 : out   t_wishbone_slave_out;
    -- Wires and registers
    mini_nic_regs_i      : in    t_mini_nic_regs_master_in;
    mini_nic_regs_o      : out   t_mini_nic_regs_master_out
  );
end wr_mini_nic_map;

architecture syn of wr_mini_nic_map is
  signal adr_int                        : std_logic_vector(4 downto 2);
  signal rd_req_int                     : std_logic;
  signal wr_req_int                     : std_logic;
  signal rd_ack_int                     : std_logic;
  signal wr_ack_int                     : std_logic;
  signal wb_en                          : std_logic;
  signal ack_int                        : std_logic;
  signal wb_rip                         : std_logic;
  signal wb_wip                         : std_logic;
  signal mcr_wreq                       : std_logic;
  signal tx_fifo_wreq                   : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(4 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
begin

  -- WB decode signals
  adr_int <= wb_i.adr(4 downto 2);
  wb_en <= wb_i.cyc and wb_i.stb;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_rip <= '0';
      else
        wb_rip <= (wb_rip or (wb_en and not wb_i.we)) and not rd_ack_int;
      end if;
    end if;
  end process;
  rd_req_int <= (wb_en and not wb_i.we) and not wb_rip;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_wip <= '0';
      else
        wb_wip <= (wb_wip or (wb_en and wb_i.we)) and not wr_ack_int;
      end if;
    end if;
  end process;
  wr_req_int <= (wb_en and wb_i.we) and not wb_wip;

  ack_int <= rd_ack_int or wr_ack_int;
  wb_o.ack <= ack_int;
  wb_o.stall <= not ack_int and wb_en;
  wb_o.rty <= '0';
  wb_o.err <= '0';

  -- pipelining for wr-in+rd-out
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        rd_ack_int <= '0';
        wb_o.dat <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_adr_d0 <= "000";
        wr_dat_d0 <= "00000000000000000000000000000000";
      else
        rd_ack_int <= rd_ack_d0;
        wb_o.dat <= rd_dat_d0;
        wr_req_d0 <= wr_req_int;
        wr_adr_d0 <= adr_int;
        wr_dat_d0 <= wb_i.dat;
      end if;
    end if;
  end process;

  -- Register mcr
  mini_nic_regs_o.mcr_tx_start <= wr_dat_d0(0);
  mini_nic_regs_o.mcr_tx_idle <= wr_dat_d0(1);
  mini_nic_regs_o.mcr_tx_error <= wr_dat_d0(2);
  mini_nic_regs_o.mcr_tx_empty <= wr_dat_d0(3);
  mini_nic_regs_o.mcr_tx_full <= wr_dat_d0(4);
  mini_nic_regs_o.mcr_rx_ready <= wr_dat_d0(8);
  mini_nic_regs_o.mcr_rx_error <= wr_dat_d0(9);
  mini_nic_regs_o.mcr_rx_en <= wr_dat_d0(10);
  mini_nic_regs_o.mcr_tx_ts_ready <= wr_dat_d0(11);
  mini_nic_regs_o.mcr_rx_empty <= wr_dat_d0(12);
  mini_nic_regs_o.mcr_rx_full <= wr_dat_d0(13);
  mini_nic_regs_o.mcr_VER <= wr_dat_d0(27 downto 24);
  mini_nic_regs_o.mcr_wr <= mcr_wreq;

  -- Register tx_fifo
  mini_nic_regs_o.tx_fifo_dat <= wr_dat_d0(15 downto 0);
  mini_nic_regs_o.tx_fifo_type <= wr_dat_d0(17 downto 16);
  mini_nic_regs_o.tx_fifo_wr <= tx_fifo_wreq;

  -- Register rx_fifo

  -- Register tsr0

  -- Register tsr1

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0) begin
    mcr_wreq <= '0';
    tx_fifo_wreq <= '0';
    case wr_adr_d0(4 downto 2) is
    when "000" =>
      -- Reg mcr
      mcr_wreq <= wr_req_d0;
      wr_ack_int <= wr_req_d0;
    when "001" =>
      -- Reg tx_fifo
      tx_fifo_wreq <= wr_req_d0;
      wr_ack_int <= wr_req_d0;
    when "010" =>
      -- Reg rx_fifo
      wr_ack_int <= wr_req_d0;
    when "101" =>
      -- Reg tsr0
      wr_ack_int <= wr_req_d0;
    when "110" =>
      -- Reg tsr1
      wr_ack_int <= wr_req_d0;
    when others =>
      wr_ack_int <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (adr_int, rd_req_int, mini_nic_regs_i.mcr_tx_start,
           mini_nic_regs_i.mcr_tx_idle, mini_nic_regs_i.mcr_tx_error,
           mini_nic_regs_i.mcr_tx_empty, mini_nic_regs_i.mcr_tx_full,
           mini_nic_regs_i.mcr_rx_ready, mini_nic_regs_i.mcr_rx_error,
           mini_nic_regs_i.mcr_rx_en, mini_nic_regs_i.mcr_tx_ts_ready,
           mini_nic_regs_i.mcr_rx_empty, mini_nic_regs_i.mcr_rx_full,
           mini_nic_regs_i.mcr_VER, mini_nic_regs_i.rx_fifo_dat,
           mini_nic_regs_i.rx_fifo_type, mini_nic_regs_i.rx_fifo_empty,
           mini_nic_regs_i.rx_fifo_full, mini_nic_regs_i.tsr0_valid,
           mini_nic_regs_i.tsr0_pid, mini_nic_regs_i.tsr0_fid,
           mini_nic_regs_i.tsr1_tsval) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    mini_nic_regs_o.rx_fifo_rd <= '0';
    mini_nic_regs_o.tsr1_rd <= '0';
    case adr_int(4 downto 2) is
    when "000" =>
      -- Reg mcr
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(0) <= mini_nic_regs_i.mcr_tx_start;
      rd_dat_d0(1) <= mini_nic_regs_i.mcr_tx_idle;
      rd_dat_d0(2) <= mini_nic_regs_i.mcr_tx_error;
      rd_dat_d0(3) <= mini_nic_regs_i.mcr_tx_empty;
      rd_dat_d0(4) <= mini_nic_regs_i.mcr_tx_full;
      rd_dat_d0(7 downto 5) <= (others => '0');
      rd_dat_d0(8) <= mini_nic_regs_i.mcr_rx_ready;
      rd_dat_d0(9) <= mini_nic_regs_i.mcr_rx_error;
      rd_dat_d0(10) <= mini_nic_regs_i.mcr_rx_en;
      rd_dat_d0(11) <= mini_nic_regs_i.mcr_tx_ts_ready;
      rd_dat_d0(12) <= mini_nic_regs_i.mcr_rx_empty;
      rd_dat_d0(13) <= mini_nic_regs_i.mcr_rx_full;
      rd_dat_d0(23 downto 14) <= (others => '0');
      rd_dat_d0(27 downto 24) <= mini_nic_regs_i.mcr_VER;
      rd_dat_d0(31 downto 28) <= (others => '0');
    when "001" =>
      -- Reg tx_fifo
      rd_ack_d0 <= rd_req_int;
    when "010" =>
      -- Reg rx_fifo
      mini_nic_regs_o.rx_fifo_rd <= rd_req_int;
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(15 downto 0) <= mini_nic_regs_i.rx_fifo_dat;
      rd_dat_d0(17 downto 16) <= mini_nic_regs_i.rx_fifo_type;
      rd_dat_d0(29 downto 18) <= (others => '0');
      rd_dat_d0(30) <= mini_nic_regs_i.rx_fifo_empty;
      rd_dat_d0(31) <= mini_nic_regs_i.rx_fifo_full;
    when "101" =>
      -- Reg tsr0
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(0) <= mini_nic_regs_i.tsr0_valid;
      rd_dat_d0(5 downto 1) <= mini_nic_regs_i.tsr0_pid;
      rd_dat_d0(21 downto 6) <= mini_nic_regs_i.tsr0_fid;
      rd_dat_d0(31 downto 22) <= (others => '0');
    when "110" =>
      -- Reg tsr1
      mini_nic_regs_o.tsr1_rd <= rd_req_int;
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= mini_nic_regs_i.tsr1_tsval;
    when others =>
      rd_ack_d0 <= rd_req_int;
    end case;
  end process;
end syn;
