-------------------------------------------------------------------------------
-- SPDX-FileCopyrightText: 2026 CERN (home.cern)
--
-- SPDX-License-Identifier: CERN-OHL-W-2.0+
-------------------------------------------------------------------------------
-- Do not edit.  Generated by cheby 1.7.dev0 using these options:
--  --gen-hdl epx_mininic_map.vhd --gen-c epx_mininic_map.h -i epx_mininic_map.cheby
-- Generated on Wed Jul 02 13:16:22 2025 by tgingold


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;

entity epx_mininic_map is
  port (
    rst_n_i              : in    std_logic;
    clk_i                : in    std_logic;
    wb_i                 : in    t_wishbone_slave_in;
    wb_o                 : out   t_wishbone_slave_out;

    -- control register (mainly reset)
    ctrl_rxreset_o       : out   std_logic;

    -- status register
    stat_rxpkt_i         : in    std_logic;
    stat_rxlocked_i      : in    std_logic;
    stat_txdone_i        : in    std_logic;

    -- length of the current RX packet
    rxlen_nbytes_i       : in    std_logic_vector(2 downto 0);
    rxlen_len8_i         : in    std_logic_vector(12 downto 0);
    rxlen_rem8_i         : in    std_logic_vector(12 downto 0);

    -- high word of rx data 8B block
    rxdatah_i            : in    std_logic_vector(31 downto 0);

    -- low word of rx data 8B block, advance the buffer
    rxdatal_i            : in    std_logic_vector(31 downto 0);
    rxdatal_rd_o         : out   std_logic;

    -- length of the current TX packet and trigger xmit
    txlen_nbytes_o       : out   std_logic_vector(2 downto 0);
    txlen_len8_o         : out   std_logic_vector(12 downto 0);
    txlen_wr_o           : out   std_logic;

    -- high word of tx data 8B block
    txdatah_o            : out   std_logic_vector(31 downto 0);

    -- low word of tx data 8B block, advance the buffer
    txdatal_o            : out   std_logic_vector(31 downto 0);
    txdatal_wr_o         : out   std_logic;

    -- Current address in tx buffer - for debug
    txaddr_i             : in    std_logic_vector(31 downto 0)
  );
end epx_mininic_map;

architecture syn of epx_mininic_map is
  signal adr_int                        : std_logic_vector(5 downto 2);
  signal rd_req_int                     : std_logic;
  signal wr_req_int                     : std_logic;
  signal rd_ack_int                     : std_logic;
  signal wr_ack_int                     : std_logic;
  signal wb_en                          : std_logic;
  signal ack_int                        : std_logic;
  signal wb_rip                         : std_logic;
  signal wb_wip                         : std_logic;
  signal ctrl_rxreset_reg               : std_logic;
  signal ctrl_wreq                      : std_logic;
  signal ctrl_wack                      : std_logic;
  signal txlen_nbytes_reg               : std_logic_vector(2 downto 0);
  signal txlen_len8_reg                 : std_logic_vector(12 downto 0);
  signal txlen_wreq                     : std_logic;
  signal txlen_wack                     : std_logic;
  signal txlen_wstrb                    : std_logic;
  signal txdatah_reg                    : std_logic_vector(31 downto 0);
  signal txdatah_wreq                   : std_logic;
  signal txdatah_wack                   : std_logic;
  signal txdatal_reg                    : std_logic_vector(31 downto 0);
  signal txdatal_wreq                   : std_logic;
  signal txdatal_wack                   : std_logic;
  signal txdatal_wstrb                  : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(5 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
begin

  -- WB decode signals
  adr_int <= wb_i.adr(5 downto 2);
  wb_en <= wb_i.cyc and wb_i.stb;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_rip <= '0';
      else
        wb_rip <= (wb_rip or (wb_en and not wb_i.we)) and not rd_ack_int;
      end if;
    end if;
  end process;
  rd_req_int <= (wb_en and not wb_i.we) and not wb_rip;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_wip <= '0';
      else
        wb_wip <= (wb_wip or (wb_en and wb_i.we)) and not wr_ack_int;
      end if;
    end if;
  end process;
  wr_req_int <= (wb_en and wb_i.we) and not wb_wip;

  ack_int <= rd_ack_int or wr_ack_int;
  wb_o.ack <= ack_int;
  wb_o.stall <= not ack_int and wb_en;
  wb_o.rty <= '0';
  wb_o.err <= '0';

  -- pipelining for wr-in+rd-out
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        rd_ack_int <= '0';
        wb_o.dat <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_adr_d0 <= "0000";
        wr_dat_d0 <= "00000000000000000000000000000000";
      else
        rd_ack_int <= rd_ack_d0;
        wb_o.dat <= rd_dat_d0;
        wr_req_d0 <= wr_req_int;
        wr_adr_d0 <= adr_int;
        wr_dat_d0 <= wb_i.dat;
      end if;
    end if;
  end process;

  -- Register ctrl
  ctrl_rxreset_o <= ctrl_rxreset_reg;
  ctrl_wack <= ctrl_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        ctrl_rxreset_reg <= '0';
      else
        if ctrl_wreq = '1' then
          ctrl_rxreset_reg <= wr_dat_d0(0);
        end if;
      end if;
    end if;
  end process;

  -- Register stat

  -- Register rxlen

  -- Register rxdatah

  -- Register rxdatal

  -- Register txlen
  txlen_nbytes_o <= txlen_nbytes_reg;
  txlen_len8_o <= txlen_len8_reg;
  txlen_wack <= txlen_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        txlen_nbytes_reg <= "000";
        txlen_len8_reg <= "0000000000000";
        txlen_wstrb <= '0';
      else
        if txlen_wreq = '1' then
          txlen_nbytes_reg <= wr_dat_d0(2 downto 0);
          txlen_len8_reg <= wr_dat_d0(15 downto 3);
        end if;
        txlen_wstrb <= txlen_wreq;
      end if;
    end if;
  end process;
  txlen_wr_o <= txlen_wstrb;

  -- Register txdatah
  txdatah_o <= txdatah_reg;
  txdatah_wack <= txdatah_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        txdatah_reg <= "00000000000000000000000000000000";
      else
        if txdatah_wreq = '1' then
          txdatah_reg <= wr_dat_d0;
        end if;
      end if;
    end if;
  end process;

  -- Register txdatal
  txdatal_o <= txdatal_reg;
  txdatal_wack <= txdatal_wreq;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        txdatal_reg <= "00000000000000000000000000000000";
        txdatal_wstrb <= '0';
      else
        if txdatal_wreq = '1' then
          txdatal_reg <= wr_dat_d0;
        end if;
        txdatal_wstrb <= txdatal_wreq;
      end if;
    end if;
  end process;
  txdatal_wr_o <= txdatal_wstrb;

  -- Register txaddr

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0, ctrl_wack, txlen_wack, txdatah_wack, txdatal_wack) begin
    ctrl_wreq <= '0';
    txlen_wreq <= '0';
    txdatah_wreq <= '0';
    txdatal_wreq <= '0';
    case wr_adr_d0(5 downto 2) is
    when "0000" =>
      -- Reg ctrl
      ctrl_wreq <= wr_req_d0;
      wr_ack_int <= ctrl_wack;
    when "0001" =>
      -- Reg stat
      wr_ack_int <= wr_req_d0;
    when "0010" =>
      -- Reg rxlen
      wr_ack_int <= wr_req_d0;
    when "0011" =>
      -- Reg rxdatah
      wr_ack_int <= wr_req_d0;
    when "0100" =>
      -- Reg rxdatal
      wr_ack_int <= wr_req_d0;
    when "0101" =>
      -- Reg txlen
      txlen_wreq <= wr_req_d0;
      wr_ack_int <= txlen_wack;
    when "0110" =>
      -- Reg txdatah
      txdatah_wreq <= wr_req_d0;
      wr_ack_int <= txdatah_wack;
    when "0111" =>
      -- Reg txdatal
      txdatal_wreq <= wr_req_d0;
      wr_ack_int <= txdatal_wack;
    when "1000" =>
      -- Reg txaddr
      wr_ack_int <= wr_req_d0;
    when others =>
      wr_ack_int <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (adr_int, rd_req_int, ctrl_rxreset_reg, stat_rxpkt_i, stat_rxlocked_i,
           stat_txdone_i, rxlen_nbytes_i, rxlen_len8_i, rxlen_rem8_i, rxdatah_i,
           rxdatal_i, txdatah_reg, txdatal_reg, txaddr_i) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    rxdatal_rd_o <= '0';
    case adr_int(5 downto 2) is
    when "0000" =>
      -- Reg ctrl
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(0) <= ctrl_rxreset_reg;
      rd_dat_d0(31 downto 1) <= (others => '0');
    when "0001" =>
      -- Reg stat
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(0) <= stat_rxpkt_i;
      rd_dat_d0(1) <= stat_rxlocked_i;
      rd_dat_d0(2) <= stat_txdone_i;
      rd_dat_d0(31 downto 3) <= (others => '0');
    when "0010" =>
      -- Reg rxlen
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(2 downto 0) <= rxlen_nbytes_i;
      rd_dat_d0(15 downto 3) <= rxlen_len8_i;
      rd_dat_d0(28 downto 16) <= rxlen_rem8_i;
      rd_dat_d0(31 downto 29) <= (others => '0');
    when "0011" =>
      -- Reg rxdatah
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= rxdatah_i;
    when "0100" =>
      -- Reg rxdatal
      rxdatal_rd_o <= rd_req_int;
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= rxdatal_i;
    when "0101" =>
      -- Reg txlen
      rd_ack_d0 <= rd_req_int;
    when "0110" =>
      -- Reg txdatah
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= txdatah_reg;
    when "0111" =>
      -- Reg txdatal
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= txdatal_reg;
    when "1000" =>
      -- Reg txaddr
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= txaddr_i;
    when others =>
      rd_ack_d0 <= rd_req_int;
    end case;
  end process;
end syn;
